### ISSUE TITLE
[NFAuthenticationKey] module 'numpy' has no attribute 'frombuffer'

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [CastagnaIT/plugin.video.netflix#1055]
## Bug report

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [x] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Error when running the auth python script

```
Press "ENTER" key to accept the disclaimer and start, or "CTRL+C" to cancel
Browser startup... (/Applications/Google Chrome.app/Contents/MacOS/Google Chrome) please wait
Establish connection with the browser... please wait
An error is occurred:
module 'numpy' has no attribute 'frombuffer'
Traceback (most recent call last):
  File "/Users/benjamin/Downloads/NFAuthenticationKey/NFAuthenticationKey.py", line 62, in __init__
    self.operations()
  File "/Users/benjamin/Downloads/NFAuthenticationKey/NFAuthenticationKey.py", line 83, in operations
    self.ws_request('Network.enable')
  File "/Users/benjamin/Downloads/NFAuthenticationKey/NFAuthenticationKey.py", line 170, in ws_request
    self._ws.send(message)
  File "/Users/benjamin/Library/Python/3.9/lib/python/site-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
  File "/Users/benjamin/Library/Python/3.9/lib/python/site-packages/websocket/_core.py", line 272, in send_frame
    data = frame.format()
  File "/Users/benjamin/Library/Python/3.9/lib/python/site-packages/websocket/_abnf.py", line 242, in format
    return frame_header + self._get_masked(mask_key)
  File "/Users/benjamin/Library/Python/3.9/lib/python/site-packages/websocket/_abnf.py", line 245, in _get_masked
    s = ABNF.mask(mask_key, self.data)
  File "/Users/benjamin/Library/Python/3.9/lib/python/site-packages/websocket/_abnf.py", line 276, in mask
    a = numpy.frombuffer(data, dtype="uint32")
AttributeError: module 'numpy' has no attribute 'frombuffer'
```
#### Possible fix

`pip3 install numpy` worked for me

**Comment by BenjaminVanRyseghem** [comment]
The template does not apply as the error is not in the plugin itself, but in the authentication script

**Comment by CastagnaIT** [comment]
this is a websocket-client module problem not depends from our script
`numpy` module is not a prerequisite to use `websocket-client` module

so something is not working properly or not full compatible in your configuration,
you have to report the issue here:
https://github.com/websocket-client/websocket-client/issues
