### ISSUE TITLE
Plugin won't start. (  Error Contents: 'NoneType' object has no attribute 'split' )

### ISSUE THREAD

**Issue by Uglymotha** [CastagnaIT/plugin.video.netflix#1088]
#### Your Environment
Kodi 19 - Matrix (official XBMC team version)
plugin.video.netflix v1.14.0+matrix.1 installed
Ubuntu 20.04.2 LTS (GNU/Linux 5.8.0-44-generic x86_64)
Pyhton3 only, python2 is completely removed from system.

### Describe the bug
Netflix Error when kodi starts. Python error in kodi.log:
2021-02-23 09:03:06.886 T:2016    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'split'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/service.py", line 13, in <module>
                                                       run(sys.argv)
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/run_service.py", line 157, in run
                                                       check_service_upgrade()
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/upgrade_controller.py", line 52, in check_service_upgrade
                                                       _perform_service_changes(service_previous_ver, service_current_ver)
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/upgrade_controller.py", line 74, in _perform_service_changes
                                                       if is_less_version(previous_ver, '1.13'):
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 164, in is_less_version
                                                       return list(map(int, version.split('.'))) < list(map(int, max_version.split('.')))
                                                   AttributeError: 'NoneType' object has no attribute 'split'
                                                   -->End of Python script error report<--

2021-02-23 09:03:06.905 T:1957  WARNING <general>: CActiveAE::StateMachine - signal: 1 from port: OutputDataPort not handled for state: 2
2021-02-23 09:03:07.049 T:2016     INFO <general>: Python interpreter stopped

#### Expected behavior
Functioning plugin

#### Actual behavior
Non-functioning plugin

#### Steps to reproduce the behavior
install plugin and run.

**Comment by Uglymotha** [comment]
This was a clean install, and I see this is already fixed in git:
74    if previous_ver and is_less_version(previous_ver, '1.13'):

**Comment by chgardener** [comment]
Same problem under Ubuntu 20.10

**Comment by PaulCoddington** [comment]
> This was a clean install, and I see this is already fixed in git:
> 74 if previous_ver and is_less_version(previous_ver, '1.13'):

Repository ZIP does not contain a fix yet. Will the fix propagate automatically in the near future if we just leave 1.14 installed as is?

**Comment by CastagnaIT** [comment]
the fix is in daily build,
if there are no delays the fixed version will be released tomorrow

**Comment by PaulCoddington** [comment]
> the fix is in daily build,
> if there are no delays the fixed version will be released tomorrow

Excellent news! Thank you for all your hard work.
