### ISSUE TITLE
Exception:  KeyError Error details: 'loco'

### ISSUE THREAD

**Issue by kmedcalf** [CastagnaIT/plugin.video.netflix#1120]
#### Your Environment
- Netflix add-on version: 1.14.1+matrix.1
- Operating system version/name: Android TV
- Device model:  NVidia ShieldTV

Used Operating system:
* [ X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
When opening a NetFlix session, the session syncronization fails.  Attempted to uninstall and reinstall.  No difference.  Still ABENDs after successful logon when attempting to sync session.

#### Expected behavior
Expect categories list

#### Actual behavior
Exception: KeyError
Error details:
'loco'

#### Steps to reproduce the behavior
Start Plugin (after login)

#### Possible fix
key is not found in dictionary

### Debug log
2021-03-30 20:31:44.150 T:25057   DEBUG <general>: ------ Window Deinit (DialogKeyboard.xml) ------
2021-03-30 20:31:46.037 T:25094   ERROR <general>: [plugin.video.netflix (0)] Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py", line 133, in login
                                                       website.extract_session_data(login_response, validate=True, update_profiles=True)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 142, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/utils/website.py", line 87, in extract_session_data
                                                       loco_root = falcor_cache['loco']['value'][1]
                                                   KeyError: 'loco'

2021-03-30 20:31:46.037 T:25094   ERROR <general>: [plugin.video.netflix (0)] IPC callback raised exception: 'loco'
2021-03-30 20:31:46.038 T:25094   ERROR <general>: [plugin.video.netflix (0)] Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 193, in _perform_ipc_return_call
                                                       result = _call(func, data)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 231, in _call
                                                       return func(**data)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 142, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py", line 133, in login
                                                       website.extract_session_data(login_response, validate=True, update_profiles=True)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 142, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/utils/website.py", line 87, in extract_session_data
                                                       loco_root = falcor_cache['loco']['value'][1]
                                                   KeyError: 'loco'

2021-03-30 20:31:46.064 T:25135   ERROR <general>: [plugin.video.netflix (1)] Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 29, in wrapper
                                                       func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 252, in run
                                                       success = route(pathitems)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 85, in lazy_login_wrapper
                                                       if _check_valid_credentials():
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 70, in _check_valid_credentials
                                                       if not login():
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/utils/api_requests.py", line 54, in login
                                                       if common.make_call('login', credentials):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 142, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 80, in make_call
                                                       return make_addonsignals_call(callname, data)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 142, in make_addonsignals_call
                                                       _raise_for_error(result)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 154, in _raise_for_error
                                                       raise Exception(result['class'] + '\r\nError details:\r\n' + result.get('message', '--'))
                                                   Exception: KeyError
                                                   Error details:
                                                   'loco'

#### Other information
Started afternoon of 30 March 2021 MDT (Canada/Mountain)

**Comment by JackHall81** [comment]
Exact same error and log file contents here, just started out of the blue.
Running Kodi Matrix on Linux Mint

**Comment by Sil3ntKn1ght** [comment]
Having same problem not sure what rule i missed myself. 
I tested on Andriod phone fresh and My android box has Kodi set up issue is there and on my main system a windows 10 PC.
this issue is affecting all my devices with kodi.

Windows 10
and Android

Add-on issues started today no updates nothing has changes on windows 10, kodi installed from download from there Kodi page, have tried fresh install from scratch with kodi netflix issue still there.

The add-on encountered the following error
Exception: KeyError
Error Details:
'Loco'

Last log entries
2021-03-31 09:38:15.133 T:14704 INFO : XBApplicationEx: destroying...
2021-03-31 09:38:15.497 T:14704 INFO : AddOnLog: peripheral.joystick: Disabling joystick interface "directinput"
2021-03-31 09:38:15.497 T:14704 INFO : AddOnLog: peripheral.joystick: Disabling joystick interface "xinput"
2021-03-31 09:38:15.497 T:14704 INFO : ADDON: Dll Destroyed - Joystick Support
2021-03-31 09:38:15.498 T:14704 INFO : unload skin
2021-03-31 09:38:15.527 T:14704 INFO : Unloaded skin
2021-03-31 09:38:15.567 T:14704 INFO : unload sections
2021-03-31 09:38:15.576 T:14704 INFO : XBApplicationEx: application stopped!

**Comment by Sil3ntKn1ght** [comment]
my log doesn't show it, even though its happened so many times as iv tested today my logs just has the above, but same pop up and netflix add-ons dead so to speak

**Comment by notoco** [comment]
You need add full log, not only part with errors

**Comment by kmedcalf** [comment]
Sorry, but you will not get a full log.  The debug log contains reams of private information including userid's and passwords.  The best that you can hope for is a heavily sanitized log.

**Comment by kmedcalf** [comment]
Well that means that no log will be provided because there is no way to comply.  However, another issue has been posted with the same problem and that is a more complete log that contains no sensitive information.

I will not provide an unredacted log to anyone that contains sensitive information.  
I care not who you think you are.

**Comment by Sil3ntKn1ght** [comment]
Iv tried debug everything im on windows and my log doesn't show the reasons,
I can see in yours and the other persons the plugin.video.netflix/resources/lib/common/ipc.py Is the cause, upon researching that its a issue that pops up time to time when Netflix changes there substructure to how shows etc are organized.

hope its there is a fix soon, sad as there poor guy the made this did the ipc.py file 5 days ago to update it, but shows they are a active creator, I'm so very grateful for these add-ons. the people that make them are extremely talented

**Comment by fcr** [comment]
Had the same problem after MechanicalSoup plugin updated to 1.0.0 + matrix.1.
Connected?

**Comment by kmedcalf** [comment]
You have to turn on debugging in two places ... in Settings / System / Logging / Enable Debug Logging and also in the NetFlix AddOn Settings under Expert / Enable Debug logging.

Note that if you did what I did and re-install the NetFlix plugin then when you enter your userid and password it is recorded in the log.

**Comment by CastagnaIT** [comment]
> Had the same problem after MechanicalSoup plugin updated to 1.0.0 + matrix.1.
Connected?

this addon do not use it

for update follow issue #1121

**Comment by vteccorp** [comment]
Same error on my side... CoreELEC Matrix 19.1 RC1 on Beelink GT King...
