### ISSUE TITLE
install issue on Manjaro KDE 

### ISSUE THREAD

**Issue by jfabernathy** [CastagnaIT/plugin.video.netflix#1180]
#### Your Environment
- Netflix add-on version:  1,16,0+matrix.1
- Operating system version/name: Linux kde-manjaro 5.10.36-2-MANJARO 
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ *] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

I can open Netflix and get logged in via the authentication file but I get a failure to play with errors in inputstream.adaptive or widevie.

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found here:
https://paste.kodi.tv/pixacivuzo.kodi

#### Screenshots

2021-06-03 10:49:08.006 T:4241     INFO <general>: initializing python engine.
2021-06-03 10:49:08.244 T:4241    ERROR <general>: [script.module.inputstreamhelper] inputstream.adaptive is not installed.
2021-06-03 10:49:08.257 T:4241    ERROR <general>: EXCEPTION: Unknown addon id 'inputstream.adaptive'.
2021-06-03 10:49:08.257 T:4241    ERROR <general>: [script.module.inputstreamhelper] InputStream add-on not installed.
2021-06-03 10:49:08.273 T:4188     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2021-06-03 10:49:16.990 T:4241    ERROR <general>: [plugin.video.netflix (1)] Traceback (most recent call last):
                                                     File "/home/jim/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 29, in wrapper
                                                       func(*args, **kwargs)
                                                     File "/home/jim/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 252, in run
                                                       success = route(pathitems)
                                                     File "/home/jim/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 87, in lazy_login_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/jim/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 120, in route
                                                       play(videoid=pathitems[1:])
                                                     File "/home/jim/.kodi/addons/plugin.video.netflix/resources/lib/common/videoid.py", line 307, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/jim/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 47, in play
                                                       _play(videoid, False)
                                                     File "/home/jim/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 142, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/jim/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 65, in _play
                                                       list_item = get_inputstream_listitem(videoid)
                                                     File "/home/jim/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 107, in get_inputstream_listitem
                                                       raise Exception(common.get_local_string(30046))
                                                   Exception: There is a problem with InputStream Adaptive add-on or the Widevine library. May be missing or not enabled, the operation will be cancelled.

**Comment by jfabernathy** [comment]
I have added the log

**Comment by jakermx** [comment]
2021-06-03 14:13:54.196 T:7809    ERROR <general>: [script.module.inputstreamhelper] inputstream.adaptive is not installed.

**Comment by jfabernathy** [comment]
I saw that error, but inputstreamhelper is installed, but I see no way to install inputstream.adaptive. It's not listed as an option.  On Ubuntu I do not have to install this myself.

**Comment by jakermx** [comment]
Helper is another addon....try install from repository...all Repositories....and then go ImputStream

**Comment by jfabernathy** [comment]
I can't find anything called inputstream.adaptive.  When I use the search I only see inputstreamhelper.  This seams to be only on my Manjaro build system.

**Comment by jfabernathy** [comment]
okay, found it.  on Manjaro, A lof of the addons are in AUR.  so I had to install via:
yay -S kodi-addon-inputstream-adaptive-any

Thanks
