### ISSUE TITLE
license/pbl-1044: IssueLicensePolicyError

### ISSUE THREAD

**Issue by zz64** [CastagnaIT/plugin.video.netflix#1216]
#### Your Environment
- Netflix add-on version: 1.17.0
- Operating system version/name: GNU/Linux Gentoo 7.1 stable kernel 5.11.10-gentoo
- python-3.8.11
- kodi 19.1
- kodi-inputstream-adaptive-2.6.23
- Widevine: 4.10.2209.1
- Device model:  MSI board x86_64 Intel(R) Celeron(R) CPU J1800 

Used Operating system:
* [ ] Android
* [ ] iOS
* [ X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
after i upgrade to 1.17.0 for fixing email/pass login, i can't able to play any thing.
#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found here:
```2021-08-15 10:21:44.063 T:3268     INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.netflix/play/show/80002311/season/80223877/episode/80226447/?profile_guid=VEQ2QHJLFJAX7P7JWQPMWHI7Y4
2021-08-15 10:21:44.070 T:4617     INFO <general>: Creating InputStream
2021-08-15 10:21:44.071 T:4617     INFO <general>: AddOnLog: inputstream.adaptive: SetVideoResolution (1920 x 1080)
2021-08-15 10:21:47.375 T:4617     INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file. #Periods: 1, #Streams in first period: 22, Type: VOD, Download speed: 178767.6999 Bytes/s
2021-08-15 10:21:48.386 T:4620    ERROR <general>: [plugin.video.netflix (0)] Full MSL error information:
2021-08-15 10:21:48.387 T:4620    ERROR <general>: [plugin.video.netflix (0)] {"version": 2, "id": 16290157080989, "serverTime": 1629015708334, "from": "nq_cadmium_pbo_licenses@2.77.1/pbo-client@2.77.0", "result": [{"error": {"pboc": true, "code": "FAIL", "detail": "license/pbl-1044: IssueLicensePolicyError (E3-BQFRAAELECWFIE7H3Yhsgf0xZd0Mr0uBwmy3EZkduZdX5RZF9I0_e6eNqGVE-rZHFblvIHhd-YXaX_Of8FSKO9jfIUuhydkt0lrBz4EvZsQNBdjCe4M603EyzNIVwAlIGxtt0Czhf7pySnVrF1Z4wEFHB7423GtwVDj_ADlZr8cXWyWtadIYBQRMbTA36Y1BKchrtYcNNaOnfl5TczvlLNIiIANBFcuYRlTzwnQpJydTkm5JjMZ_v7FoxlC9jn6RrOPWwEcROSLJbbraI4utszNkhY5wsH_tWlgD9d_LjQn4_5bDyy05BrjL69Kz9JyVCCki9ZS6U-tQR6I2v-pMz8YVnYtzVtpYERKJ8g9BR0tN-ZEj4W7WrYpAjg8WvWEMkNd3iMwMxWtDaXtFPPJTbkvcyw3z9YXmbWax8Jupl88V8ltsvIykiBlPH1zAszWDgkf6Nd3R0SaXBk_NYQ_RGw3dtX4DcH4buwNdhY1itKq_QD_ieqcMD9puIcMWXWTRQ3lMsFgNlxhnM7dFidxTKyJCffl6ag9grRE65CAC7T60cWzudXKt7wcBBBvjmduUP6gukWqNu6752RoiqIib7gVh1s2pGj39ZOeMkZ8O_0iNyB4OFyY612ZDzg==) (nq_cadmium_pbo_licenses@2.77.1/pbo-client@2.77.0)", "display": "Ce titre n'est pas disponible en acc\u00e8s instantan\u00e9. Veuillez en s\u00e9lectionner un autre. - 1044", "alertTag": "", "errorDisplayMessage": "Ce titre n'est pas disponible en acc\u00e8s instantan\u00e9. Veuillez en s\u00e9lectionner un autre. - 1044", "errorActionId": 3, "nccpError": {}, "errorSubCode": 0, "errorReasonCode": 0, "errorNccpCode": 0, "errorExternalCode": 0, "bladeRunnerMessage": "license/pbl-1044: IssueLicensePolicyError (E3-BQFRAAELECWFIE7H3Yhsgf0xZd0Mr0uBwmy3EZkduZdX5RZF9I0_e6eNqGVE-rZHFblvIHhd-YXaX_Of8FSKO9jfIUuhydkt0lrBz4EvZsQNBdjCe4M603EyzNIVwAlIGxtt0Czhf7pySnVrF1Z4wEFHB7423GtwVDj_ADlZr8cXWyWtadIYBQRMbTA36Y1BKchrtYcNNaOnfl5TczvlLNIiIANBFcuYRlTzwnQpJydTkm5JjMZ_v7FoxlC9jn6RrOPWwEcROSLJbbraI4utszNkhY5wsH_tWlgD9d_LjQn4_5bDyy05BrjL69Kz9JyVCCki9ZS6U-tQR6I2v-pMz8YVnYtzVtpYERKJ8g9BR0tN-ZEj4W7WrYpAjg8WvWEMkNd3iMwMxWtDaXtFPPJTbkvcyw3z9YXmbWax8Jupl88V8ltsvIykiBlPH1zAszWDgkf6Nd3R0SaXBk_NYQ_RGw3dtX4DcH4buwNdhY1itKq_QD_ieqcMD9puIcMWXWTRQ3lMsFgNlxhnM7dFidxTKyJCffl6ag9grRE65CAC7T60cWzudXKt7wcBBBvjmduUP6gukWqNu6752RoiqIib7gVh1s2pGj39ZOeMkZ8O_0iNyB4OFyY612ZDzg==) (nq_cadmium_pbo_licenses@2.77.1/pbo-client@2.77.0)", "bladeRunnerCode": "1044"}, "errorParams": {"drmSessionId": "131E6B8BD6AFE1ED6D1C3632BE6EAF47"}}]}
2021-08-15 10:21:52.184 T:4620    ERROR <general>: ----------------------------------------
2021-08-15 10:21:52.184 T:4620    ERROR <general>: 
                                                   
2021-08-15 10:21:52.184 T:4620    ERROR <general>: Exception happened during processing of request from
2021-08-15 10:21:52.184 T:4620    ERROR <general>:  
2021-08-15 10:21:52.184 T:4620    ERROR <general>: ('127.0.0.1', 39200)
2021-08-15 10:21:52.185 T:4620    ERROR <general>: 
                                                   
2021-08-15 10:21:52.186 T:4620    ERROR <general>: Traceback (most recent call last):
                                                   
2021-08-15 10:21:52.186 T:4620    ERROR <general>: 
2021-08-15 10:21:52.187 T:4620    ERROR <general>:   File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
                                                       self.finish_request(request, client_address)
                                                   
2021-08-15 10:21:52.187 T:4620    ERROR <general>: 
2021-08-15 10:21:52.187 T:4620    ERROR <general>:   File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
                                                       self.RequestHandlerClass(request, client_address, self)
                                                   
2021-08-15 10:21:52.187 T:4620    ERROR <general>: 
2021-08-15 10:21:52.187 T:4620    ERROR <general>:   File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
                                                       self.handle()
                                                   
2021-08-15 10:21:52.187 T:4620    ERROR <general>: 
2021-08-15 10:21:52.187 T:4620    ERROR <general>:   File "/usr/lib/python3.8/http/server.py", line 427, in handle
                                                       self.handle_one_request()
                                                   
2021-08-15 10:21:52.187 T:4620    ERROR <general>: 
2021-08-15 10:21:52.187 T:4620    ERROR <general>:   File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
                                                       method()
                                                   
2021-08-15 10:21:52.187 T:4620    ERROR <general>: 
2021-08-15 10:21:52.187 T:4620    ERROR <general>:   File "/home/moi/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py", line 48, in do_POST
                                                       handle_msl_request(self, func_name, data)
                                                   
2021-08-15 10:21:52.187 T:4620    ERROR <general>: 
2021-08-15 10:21:52.187 T:4620    ERROR <general>:   File "/home/moi/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py", line 80, in handle_msl_request
                                                       license_data = server.server.netflix_session.msl_handler.get_license(data)
                                                   
2021-08-15 10:21:52.187 T:4620    ERROR <general>: 
2021-08-15 10:21:52.187 T:4620    ERROR <general>:   File "/home/moi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/msl_utils.py", line 55, in error_catching_wrapper
                                                       return func(*args, **kwargs)
                                                   
2021-08-15 10:21:52.187 T:4620    ERROR <general>: 
2021-08-15 10:21:52.188 T:4620    ERROR <general>:   File "/home/moi/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 142, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                   
2021-08-15 10:21:52.188 T:4620    ERROR <general>: 
2021-08-15 10:21:52.188 T:4620    ERROR <general>:   File "/home/moi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/msl_handler.py", line 230, in get_license
                                                       response = self.msl_requests.chunked_request(endpoint_url,
                                                   
2021-08-15 10:21:52.188 T:4620    ERROR <general>: 
2021-08-15 10:21:52.188 T:4620    ERROR <general>:   File "/home/moi/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 142, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                   
2021-08-15 10:21:52.188 T:4620    ERROR <general>: 
2021-08-15 10:21:52.188 T:4620    ERROR <general>:   File "/home/moi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/msl_requests.py", line 165, in chunked_request
                                                       chunked_response = self._process_chunked_response(
                                                   
2021-08-15 10:21:52.188 T:4620    ERROR <general>: 
2021-08-15 10:21:52.188 T:4620    ERROR <general>:   File "/home/moi/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 142, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                   
2021-08-15 10:21:52.188 T:4620    ERROR <general>: 
2021-08-15 10:21:52.188 T:4620    ERROR <general>:   File "/home/moi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/msl_requests.py", line 220, in _process_chunked_response
                                                       return _raise_if_error(decrypted_response)
                                                   
2021-08-15 10:21:52.188 T:4620    ERROR <general>: 
2021-08-15 10:21:52.188 T:4620    ERROR <general>:   File "/home/moi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/msl/msl_requests.py", line 249, in _raise_if_error
                                                       raise MSLError(err_message, err_number)
                                                   
2021-08-15 10:21:52.188 T:4620    ERROR <general>: 
2021-08-15 10:21:52.188 T:4620    ERROR <general>: resources.lib.common.exceptions.MSLError: Ce titre n'est pas disponible en accès instantané. Veuillez en sélectionner un autre. - 1044
                                                   
2021-08-15 10:21:52.188 T:4620    ERROR <general>: 
2021-08-15 10:21:52.188 T:4620    ERROR <general>: ----------------------------------------
2021-08-15 10:21:52.188 T:4620    ERROR <general>: 
                                                   
2021-08-15 10:21:52.189 T:4617    ERROR <general>: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
2021-08-15 10:21:52.189 T:4617    ERROR <general>: CCurlFile::Open failed with code 0 for http://127.0.0.1:51275/msl/get_license?videoid=80226447:
                                                   
2021-08-15 10:21:52.189 T:4617    ERROR <general>: AddOnLog: inputstream.adaptive: License server returned failure
2021-08-15 10:21:52.189 T:4617    ERROR <general>: AddOnLog: inputstream.adaptive: License update not successful (no keys)
2021-08-15 10:21:52.240 T:4617    ERROR <general>: AddOnLog: inputstream.adaptive: Initialize failed (SingleSampleDecrypter)
2021-08-15 10:21:52.243 T:4617    ERROR <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/play/show/80002311/season/80223877/episode/80226447/?profile_guid=VEQ2QHJLFJAX7P7JWQPMWHI7Y4]
2021-08-15 10:21:52.244 T:4617     INFO <general>: CVideoPlayer::OnExit()
2021-08-15 10:21:52.248 T:4617     INFO <general>: ADDON: Dll Destroyed - InputStream Adaptive
2021-08-15 10:21:52.263 T:3268     INFO <general>: CVideoPlayer::CloseFile()
2021-08-15 10:21:52.276 T:3268     INFO <general>: VideoPlayer: waiting for threads to exit
2021-08-15 10:21:52.277 T:3268     INFO <general>: VideoPlayer: finished waiting
2021-08-15 10:21:54.331 T:4510     INFO <general>: initializing python engine.
2021-08-15 10:21:54.673 T:4510     INFO <general>: CPythonInvoker(16, /home/moi/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
2021-08-15 10:21:55.439 T:4510     INFO <general>: initializing python engine.
2021-08-15 10:21:55.819 T:4510     INFO <general>: CPythonInvoker(16, /home/moi/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
2021-08-15 10:21:56.524 T:4510     INFO <general>: initializing python engine.
2021-08-15 10:21:56.880 T:4510     INFO <general>: CPythonInvoker(16, /home/moi/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
2021-08-15 10:21:57.095 T:3268  WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval (1)
2021-08-15 10:23:12.314 T:3268  WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval (1)
2021-08-15 10:23:35.486 T:3268     INFO <general>: Skipped 6 duplicate messages..
2021-08-15 10:23:35.486 T:3268     INFO <general>: NFS is idle. Closing the remaining connections.
```
-->

**Comment by CastagnaIT** [comment]
the license error has no relations to the login changes
please go to
Expert settings -> ESN/Widevine -> press "Reset"

try playback

if still not works:
1)

Expert settings -> ESN/Widevine -> press "Save system info"
attach here the file


2)

follow the guthub readme to read on how to get debug log, and then provide a FULL debug log, the provided one is not a debug log
and please follow the rules: _here is not accepted shrinked/edited log or attach the log text in the Issue thread_

**Comment by zz64** [comment]
> Expert settings -> ESN/Widevine -> press "Reset"

is working. thanks.
