### ISSUE TITLE
TypeError on login

### ISSUE THREAD

**Issue by 404cn** [CastagnaIT/plugin.video.netflix#1263]
#### Your Environment
- Netflix add-on version: 
1.0.0 https://github.com/castagnait/repository.castagnait/raw/matrix/repository.castagnait-1.0.0.zip
- Operating system version/name: 
 LibreElec 10.0.0 on RPI4.arm

### Describe the bug
Enter mail and password and got an error.

Here is the log from kodi.log
```
2021-11-07 15:05:35.534 T:2599    ERROR <general>: [plugin.video.netflix (1)] Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 29, in wrapper
                                                       func(*args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 245, in run
                                                       success = route(pathitems)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 85, in lazy_login_wrapper
                                                       if _check_valid_credentials():
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 70, in _check_valid_credentials
                                                       if not login():
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/api_requests.py", line 36, in login
                                                       if common.make_call('login', credentials):
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 94, in make_call
                                                       return make_http_call(endpoint, func_name, data)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 115, in make_http_call
                                                       _data = pickle.loads(received_data)
                                                   TypeError: __init__() missing 2 required keyword-only arguments: 'request' and 'response'
```

**Comment by CastagnaIT** [comment]
You have not fullfill the bugreport as requested in this Github
please edit it by fullfill the report by following the template or this Issue will be closed next days
