### ISSUE TITLE
Error to save profiles on sql - UnicodeEncodeError: 'utf-8'

### ISSUE THREAD

**Issue by tecnomanu** [CastagnaIT/plugin.video.netflix#1347]
### Netflix add-on version

1.0.0

### Operative systems used

Android, Mac OSX

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Hi, i installed the plugin and have problems to login with my account.
Then i try to get log errorr, then recieved this:

> 2022-05-23 10:39:54.341 T:76458   ERROR <general>: [plugin.video.netflix (0)] Traceback (most recent call last):
                                                     File "/Users/manuelbruna/Library/Application Support/Kodi/addons/plugin.video.netflix/resources/lib/utils/website.py", line 147, in parse_profiles
                                                       G.LOCAL_DB.insert_profile_configs(summary, guid)
                                                     File "/Users/manuelbruna/Library/Application Support/Kodi/addons/plugin.video.netflix/resources/lib/database/db_base_sqlite.py", line 50, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/Users/manuelbruna/Library/Application Support/Kodi/addons/plugin.video.netflix/resources/lib/database/db_local.py", line 94, in insert_profile_configs
                                                       self._executemany_non_query(insert_query, records_values, cur)
                                                     File "/Users/manuelbruna/Library/Application Support/Kodi/addons/plugin.video.netflix/resources/lib/database/db_base_sqlite.py", line 106, in _executemany_non_query
                                                       cursor.executemany(query, params)
                                                   UnicodeEncodeError: 'utf-8' codec can't encode characters in position 4-5: surrogates not allowed

Trying to search the problem, i guess know is about the nickname used by my child:
'avatarName': 'Elo \ud83d\udc9c',

Because she used an icon heart (❤️ ) for his nickname and the encder cant resolve i supposed.

I hope this log help you to resolve this in the next update and if you want, i can test this after that.

See you!

### Steps to reproduce the behavior

1. Go to profiles in Netflix account.
2. Change the name
3. Insert a icon like a heart (using android keybord i gues).
4.  Try login with the addon

### Debug log - mandatory

https://paste.kodi.tv/azefasecey.kodi

### Possible fix

Check when you convert the text and sanitize the values.

**Comment by CastagnaIT** [comment]
avatarName field is not the profile name is the coded name of the profile image
can you take a screenshot of the profile image used with that profile?
so maybe i can reproduce locally

**Comment by CastagnaIT** [comment]
closed due to not found a way to reproduce it
