### ISSUE TITLE
NFAuthentication Key for Linux/MacOS (Version 1.1.4) ERROR

### ISSUE THREAD

**Issue by anroswart** [CastagnaIT/plugin.video.netflix#1374]
### Netflix add-on version

1.18.7+matrix.1

### Operative systems used

Mac OSX

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

I am unable to run the Authentication Key script:
```
NFAuthentication Key for Linux/MacOS (Version 1.1.4)

Disclaimer:
This script and source code available on GitHub are provided "as is" without warranty of any kind, either express or implied. Use at your own risk. The use of the software is done at your own discretion and risk with the agreement that you will be solely responsible for any damage resulting from such activities and you are solely responsible for adequate data protection.

Press "ENTER" key to accept the disclaimer and start, or "CTRL+C" to cancel
Browser startup... (/Applications/Google Chrome.app/Contents/MacOS/Google Chrome) please wait
Establish connection with the browser... please wait
Opening login webpage... please wait
Please login in to website now ...waiting for you to finish...
An error is occurred:
Connection to remote host was lost.
Traceback (most recent call last):
  File "/Users/anro/Desktop/osmc/NFAuthenticationKey/NFAuthenticationKey.py", line 63, in __init__
    self.operations()
  File "/Users/anro/Desktop/osmc/NFAuthenticationKey/NFAuthenticationKey.py", line 92, in operations
    if not self.wait_user_logged():
  File "/Users/anro/Desktop/osmc/NFAuthenticationKey/NFAuthenticationKey.py", line 162, in wait_user_logged
    history_data = self.ws_request('Page.getNavigationHistory')
  File "/Users/anro/Desktop/osmc/NFAuthenticationKey/NFAuthenticationKey.py", line 186, in ws_request
    message = self._ws.recv()
  File "/opt/homebrew/lib/python3.9/site-packages/websocket/_core.py", line 357, in recv
    opcode, data = self.recv_data()
  File "/opt/homebrew/lib/python3.9/site-packages/websocket/_core.py", line 380, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/opt/homebrew/lib/python3.9/site-packages/websocket/_core.py", line 401, in recv_data_frame
    frame = self.recv_frame()
  File "/opt/homebrew/lib/python3.9/site-packages/websocket/_core.py", line 440, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/opt/homebrew/lib/python3.9/site-packages/websocket/_abnf.py", line 338, in recv_frame
    self.recv_header()
  File "/opt/homebrew/lib/python3.9/site-packages/websocket/_abnf.py", line 294, in recv_header
    header = self.recv_strict(2)
  File "/opt/homebrew/lib/python3.9/site-packages/websocket/_abnf.py", line 373, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/opt/homebrew/lib/python3.9/site-packages/websocket/_core.py", line 524, in _recv
    return recv(self.sock, bufsize)
  File "/opt/homebrew/lib/python3.9/site-packages/websocket/_socket.py", line 122, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.
```

### Steps to reproduce the behavior

1. Download NFAuthenticationKey.zip
2. Unzip
3. run `python NFAuthenticationKey.py`

### Debug log - mandatory

https://github.com/CastagnaIT/plugin.video.netflix/wiki/Login-with-Authentication-key

**Comment by CastagnaIT** [comment]
Closed due to not possible investigate from my part and no users helped
