### ISSUE TITLE
Crypto Bug after Updating to Latest Debian Bullseye

### ISSUE THREAD

**Issue by WammKD** [CastagnaIT/plugin.video.netflix#1440]
### Netflix add-on version

1.18.10+matrix.1

### Operative systems used

OSMC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

In relation to #1416, – after I updated my system to the latest Bullseye packages – I found that the Netflix plugin was reporting that it couldn't find module Crypto.

I went back to the install instructions to try and rerun them, in case anything had been removed, and, like @dantahoua, found that `python3-crypto` was not available. I also find that `python3-cryptodome` is not, either. I tried installing `python3-cryptography` (I'm not sure if it's helpful or relevant but I figured, at worst, it'd have no effect).

I found that `build-essential`, `python-pip`, and `libnss3` were reported as already installed which didn't surprise me.

Installing `setuptools` and `wheel` had similar results.

`pycryptodomex`, however, did need to get installed which I found weird as I already had the plugin installed, previously.

Nonetheless, doing so resulted in the background process for the Netflix plugin starting, like it normally does.

But clicking on the plugin results in a consistent error.

Looking at the logs, I got

```
2022-10-02 17:16:13.030 T:3107    ERROR <general>: GetDirectory - Error getting -
2022-10-02 17:16:13.076 T:3110     INFO <general>: initializing python engine.
2022-10-02 17:16:14.279 T:3110     INFO <general>: [plugin.video.netflix (1)] The debug logging is set as DISABLED
2022-10-02 17:16:16.942 T:2971    ERROR <general>: [plugin.video.netflix (0)] IPC callback raised exception: 404 Client Error: Not Found for url: https://www.netflix.com/api/shakti/vbb9fbeef/pathEvaluator?drmSystem=widevine&withSize=false&materialize=false&routeAPIRequestsThroughFTL=false&isVolatileBillboardsEnabled=true&isTop10Supported=true&categoryCraversEnabled=false&original_path=%2Fshakti%2Fvbb9fbeef%2FpathEvaluator
                                                   For more information check: https://httpstatuses.com/404
2022-10-02 17:16:16.960 T:2971    ERROR <general>: [plugin.video.netflix (0)] Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/cache_management.py", line 163, in get
                                                       cache_entry = self._get_cache_bucket(bucket['name'])[identifier]
                                                   KeyError: 'XQOIDDVNQNEXFL65VEE54Y5WGI_loco_list'
                                                   
                                                   The above exception was the direct cause of the following exception:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/cache_utils.py", line 70, in wrapper
                                                       return G.CACHE.get(_bucket, identifier)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/cache_management.py", line 171, in get
                                                       raise CacheMiss from exc
                                                   resources.lib.common.exceptions.CacheMiss
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 172, in return_call
                                                       result = _call(self._func, _data)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 188, in _call
                                                       return func()
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/directorybuilder/dir_builder.py", line 48, in get_mainmenu
                                                       loco_list = self.req_loco_list_root()
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/cache_utils.py", line 72, in wrapper
                                                       output = func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/directorybuilder/dir_path_requests.py", line 65, in req_loco_list_root
                                                       path_response = self.nfsession.path_request(**call_args)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/path_requests.py", line 32, in path_request
                                                       response = self.post_safe(
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py", line 77, in post_safe
                                                       return self.post(endpoint, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/http_requests.py", line 41, in post
                                                       return self._request_call(
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/http_requests.py", line 48, in _request_call
                                                       return self._request(method, endpoint, None, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/http_requests.py", line 103, in _request
                                                       return self._request(method, endpoint, True, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/http_requests.py", line 106, in _request
                                                       response.raise_for_status()
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/packages/httpx/_models.py", line 1402, in raise_for_status
                                                       raise HTTPStatusError(message, request=request, response=self)
                                                   httpx.HTTPStatusError: 404 Client Error: Not Found for url: https://www.netflix.com/api/shakti/vbb9fbeef/pathEvaluator?drmSystem=widevine&withSize=false&materialize=false&routeAPIRequestsThroughFTL=false&isVolatileBillboardsEnabled=true&isTop10Supported=true&categoryCraversEnabled=false&original_path=%2Fshakti%2Fvbb9fbeef%2FpathEvaluator
                                                   For more information check: https://httpstatuses.com/404
                                                   
2022-10-02 17:16:19.232 T:3110    ERROR <general>: [plugin.video.netflix (1)] Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 29, in wrapper
                                                       func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 245, in run
                                                       success = route(pathitems)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 87, in lazy_login_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 127, in route
                                                       _execute(nav_handler, pathitems[1:], G.REQUEST_PARAMS, root_handler)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 156, in _execute
                                                       executor(pathitems=pathitems)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_utils.py", line 28, in set_custom_viewmode
                                                       override_content_type = func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 102, in home
                                                       dir_items, extra_data = common.make_call('get_mainmenu')  # pylint: disable=unused-variable
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 95, in make_call
                                                       return make_addonsignals_call(func_name, data)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 143, in make_addonsignals_call
                                                       _result = pickle.loads(b64decode(result))
                                                   TypeError: __init__() missing 2 required keyword-only arguments: 'request' and 'response'
                                                   
2022-10-02 17:16:19.236 T:2886     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
```

I tried uninstalling `python3-cryptography`, just to see what would happen, and got this error:

```
2022-10-02 17:17:31.754 T:2945     INFO <general>: CActiveAESink::OpenSink - initialize sink
2022-10-02 17:17:31.754 T:2945     INFO <general>: CAESinkALSA::Initialize - Requested layout: FL, FR
2022-10-02 17:17:31.755 T:2945     INFO <general>: CAESinkALSA::Initialize - set digital_codec 0
2022-10-02 17:17:31.756 T:2945     INFO <general>: CAESinkALSA::Initialize - Attempting to open device "default"
2022-10-02 17:17:31.766 T:2945     INFO <general>: CAESinkALSA::Initialize - Opened device "default"
2022-10-02 17:17:31.767 T:2945     INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2022-10-02 17:17:31.768 T:2945     INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE4
2022-10-02 17:17:31.770 T:2945     INFO <general>: CAESinkALSA::Initialize - speaker layout 0
2022-10-02 17:17:31.991 T:3169     INFO <general>: initializing python engine.
2022-10-02 17:17:32.208 T:3154     INFO <general>: Python interpreter stopped
2022-10-02 17:17:33.034 T:2886    ERROR <general>: Control 50 in window 10025 has been asked to focus, but it can't
2022-10-02 17:17:33.069 T:3173     INFO <general>: initializing python engine.
2022-10-02 17:17:35.863 T:3173     INFO <general>: [plugin.video.netflix (3)] The debug logging is set as DISABLED
2022-10-02 17:17:36.454 T:3169     INFO <general>: CPythonInvoker(12, /home/osmc/.kodi/addons/script.skinshortcuts/resources/lib/entry_point.py): script successfully run
2022-10-02 17:17:36.549 T:3169     INFO <general>: Python interpreter stopped
2022-10-02 17:17:38.365 T:2971    ERROR <general>: [plugin.video.netflix (0)] IPC callback raised exception: 404 Client Error: Not Found for url: https://www.netflix.com/api/shakti/vbb9fbeef/pathEvaluator?drmSystem=widevine&withSize=false&materialize=false&routeAPIRequestsThroughFTL=false&isVolatileBillboardsEnabled=true&isTop10Supported=true&categoryCraversEnabled=false&original_path=%2Fshakti%2Fvbb9fbeef%2FpathEvaluator
                                                   For more information check: https://httpstatuses.com/404
2022-10-02 17:17:38.369 T:2971    ERROR <general>: [plugin.video.netflix (0)] Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/cache_management.py", line 163, in get
                                                       cache_entry = self._get_cache_bucket(bucket['name'])[identifier]
                                                   KeyError: 'XQOIDDVNQNEXFL65VEE54Y5WGI_loco_list'
                                                   
                                                   The above exception was the direct cause of the following exception:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/cache_utils.py", line 70, in wrapper
                                                       return G.CACHE.get(_bucket, identifier)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/cache_management.py", line 171, in get
                                                       raise CacheMiss from exc
                                                   resources.lib.common.exceptions.CacheMiss
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 172, in return_call
                                                       result = _call(self._func, _data)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 188, in _call
                                                       return func()
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/directorybuilder/dir_builder.py", line 48, in get_mainmenu
                                                       loco_list = self.req_loco_list_root()
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/cache_utils.py", line 72, in wrapper
                                                       output = func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/directorybuilder/dir_path_requests.py", line 65, in req_loco_list_root
                                                       path_response = self.nfsession.path_request(**call_args)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/path_requests.py", line 32, in path_request
                                                       response = self.post_safe(
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py", line 77, in post_safe
                                                       return self.post(endpoint, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/http_requests.py", line 41, in post
                                                       return self._request_call(
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/http_requests.py", line 48, in _request_call
                                                       return self._request(method, endpoint, None, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/http_requests.py", line 103, in _request
                                                       return self._request(method, endpoint, True, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/http_requests.py", line 106, in _request
                                                       response.raise_for_status()
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/packages/httpx/_models.py", line 1402, in raise_for_status
                                                       raise HTTPStatusError(message, request=request, response=self)
                                                   httpx.HTTPStatusError: 404 Client Error: Not Found for url: https://www.netflix.com/api/shakti/vbb9fbeef/pathEvaluator?drmSystem=widevine&withSize=false&materialize=false&routeAPIRequestsThroughFTL=false&isVolatileBillboardsEnabled=true&isTop10Supported=true&categoryCraversEnabled=false&original_path=%2Fshakti%2Fvbb9fbeef%2FpathEvaluator
                                                   For more information check: https://httpstatuses.com/404
                                                   
2022-10-02 17:17:40.755 T:3173    ERROR <general>: [plugin.video.netflix (3)] Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 29, in wrapper
                                                       func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 245, in run
                                                       success = route(pathitems)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 87, in lazy_login_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 127, in route
                                                       _execute(nav_handler, pathitems[1:], G.REQUEST_PARAMS, root_handler)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 156, in _execute
                                                       executor(pathitems=pathitems)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_utils.py", line 28, in set_custom_viewmode
                                                       override_content_type = func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 102, in home
                                                       dir_items, extra_data = common.make_call('get_mainmenu')  # pylint: disable=unused-variable
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 95, in make_call
                                                       return make_addonsignals_call(func_name, data)
                                                     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 143, in make_addonsignals_call
                                                       _result = pickle.loads(b64decode(result))
                                                   TypeError: __init__() missing 2 required keyword-only arguments: 'request' and 'response'
```

### Steps to reproduce the behavior

1. Install updates via OSMC's usual updates system?
2. Try to run Netflix plugin (will encounter "no Crypto module" error)
3. Try to rerun installation instructions (won't be able to install `python3-crypto` or `python3-cryptodome`)
4. Try to run Netflix plugin, again

### Debug log - mandatory

https://paste.kodi.tv/ezoxofuhof.kodi

**Comment by CastagnaIT** [comment]
the error shown not concern crypto library, see #1425

**Comment by WammKD** [comment]
Gotcha; thanks for pointing it out. I'll get this closed.
