### ISSUE TITLE
recurring SqLiteError

### ISSUE THREAD

**Issue by krzysztofwinnik** [CastagnaIT/plugin.video.netflix#1534]
### Netflix add-on version

1.20.3+matrix.1

### Operative systems used

CoreELEC

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Hi there, 
I get frequent and recurrent SqLiteErrors thrown by Netflix addons for - let's say - last two or three weeks. 
In spite of the error, everything seems to work just fine. The only inconvenience is that each time the error is thrown an alert window is displayed. 

Please find below an extract form my debug log. Hope it helps.

```
2023-01-05 16:03:47.873 T:13492   error <general>: [plugin.video.netflix (0)] SQLite error UNIQUE constraint failed: menu_data.ContextId:
2023-01-05 16:03:47.873 T:13492   error <general>: [plugin.video.netflix (0)] IPC callback raised exception: 
2023-01-05 16:03:47.941 T:13492   error <general>: [plugin.video.netflix (0)] Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/database/db_base_sqlite.py", line 124, in _execute_non_query
                                                       cursor.execute(query, params)
                                                   sqlite3.IntegrityError: UNIQUE constraint failed: menu_data.ContextId
                                                   
                                                   The above exception was the direct cause of the following exception:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py", line 105, in handle_request
                                                       ret_data = _call_func(func, pickle.loads(data))
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py", line 161, in _call_func
                                                       return func(**data)
                                                              ^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/directorybuilder/dir_builder.py", line 145, in get_genres
                                                       return build_loco_listing(loco_list, menu_data, force_use_videolist_id)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/directorybuilder/dir_builder_items.py", line 218, in build_loco_listing
                                                       G.LOCAL_DB.set_value(list_id, sub_menu_data, TABLE_MENU_DATA)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/database/db_base_sqlite.py", line 53, in wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/database/db_base_sqlite.py", line 223, in set_value
                                                       self._execute_non_query(insert_query, (key, value))
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/database/db_base_sqlite.py", line 129, in _execute_non_query
                                                       raise DBSQLiteError from exc
                                                   resources.lib.common.exceptions.DBSQLiteError
                                                   
```

### Steps to reproduce the behavior

I can see no pattern related to this bug. It seem to happen even if not using Netlix. Probably related to some service workers running in background.

### Debug log - mandatory

https://paste.kodi.tv/ofoquneyuh.kodi

**Comment by CastagnaIT** [comment]
from the log seem you have 3 skin widgets and all them try to access to the addon at same time 

```
2023-01-05 16:03:41.841 T:30075    info <general>: plugin.program.autowidget: Added to queue: 78996fb3081e85f5eca55596105db06e87813a32 plugin://plugin.video.netflix/directory/genres/movies/34399/ None
2023-01-05 16:03:41.844 T:30075    info <general>: plugin.program.autowidget: Added to queue: 82755bfe59a5b99c4c1aa038c2c5d246fc9e3b1d plugin://plugin.video.netflix/directory/category_list/newAndPopular/ None
2023-01-05 16:03:41.848 T:30075    info <general>: plugin.program.autowidget: Added to queue: 0a488e43c6f1e8685008002d1796a33d80349716 plugin://plugin.video.netflix/directory/genres/tvshows/83/ None
2023-01-05 16:03:43.020 T:13384    info <general>: [plugin.video.netflix (91)] The debug logging is set as DISABLED
2023-01-05 16:03:43.034 T:13382    info <general>: [plugin.video.netflix (90)] The debug logging is set as DISABLED
2023-01-05 16:03:43.070 T:13388    info <general>: [plugin.video.netflix (92)] The debug logging is set as DISABLED
```
this is more likely the problem, so widgets has caused a kind of database concurrency
widgets do not have any kind of access control are executed without any limit
this is the reason why this addon dont support widgets there are no way to have a control over them

however can you try update with this test?
[plugin.video.netflix_1.20.3+matrix.1_20230110_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/10380521/plugin.video.netflix_1.20.3%2Bmatrix.1_20230110_t1.zip)
is possible that this change perhaps may improve a bit the situation

**Comment by CastagnaIT** [comment]
Please before try test update with this "t2" test:
[plugin.video.netflix_1.20.3+matrix.1_20230110_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/10380709/plugin.video.netflix_1.20.3%2Bmatrix.1_20230110_t2.zip)

**Comment by krzysztofwinnik** [comment]
@CastagnaIT Many thanks for your reply - I'll give it a try and get back to you with feedback asap.

**Comment by CastagnaIT** [comment]
there is no way to hide error messages, because there is no way to identify if the call come from a widget
otherwise you hide all errors and you are not able to know when the addon works correctly or not

the screenshot is not useful, you have to share the new log so i can try see if there is other things to check,
but you have to remember also to enable the debug as described in github Readme

**Comment by krzysztofwinnik** [comment]
Yeah, sure. I see your point. I will enable debug mode and wait for an error to send you my log.
Many thanks anyway!

**Comment by krzysztofwinnik** [comment]
Ok, today is the 6th day after installing t2 version and I am happy to confirm I haven't experienced any errors or crashes except for the single timeout error I described earlier (which I cannot reproduce and is most likely not related). That said, I believe it is safe to say your t2 version resolved my problem. Are you going to merge that version with the main branch?

Many thanks for your support @CastagnaIT.

**Comment by CastagnaIT** [comment]
thanks for feedback
yes you can already update with last version
