### ISSUE TITLE
netflix returned the following errors:

### ISSUE THREAD

**Issue by Fixafazatron** [CastagnaIT/plugin.video.netflix#1553]
### Netflix add-on version

Netflix add-on

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Ваш аккаунт не может использоваться на этом устройстве

### Debug log - mandatory

я не знаю как это сделать

### Screenshots

![photo_2023-02-08_19-30-53](https://user-images.githubusercontent.com/52254583/217607803-120ab819-3109-4ffc-b0af-2e3fa85a2817.jpg)
![photo_2023-02-08_19-30-37](https://user-images.githubusercontent.com/52254583/217607809-70d61318-fabe-4ff9-aedd-2eb54dbdb2e0.jpg)
![photo_2023-02-08_19-30-43](https://user-images.githubusercontent.com/52254583/217607811-2620f227-3c56-498c-aa34-48f9ab6dacb6.jpg)

**Comment by CastagnaIT** [comment]
only english language is accepted
please amend your issue description

sound like your device is not certified,
make sure that your device is certified see [How to check if an android device passes Netflix certification](https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#how-to-check-if-an-android-device-passes-netflix-certification)
if so, is needed a full debug log as well explained on main page Readme

**Comment by TheChatty** [comment]
I've got the [BenQ S01](https://www.benq.eu/de-de/projector/accessory/qs01-remote-dongle-bundle.html). Unfortunately this stick is not certified. Is there anything I can do about it?

**Comment by CastagnaIT** [comment]
@TheChatty the only thing you can try is to install Netflix app by sideloading it
if starts and if can play videos, then
1) go to app settings to check how the first part of the ESN is composed
2) go to addon expert setting to check if the first part of addon esn is the same, if not so, edit addon esn to match app esn, do not copy/edit the last part of about ~30 chars
3) try play a video

if this not works, nothing else can be done

**Comment by TheChatty** [comment]
Since my stick is not certified I could not download Netflix from Playstore but from Aptoide (it's 6.26.1 build 15). This app reports an ESN like "NFANDROID1-PRV-B-L3-INSPUQS01-1234-56789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF01234".
Addon ESN is like "NFANDROID2-PRV-0-INSPUQS01-12345-6789ABCDEF....". How should the Addon ESN start now?

**Comment by CastagnaIT** [comment]
in this case for addon become
`NFANDROID1-PRV-B-L3-INSPUQS01-1234-6789ABCDEF....`
so by keeping the addon last part `-6789ABCDEF....`

**Comment by TheChatty** [comment]
I replaced the string start as you said but still get an error only. The log says:
```
 info <general>: [plugin.video.netflix (0)] Requesting manifest (version default) for ...
debug <general>: [plugin.video.netflix (0)] Stored MSL MasterToken is bound to a different ESN, a new key handshake will be performed
 info <general>: [plugin.video.netflix (0)] Performing key handshake with ESN: NFANDROID1-PRV-B-L3-INSPUQS01-1234-6789ABCDEF...
debug <general>: [plugin.video.netflix (0)] Widevine CryptoSession getKeyRequest successful. Size: 2141
debug <general>: [plugin.video.netflix (0)] Executing POST request to https://www.netflix.com/msl/playapi/cadmium/licensedmanifest
debug <general>: [plugin.video.netflix (0)] Request took 0.20972041599998192s
debug <general>: [plugin.video.netflix (0)] Request returned response with status 200
error <general>: [plugin.video.netflix (0)] Full MSL error information:
error <general>: [plugin.video.netflix (0)] {"signature": "Q+saRY...
...
```

The on-screen error message says: "MSLError: Request failed validation during key exchange".

**Comment by CastagnaIT** [comment]
in this case you cant use that device at least not with this addon

**Comment by TheChatty** [comment]
That's too bad. Even more so since the (Aptoid) app is able to play contents. Thanks for your assistance.

**Comment by CastagnaIT** [comment]
if you are able to find a solution to the problem,
PR to implement improvements are welcome

**Comment by petakpa1** [comment]
Can I reopen this topic? I have the same or very similar issue. After I start to view a movie in the addon, a popup window comes up:
_Netflix stopped because of below error:
MSLerror: This movie is not available for instant view. Please choose another movie : -1044.
The details of error was saved to Kodi log...._

(The error message is shown in Hungarian, I were unable to switch it to English and insert a screenshot here, thus I transleted the error msg to english on my own. Translation is maybe not perfectly the same what would be reported on an English Kodi, but the translation is basically correct).

**Despite above pop up window, the movie is started to play but after cc.a 2 mins it video stucks to play further only the audio continues to play.**

The same error happens with several movie.

I copy below that part of the log what I think relevant:

2023-06-02 16:31:16.903 T:7200     info <general>: [plugin.video.netflix (1)] The debug logging is set as DISABLED
2023-06-02 16:32:00.710 T:7200  warning <general>: [script.module.inputstreamhelper] Widevine update check was made on 2023-05-16 14:48
2023-06-02 16:32:00.781 T:6012     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.netflix/play/movie/70142823/?profile_guid=MJIAJHDAWZEGDFPW2QNIPTZAFQ
2023-06-02 16:32:00.784 T:7720     info <general>: Creating InputStream
2023-06-02 16:32:01.082 T:7720  warning <general>: AddOnLog: inputstream.adaptive: Set headers to the manifest by using "inputstream.adaptive.stream_headers" property is a deprecated behaviour that will be removed in future.
                                                   To set headers to the manifest, use "inputstream.adaptive.manifest_headers" property.
2023-06-02 16:32:01.092 T:7720     info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1280x749, max allowed: 1280x749, Adjust refresh rate: 0
2023-06-02 16:32:01.093 T:7720    error <general>: XFILE::CDirectory::GetDirectory - Error getting C:\Program Files (x86)\Kodi\addons\inputstream.adaptive\
2023-06-02 16:32:03.624 T:7720     info <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file (Periods: 1, Streams in first period: 15, Type: VOD)
2023-06-02 16:32:03.866 T:6832    error <general>: [plugin.video.netflix (0)] Full MSL error information:
2023-06-02 16:32:03.867 T:6832    error <general>: [plugin.video.netflix (0)] {"version": 2, "id": 16857163236396, "serverTime": 1685716322103, "from": "nq_cadmium_pbo_licenses@2.133.0/pbo-client@2.133.0", "result": [{"error": {"pboc": true, "code": "FAIL", "detail": "license/pbl-1044: IssueLicensePolicyError (E3-BQFRAAELED1pnNOD12w9u7xJRjnxEjaBuUkjahZNjFaVryY5IdCksUSY1RxBgVQsqC3LTQ5_dVAxZz4PP_q7fGl0lXtDD38YnRWhTTU2VEvZ1wx0wukRe7g2YPkXf0lJTNr9-ctVVb-7mGdiQ8WZtK_EkBgwPcjIoQX5zTGryP4e3YPG_m8X4abVTIRSVd_QuaFqIZ46YtPTVWx1vHaBrTtTlDm9QTw1FaL7AjsJA5IrVy0a0OBTNZp0XBRlfGK_FRFibRXiHcdRPJejul9bhRfTm9q23A75q-2NOnX1RWjUjbEZJPX6WTgG6_svomuGPcn9qyKYy3R7o0XRo9zB1s4IOJ60TEoU7wYfazWEqxPmdLMctPMkDqncYxRZIF9dFOHOyPxeXlZ_NqXG7COEf0F-N66dgiXIfzHPyd19ZIaWW38Ma82ai-tElLwfh4PnO896Imd_O2ykR0UvaGAWzqZgSqB2kdQhwNsM01NXqxy5shGogDahTfxx9vcOTDqP86vq0HBpa21z3EUQ5NNLNeijBvwcSX-cO6TY-LjZHoMKReaxs5ZYNJ_ndZFdzaj9qK7V3Gu-xR2iurdqU1VUXyh8H6PT_G4jnOaZoaH3yiRt4g==) (nq_cadmium_pbo_licenses@2.133.0/pbo-client@2.133.0)", "display": "Ez a m\u0171sor nem \u00e1ll rendelkez\u00e9sre azonnali megtekint\u00e9sre. K\u00e9rj\u00fck, v\u00e1lassz m\u00e1sik m\u0171sort. - 1044", "alertTag": "", "errorDisplayMessage": "Ez a m\u0171sor nem \u00e1ll rendelkez\u00e9sre azonnali megtekint\u00e9sre. K\u00e9rj\u00fck, v\u00e1lassz m\u00e1sik m\u0171sort. - 1044", "errorActionId": 3, "nccpError": {}, "errorSubCode": 0, "errorReasonCode": 0, "errorNccpCode": 0, "errorExternalCode": 0, "bladeRunnerMessage": "license/pbl-1044: IssueLicensePolicyError (E3-BQFRAAELED1pnNOD12w9u7xJRjnxEjaBuUkjahZNjFaVryY5IdCksUSY1RxBgVQsqC3LTQ5_dVAxZz4PP_q7fGl0lXtDD38YnRWhTTU2VEvZ1wx0wukRe7g2YPkXf0lJTNr9-ctVVb-7mGdiQ8WZtK_EkBgwPcjIoQX5zTGryP4e3YPG_m8X4abVTIRSVd_QuaFqIZ46YtPTVWx1vHaBrTtTlDm9QTw1FaL7AjsJA5IrVy0a0OBTNZp0XBRlfGK_FRFibRXiHcdRPJejul9bhRfTm9q23A75q-2NOnX1RWjUjbEZJPX6WTgG6_svomuGPcn9qyKYy3R7o0XRo9zB1s4IOJ60TEoU7wYfazWEqxPmdLMctPMkDqncYxRZIF9dFOHOyPxeXlZ_NqXG7COEf0F-N66dgiXIfzHPyd19ZIaWW38Ma82ai-tElLwfh4PnO896Imd_O2ykR0UvaGAWzqZgSqB2kdQhwNsM01NXqxy5shGogDahTfxx9vcOTDqP86vq0HBpa21z3EUQ5NNLNeijBvwcSX-cO6TY-LjZHoMKReaxs5ZYNJ_ndZFdzaj9qK7V3Gu-xR2iurdqU1VUXyh8H6PT_G4jnOaZoaH3yiRt4g==) (nq_cadmium_pbo_licenses@2.133.0/pbo-client@2.133.0)", "bladeRunnerCode": "1044"}, "errorParams": {"drmSessionId": "287EA6A1786734790934D426DD0F75B9"}}]}
2023-06-02 16:32:03.881 T:6012     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2023-06-02 16:32:30.001 T:7720    error <general>: CCurlFile::CReadState::XFILE::CCurlFile::CReadState::FillBuffer - (0x12bde698) Failed: Timeout was reached(28)
2023-06-02 16:32:30.001 T:7720    error <general>: CCurlFile::XFILE::CCurlFile::Open - <http://127.0.0.1:50379/msl/get_license?videoid=70142823> Failed with code 0:
                                                   
2023-06-02 16:32:30.002 T:7720    error <general>: AddOnLog: inputstream.adaptive: License server returned failure
2023-06-02 16:32:30.003 T:7720     info <general>: Creating Demuxer
2023-06-02 16:32:30.007 T:6832    error <general>: ----------------------------------------
2023-06-02 16:32:30.008 T:6832    error <general>: 
                                                   
2023-06-02 16:32:30.008 T:6832    error <general>: Exception happened during processing of request from
2023-06-02 16:32:30.008 T:7720     info <general>: Opening stream: 1001 source: 256
2023-06-02 16:32:30.008 T:6832    error <general>:  
2023-06-02 16:32:30.009 T:6832    error <general>: ('127.0.0.1', 50498)
2023-06-02 16:32:30.009 T:6832    error <general>: 
                                                   
2023-06-02 16:32:30.234 T:7720     info <general>: Creating video codec with codec id: 167
2023-06-02 16:32:30.234 T:7720     info <general>: AddOnLog: inputstream.adaptive: VideoCodec::Open
2023-06-02 16:32:30.235 T:7720     info <general>: Creating video thread
2023-06-02 16:32:30.237 T:4268     info <general>: running thread: video_thread
2023-06-02 16:32:30.238 T:7720     info <general>: Opening stream: 1003 source: 256
2023-06-02 16:32:30.250 T:6832    error <general>: Traceback (most recent call last):
                                                   
2023-06-02 16:32:30.251 T:6832    error <general>: 
2023-06-02 16:32:30.251 T:6832    error <general>:   File "C:\Program Files (x86)\Kodi\system\python\Lib\socketserver.py", line 683, in process_request_thread
                                                       self.finish_request(request, client_address)
                                                   
2023-06-02 16:32:30.251 T:6832    error <general>: 
2023-06-02 16:32:30.252 T:6832    error <general>:   File "C:\Program Files (x86)\Kodi\system\python\Lib\socketserver.py", line 360, in finish_request
                                                       self.RequestHandlerClass(request, client_address, self)
                                                   
2023-06-02 16:32:30.252 T:6832    error <general>: 
2023-06-02 16:32:30.252 T:6832    error <general>:   File "C:\Program Files (x86)\Kodi\system\python\Lib\socketserver.py", line 747, in __init__
                                                       self.handle()
                                                   
2023-06-02 16:32:30.252 T:6832    error <general>: 
2023-06-02 16:32:30.252 T:6832    error <general>:   File "C:\Program Files (x86)\Kodi\system\python\Lib\http\server.py", line 434, in handle
                                                       self.handle_one_request()
                                                   
2023-06-02 16:32:30.253 T:6832    error <general>: 
2023-06-02 16:32:30.253 T:6832    error <general>:   File "C:\Program Files (x86)\Kodi\system\python\Lib\http\server.py", line 422, in handle_one_request
                                                       method()
                                                   
2023-06-02 16:32:30.253 T:6832    error <general>: 
2023-06-02 16:32:30.253 T:6832    error <general>:   File "C:\Users\Nagy Péter Árpád\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\http_server.py", line 47, in do_POST
                                                       handle_msl_request(self, func_name, data)
                                                   
2023-06-02 16:32:30.254 T:6832    error <general>: 
2023-06-02 16:32:30.254 T:6832    error <general>:   File "C:\Users\Nagy Péter Árpád\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\http_server.py", line 79, in handle_msl_request
                                                       license_data = server.server.netflix_session.msl_handler.get_license(data)
                                                   
2023-06-02 16:32:30.254 T:6832    error <general>: 
2023-06-02 16:32:30.254 T:6832    error <general>:   File "C:\Users\Nagy Péter Árpád\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\msl\msl_utils.py", line 60, in error_catching_wrapper
                                                       return func(*args, **kwargs)
                                                   
2023-06-02 16:32:30.255 T:6832    error <general>: 
2023-06-02 16:32:30.255 T:6832    error <general>:   File "C:\Users\Nagy Péter Árpád\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                   
2023-06-02 16:32:30.255 T:6832    error <general>: 
2023-06-02 16:32:30.255 T:6832    error <general>:   File "C:\Users\Nagy Péter Árpád\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\msl\msl_handler.py", line 331, in get_license
                                                       response = self.msl_requests.chunked_request(endpoint_url,
                                                   
2023-06-02 16:32:30.256 T:6832    error <general>: 
2023-06-02 16:32:30.256 T:6832    error <general>:   File "C:\Users\Nagy Péter Árpád\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                   
2023-06-02 16:32:30.256 T:6832    error <general>: 
2023-06-02 16:32:30.257 T:6832    error <general>:   File "C:\Users\Nagy Péter Árpád\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\msl\msl_requests.py", line 179, in chunked_request
                                                       chunked_response = self._process_chunked_response(
                                                   
2023-06-02 16:32:30.257 T:6832    error <general>: 
2023-06-02 16:32:30.257 T:6832    error <general>:   File "C:\Users\Nagy Péter Árpád\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                   
2023-06-02 16:32:30.257 T:6832    error <general>: 
2023-06-02 16:32:30.258 T:6832    error <general>:   File "C:\Users\Nagy Péter Árpád\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\msl\msl_requests.py", line 234, in _process_chunked_response
                                                       return _raise_if_error(decrypted_response)
                                                   
2023-06-02 16:32:30.258 T:6832    error <general>: 
2023-06-02 16:32:30.258 T:6832    error <general>:   File "C:\Users\Nagy Péter Árpád\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\msl\msl_requests.py", line 263, in _raise_if_error
                                                       raise MSLError(err_message, err_number)
                                                   
2023-06-02 16:32:30.259 T:6832    error <general>: 
2023-06-02 16:32:30.260 T:6832    error <general>: resources.lib.common.exceptions.MSLError: Ez a műsor nem áll rendelkezésre azonnali megtekintésre. Kérjük, válassz másik műsort. - 1044
                                                   
2023-06-02 16:32:30.260 T:6832    error <general>: 
2023-06-02 16:32:30.260 T:6832    error <general>: ----------------------------------------
2023-06-02 16:32:30.261 T:6832    error <general>: 
                                                   
2023-06-02 16:32:30.280 T:7720     info <general>: Finding audio codec for: 86056
2023-06-02 16:32:30.281 T:7720     info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder eac3
2023-06-02 16:32:30.282 T:7720     info <general>: CVideoPlayerAudio::OpenStream: Allowing max Out-Of-Sync Value of 10 ms
2023-06-02 16:32:30.282 T:7720     info <general>: Creating audio thread
2023-06-02 16:32:30.283 T:1840     info <general>: running thread: CVideoPlayerAudio::Process()
2023-06-02 16:32:30.284 T:7720     info <general>: Opening stream: 1011 source: 256
2023-06-02 16:32:30.312 T:7720     info <general>: CDVDSubtitlesLibass: Using libass version 1502000
2023-06-02 16:32:30.312 T:7720     info <general>: CDVDSubtitlesLibass: Creating ASS library structure
2023-06-02 16:32:30.312 T:7720     info <general>: CDVDSubtitlesLibass: Initializing ASS Renderer
2023-06-02 16:32:30.316 T:7720     info <general>: CDVDSubtitlesLibass: Initializing ASS library font settings
2023-06-02 16:32:30.532 T:7720     info <general>: CDVDSubtitlesLibass: Creating new ASS track
2023-06-02 16:32:30.732 T:1840     info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder eac3
2023-06-02 16:32:30.732 T:1840     info <general>: Creating audio stream (codec id: 86056, channels: 6, sample rate: 48000, no pass-through)
2023-06-02 16:32:30.733 T:4984     info <general>: CActiveAESink::OpenSink - initialize sink
2023-06-02 16:32:30.862 T:7720     info <general>: Opening stream: 1001 source: 256
2023-06-02 16:32:30.863 T:7720     info <general>: Opening stream: 1003 source: 256
2023-06-02 16:32:30.864 T:7720     info <general>: Finding audio codec for: 86056
2023-06-02 16:32:30.865 T:7720     info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder eac3
2023-06-02 16:32:30.866 T:7720     info <general>: Opening stream: 1011 source: 256
2023-06-02 16:32:31.208 T:1840     info <general>: CVideoPlayerAudio::OpenStream: Allowing max Out-Of-Sync Value of 10 ms
2023-06-02 16:32:31.253 T:6012     info <general>: Loading skin file: VideoFullScreen.xml, load type: KEEP_IN_MEMORY
2023-06-02 16:32:51.350 T:6012     info <general>: Loading skin file: VideoOSD.xml, load type: KEEP_IN_MEMORY
2023-06-02 16:33:00.299 T:1840     info <general>: CVideoPlayerAudio::ProcessDecoderOutput: Changed max allowed Out-Of-Sync value to 52 ms due self-learning
2023-06-02 16:34:32.945 T:4268    error <general>: AddOnLog: inputstream.adaptive: WV_CencSingleSampleDecrypter::DecryptAndDecodeVideo: Returned CDM status kNoKey for key 0000000004A8B3F80000000000000000
2023-06-02 16:34:42.954 T:4268     info <general>: Skipped 437 duplicate messages..
2023-06-02 16:34:42.954 T:4268    error <general>: AddOnLog: inputstream.adaptive: WV_CencSingleSampleDecrypter::DecryptAndDecodeVideo: Returned CDM status kNoKey for key 0000000004A8B3F80000000000000000
2023-06-02 16:34:44.661 T:6012     info <general>: Skipped 40 duplicate messages..
2023-06-02 16:34:44.661 T:6012     info <general>: CVideoPlayer::CloseFile()
2023-06-02 16:34:44.662 T:6012     info <general>: VideoPlayer: waiting for threads to exit
2023-06-02 16:34:44.671 T:7720     info <general>: CVideoPlayer::OnExit()
2023-06-02 16:34:44.672 T:7720     info <general>: Closing stream player 1
2023-06-02 16:34:44.673 T:7720     info <general>: Waiting for audio thread to exit
2023-06-02 16:34:44.674 T:1840     info <general>: thread end: CVideoPlayerAudio::OnExit()
2023-06-02 16:34:44.674 T:7720     info <general>: Closing audio device
2023-06-02 16:34:44.690 T:4984     info <general>: CActiveAESink::OpenSink - initialize sink
2023-06-02 16:34:44.691 T:7720     info <general>: Deleting audio codec
2023-06-02 16:34:44.691 T:7720     info <general>: Closing stream player 2
2023-06-02 16:34:44.693 T:7720     info <general>: waiting for video thread to exit
2023-06-02 16:34:44.693 T:4268     info <general>: thread end: video_thread
2023-06-02 16:34:44.695 T:7720     info <general>: deleting video codec
2023-06-02 16:34:44.696 T:7720     info <general>: Closing stream player 3
2023-06-02 16:34:44.869 T:7720     info <general>: ADDON: Dll Destroyed - InputStream Adaptive
2023-06-02 16:34:44.870 T:6012     info <general>: VideoPlayer: finished waiting
2023-06-02 16:34:44.871 T:6012     info <general>: CVideoPlayer::CloseFile()
2023-06-02 16:34:44.871 T:6012     info <general>: VideoPlayer: waiting for threads to exit
2023-06-02 16:34:44.871 T:6012     info <general>: VideoPlayer: finished waiting
2023-06-02 16:34:44.919 T:6012    error <general>: Control 50 in window 10025 has been asked to focus, but it can't
2023-06-02 16:34:54.848 T:6012     info <general>: Loading skin file: DialogButtonMenu.xml, load type: KEEP_IN_MEMORY
2023-06-02 16:34:57.473 T:6012     info <general>: Stopping the application...
2023-06-02 16:34:57.473 T:6012     info <general>: Stopping player
2023-06-02 16:34:57.474 T:6012     info <general>: Storing total System Uptime
2023-06-02 16:34:57.475 T:6012     info <general>: Saving settings
2023-06-02 16:34:57.496 T:6012     info <general>: Saving skin settings
2023-06-02 16:34:57.501 T:6012     info <general>: Stopping all
2023-06-02 16:34:57.502 T:6012     info <general>: ES: Stopping event server
2023-06-02 16:34:57.503 T:6012     info <general>: [WS-Discovery]: terminating
2023-06-02 16:34:57.507 T:6012     info <general>: stopping upnp
2023-06-02 16:34:57.728 T:8096     info <general>: ES: UDP Event server stopped
2023-06-02 16:34:57.783 T:6012     info <CWebserver[8080]>: Stopped
2023-06-02 16:34:57.783 T:6012     info <general>: CServiceAddonManager: failed to stop inputstream.ffmpegdirect (may have ended)
2023-06-02 16:34:59.352 T:7304     info <general>: [script.tubecast] ssdp: Stopping SSDP server
2023-06-02 16:34:59.565 T:6012     info <general>: CServiceAddonManager: failed to stop service.xbmc.versioncheck (may have ended)
2023-06-02 16:34:59.695 T:6012     info <general>: Application stopped
2023-06-02 16:34:59.896 T:6012     info <general>: PVR Manager: Stopping

The device is an Intel Atom x5-Z8300 Mini PC with Windows 10 22H2.

Can anyone tell me what could be the problem?
