### ISSUE TITLE
Watch list loading error

### ISSUE THREAD

**Issue by inowakowski** [CastagnaIT/plugin.video.netflix#1602]
### Netflix add-on version

1.22.1

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

When I try to open the 'watch' list, I receive the message Error 'Typeerror: Actor: Name Property Must Not Be Empty'

### Debug log - mandatory

Logs show nothing

### Screenshots

![PXL_20230715_210812796](https://github.com/CastagnaIT/plugin.video.netflix/assets/15818597/53e4e57b-3a6b-41a8-8ed3-58259d01992e)

**Comment by inowakowski** [comment]
The same problem occurs when searching or loading the next page of the list of saved videos to watch on "My List"

**Comment by CastagnaIT** [comment]
im not able to reproduce
where is the debug log?

**Comment by inowakowski** [comment]
The problem is that there is nothing in the logs and the problem occurs, for example, when loading the next page of the movie list or when opening the watch list. I had the same problem when searching for movies. I don't know if it's a regional problem (I'm from Poland) or something else.

**Comment by achylewski** [comment]
Same for me. Android and Windows.
Here's a snippet of the log:
`2023-08-16 23:48:38.990 T:20872    info <general>: [plugin.video.netflix (1)] The debug logging is set as DISABLED
2023-08-16 23:48:55.499 T:20872   error <general>: EXCEPTION: Actor: name property must not be empty
2023-08-16 23:48:55.503 T:20872   error <general>: [plugin.video.netflix (1)] Traceback (most recent call last):
                                                     File "C:\Users\achyl\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 29, in wrapper
                                                       func(*args, **kwargs)
                                                     File "C:\Users\achyl\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 265, in run
                                                       success = route(pathitems)
                                                     File "C:\Users\achyl\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 90, in lazy_login_wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\achyl\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 130, in route
                                                       _execute(nav_handler, pathitems[1:], G.REQUEST_PARAMS, root_handler)
                                                     File "C:\Users\achyl\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 159, in _execute
                                                       executor(pathitems=pathitems)
                                                     File "C:\Users\achyl\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\achyl\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\navigation\directory_utils.py", line 28, in set_custom_viewmode
                                                       override_content_type = func(*args, **kwargs)
                                                     File "C:\Users\achyl\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\navigation\directory.py", line 185, in video_list_sorted
                                                       dir_items, extra_data = common.make_call('get_video_list_sorted', call_args)
                                                     File "C:\Users\achyl\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\achyl\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\ipc.py", line 94, in make_call
                                                       return make_http_call(endpoint, func_name, data)
                                                     File "C:\Users\achyl\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\ipc.py", line 115, in make_http_call
                                                       _data = pickle.loads(received_data)
                                                     File "C:\Users\achyl\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\kodi_wrappers.py", line 72, in __setstate__
                                                       set_video_info_tag(state['infolabels'], video_info)
                                                     File "C:\Users\achyl\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\kodi_wrappers.py", line 170, in set_video_info_tag
                                                       video_info_tag.setCast([xbmc.Actor(name) for name in cast_names])
                                                     File "C:\Users\achyl\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\kodi_wrappers.py", line 170, in <listcomp>
                                                       video_info_tag.setCast([xbmc.Actor(name) for name in cast_names])
                                                   TypeError: Actor: name property must not be empty`
