### ISSUE TITLE
NFAuthenticationKey.py: 'Unable to connect with the browser'

### ISSUE THREAD

**Issue by bobblkabb** [CastagnaIT/plugin.video.netflix#1712]
### Netflix add-on version

1.23.3

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Other (specify in description)

### Description of the bug

When I execute the script browser opens up file temp location and after some time I'm getting error message:
`Unable to connect with the browser`
Had to do
`BROWSER_PATH = '/usr/bin/firefox'`
before because it couldn't find it.

Running openSUSE Tumbleweed. Necessary python packages are installed from the repo.

### Steps to reproduce the behavior

1. Install python311-pycryptodomex python311-websocket-client via package manager
2. execute 'python3 NFAuthenticationKey.py'
3. temp location is opened in browser
4. -> error message after some time

### Debug log - mandatory

no log

**Comment by StatJonic** [comment]
input command: python3 NFAuthenticationKey.py

output:

Browser startup... (/var/lib/flatpak/app/com.brave.Browser/current/0721705cdc4c7e2bf2652a469bbe23e1d93e82856362ec3d050a5ad58d3b8886/files/brave) please wait
An error is occurred:
[Errno 13] Permission denied: '/var/lib/flatpak/app/com.brave.Browser/current/0721705cdc4c7e2bf2652a469bbe23e1d93e82856362ec3d050a5ad58d3b8886/files/brave'
Traceback (most recent call last):
  File "/home/fuelluz/Scrivania/NFAuthenticationKey.py", line 62, in __init__
    browser_proc = open_browser(browser_temp_path)
  File "/home/fuelluz/Scrivania/NFAuthenticationKey.py", line 229, in open_browser
    return subprocess.Popen([browser_path] + params, stdout=dev_null, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/var/lib/flatpak/app/com.brave.Browser/current/0721705cdc4c7e2bf2652a469bbe23e1d93e82856362ec3d050a5ad58d3b8886/files/brave'

Notes:
the path '/var/lib/flatpak/app/com.brave.Browser/current/0721705cdc4c7e2bf2652a469bbe23e1d93e82856362ec3d050a5ad58d3b8886/files/brave' is where Brave browser executable file is located.
