### ISSUE TITLE
Playbak never properly starts on some content

### ISSUE THREAD

**Issue by matejdro** [CastagnaIT/plugin.video.netflix#1716]
### Netflix add-on version

v1.23.3+matrix.1

### Operative systems used

Android

### Kodi version used

Other (specify in description)

### Description of the bug

When playing some content, playback never properly starts. Seekbar starts seeking, but loading spinner never disappears and there is no audio or video.

This same show has worked a couple of days ago, so something must have changed in the meantime. I can play it in the Netflix app on the some device without issue.

Kodi version is 21.0 (it looks like template needs updating, since 21 is not an option).

### Steps to reproduce the behavior

1. Play content that is broken (for example Queen's Gambit)

### Debug log - mandatory

https://paste.kodi.tv/torepixika.kodi

### Screenshots

![satty-20240807-08:16:19](https://github.com/user-attachments/assets/7f0547e1-5e2c-4d93-a84f-cb8691ef1a26)

**Comment by matejdro** [comment]
Hm, looking at the Android logs, this might be a clue:

```
08-07 08:28:42.854 27039  6596 W MediaCodec: Log queueSecureInputBuffer error: -2001
08-07 08:28:42.854 27039  5931 W System.err: android.media.MediaCodec$CryptoException: Crypto key not available
08-07 08:28:42.854 27039  5931 W System.err:    at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
08-07 08:28:42.854 27039  5931 W System.err:    at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2821)
```

**Comment by CastagnaIT** [comment]
this is related to know problems

**Comment by matejdro** [comment]
You mean this one? https://github.com/CastagnaIT/plugin.video.netflix/issues/1627

Symptoms appear different, it does not play at all instead of playing for only 2 minutes
