### ISSUE TITLE
Netflix plugin (0.15.1) not starting with ProfilesMissing exception

### ISSUE THREAD

**Issue by 0xced** [CastagnaIT/plugin.video.netflix#176]
Today the Netflix plugin stopped working, I could not even get to the profiles page as I was getting a `ProfilesMissing` exception:

```
2019-08-28 23:33:59.116 T:1453314784   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
  File "/home/pi/.kodi/addons/plugin.video.netflix/addon.py", line 109, in <module>
    route(filter(None, g.PATH.split('/')))
  File "/home/pi/.kodi/addons/plugin.video.netflix/addon.py", line 50, in lazy_login_wrapper
    return func(*args, **kwargs)
  File "/home/pi/.kodi/addons/plugin.video.netflix/addon.py", line 79, in route
    g.REQUEST_PARAMS)
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/__init__.py", line 21, in execute
    executor(pathitems=pathitems)
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 45, in root
    self.profiles()
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 51, in profiles
    listings.build_profiles_listing()
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/kodi/listings.py", line 29, in set_custom_viewmode
    override_partial_setting_id = func(*args, **kwargs)
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 246, in timing_wrapper
    return func(*args, **kwargs)
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/kodi/listings.py", line 61, in build_profiles_listing
    active_guid_profile = g.LOCAL_DB.get_active_profile_guid()
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_base_sqlite.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_local.py", line 89, in get_active_profile_guid
    return self._get_active_guid_profile()
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_local.py", line 20, in _get_active_guid_profile
    raise ProfilesMissing
ProfilesMissing
```

The cause of this error is that there is no profile in the local database. Indeed, running `sqlite3 $HOME/.kodi/userdata/addon_data/plugin.video.netflix/database/nf_local.sqlite3 "SELECT COUNT(*) FROM profiles"` returns `0`, which confirms that the profiles table is empty.

The profiles table is filled here:
```
nfsession.py:login
  nfsession.py:_login
    website.py:extract_session_data
      website.py:extract_profiles
        g.LOCAL_DB.set_profile(guid, is_active, sort_order)
```

So I tried to delete both nf_local.sqlite3 and nf_shared.sqlite3, start the Netflix plugin, re-entering my username and password, hoping that the profiles table would finally be populated. But it did not work, I was getting a "AddonSignals call timed out" errors. So I rebooted my Raspberry Pi but then I started getting "Error parsing MSL Encodable".

Finally, I deleted the whole `$HOME/.kodi/userdata/addon_data/plugin.video.netflix` directory, re-entered my Netflix username and password and I was finally able to access my Netflix profile.

But the story doesn't end here. When trying to play a video, I got the following error:

```
2019-08-29 00:23:16.108 T:1593823968   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/http_server.py", line 47, in do_GET
    data = self.server.msl_handler.load_manifest(int(params['id'][0]))
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 41, in error_catching_wrapper
    return func(*args, **kwargs)
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 246, in timing_wrapper
    return func(*args, **kwargs)
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 109, in load_manifest
    manifest = self._load_manifest(viewable_id, g.get_esn())
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 246, in timing_wrapper
    return func(*args, **kwargs)
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 195, in _load_manifest
    manifest_request_data, esn)
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 246, in timing_wrapper
    return func(*args, **kwargs)
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 244, in _chunked_request
    self._post(endpoint, self.request_builder.msl_request(request_data, esn)))
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 246, in timing_wrapper
    return func(*args, **kwargs)
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/request_builder.py", line 37, in msl_request
    return (json.dumps(self._signed_header(esn)) +
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 246, in timing_wrapper
    return func(*args, **kwargs)
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/request_builder.py", line 57, in _signed_header
    esn)
  File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/default_crypto.py", line 62, in encrypt
    cipher = AES.new(self.encryption_key, AES.MODE_CBC, init_vector)
  File "/home/pi/.local/lib/python2.7/site-packages/Cryptodome/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/Cryptodome/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/Cryptodome/Cipher/AES.py", line 92, in _create_base_cipher
    if len(key) not in key_size:
TypeError: object of type 'NoneType' has no len()
```

In despair, I deactivated then re-activated the Netflix plugin and I was finally able to watch Netflix! 🎉 (It looks like the last error is a know issue: #171)

Just documenting this here as it might help someone.

**Comment by Smeulf** [comment]
Did you change something in your Netfilx profiles before getting the ProfilesMissing exception?

Addition, removal, or any change? 

If you have no more profile in the DB, that's probably because nfssession retreived an empty list of profile, and then deleted all. Sad we don't have the full debug log for that execption., I really wonder how it could happen.

**Comment by Smeulf** [comment]
From website.py:
`def extract_profiles(falkor_cache):
    """Extract profile information from Netflix website"""
    try:
        profiles_list = OrderedDict(resolve_refs(falkor_cache['profilesList'], falkor_cache))
        _delete_non_existing_profiles(profiles_list)
        sort_order = 0
        for guid, profile in profiles_list.items():`

`def _delete_non_existing_profiles(profiles_list):
    list_guid = g.LOCAL_DB.get_guid_profiles()
    for guid in list_guid:
        if guid not in profiles_list.keys():
            common.debug('Deleting non-existing profile {}'.format(guid))
            g.LOCAL_DB.delete_profile(guid)
            g.SHARED_DB.delete_profile(guid)`

Maybe we should ensure there's at least one profile in `profiles_list` at extract_profiles?

**Comment by 0xced** [comment]
I did not change anything in my Netflix profiles for years.

Here are all the related errors before the `ProfilesMissing` exception occurred. Unfortunately, I did not have DEBUG enabled when this happened. Hope this helps.

```
2019-08-28 22:52:32.509 T:1673515744   ERROR: [plugin.video.netflix (0)] Mastertoken has expired
2019-08-28 22:52:39.203 T:1673515744   ERROR: [plugin.video.netflix (0)] Full MSL error information:
2019-08-28 22:52:39.204 T:1673515744   ERROR: [plugin.video.netflix (0)] {"entityauthdata": {"authdata": {"pubkeyid": "MSL_TRUSTED_NETWORK_SERVER_KEY", "identity": "Netflix"}, "scheme": "RSA"}, "errordata": "eyJpbnRlcm5hbGNvZGUiOjEwMDAwMCwibWVzc2FnZWlkIjoxLCJlcnJvcmNvZGUiOjEsImVycm9ybXNnIjoiRXJyb3IgcGFyc2luZyBNU0wgZW5jb2RhYmxlLiIsInRpbWVzdGFtcCI6MTU2NzAyNTU1OX0=", "signature": "***REDACTED***"}
2019-08-28 22:53:05.235 T:1673515744   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'resources.lib.services.msl.exceptions.MSLError'>
                                            Error Contents: Error parsing MSL encodable.
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/service.py", line 114, in <module>
                                                NetflixService().run()
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/service.py", line 47, in __init__
                                                self.init_server(server)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/service.py", line 55, in init_server
                                                ('127.0.0.1', common.select_port(server['name'])))
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/http_server.py", line 67, in __init__
                                                self.msl_handler = MSLHandler()
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 69, in __init__
                                                if self.perform_key_handshake():
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 41, in error_catching_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 246, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 91, in perform_key_handshake
                                                self.request_builder.handshake_request(esn)))
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 246, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 280, in _process_json_response
                                                return _raise_if_error(response.json())
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 289, in _raise_if_error
                                                raise MSLError(_get_error_details(decoded_response))
                                            MSLError: Error parsing MSL encodable.
                                            -->End of Python script error report<--
2019-08-28 22:53:38.860 T:1461707488   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
2019-08-28 22:53:38.871 T:1902076768   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
2019-08-28 22:55:59.692 T:1453314784   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/addon.py", line 108, in <module>
                                                if check_valid_credentials():
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/addon.py", line 88, in check_valid_credentials
                                                if not api.login():
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/api/shakti.py", line 52, in login
                                                if not common.make_call('login'):
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 246, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 61, in make_call
                                                return make_addonsignals_call(callname, data)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 98, in make_addonsignals_call
                                                raise Exception('AddonSignals call timed out')
                                            Exception: AddonSignals call timed out
2019-08-28 22:56:18.668 T:1461707488   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
2019-08-28 22:56:18.688 T:1902076768   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
2019-08-28 22:56:25.253 T:1453314784   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/addon.py", line 109, in <module>
                                                route(filter(None, g.PATH.split('/')))
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/addon.py", line 50, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/addon.py", line 79, in route
                                                g.REQUEST_PARAMS)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/__init__.py", line 21, in execute
                                                executor(pathitems=pathitems)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 45, in root
                                                self.profiles()
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 51, in profiles
                                                listings.build_profiles_listing()
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/kodi/listings.py", line 29, in set_custom_viewmode
                                                override_partial_setting_id = func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 246, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/kodi/listings.py", line 61, in build_profiles_listing
                                                active_guid_profile = g.LOCAL_DB.get_active_profile_guid()
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_base_sqlite.py", line 41, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_local.py", line 89, in get_active_profile_guid
                                                return self._get_active_guid_profile()
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_local.py", line 20, in _get_active_guid_profile
                                                raise ProfilesMissing
                                            ProfilesMissing
```

**Comment by Smeulf** [comment]
Thanks @0xced 

You have the MSL error before profile list gets empty. I guess this is the why all profiles were deleted, or not created at all if you updated it today.

We still have some things to polish ^^

**Comment by setegonz** [comment]
I'm having the Missing profiles issue. Do I need to do something special to watch Netflix in Androidtv?

**Comment by SimeoneVilardo** [comment]
I had this error today. Uninstalling and reinstalling the plugin solved it.

**Comment by setegonz** [comment]
@SimeoneVilardo Uninstalling and reinstalling doesn't work for me on Android tv 8.0.

**Comment by CastagnaIT** [comment]
I published a new update with many fixes, should solve your problems

**Comment by setegonz** [comment]
@CastagnaIT Now I have "exception: connection error". I tried different accounts, but the error is the same. Android tv 8.0.

**Comment by Smeulf** [comment]
You have to post your full debug logs for us to understand what's going on.

**Comment by setegonz** [comment]
@Smeulf I started the installation again to record the logs. But it turned out that I don't have the error anymore.

**Comment by Smeulf** [comment]
Well @setegonz, should you see the error again, please fill a new issue with full logs :) Enjoy your videos!

**Comment by Spammychips** [comment]
Ok i was having the same issue "profile missing" on android fire and pc so i went into latest Netflix addon 1.1.1  went into >settings>views>enable custom views>enable>view for profiles>custom>custom view id i put mine to "1" then press "OK" go out of addon then come back into it login and BAM the dogs bollocks your in. Thanks to the DEV great piece of work

**Comment by EarthK** [comment]
I have the same "profile missing" problem on Raspberry 3 (LibreELEC 9.2.0) and Netfix plugin 1.1.1. I try to delete plugin and install again, doesn't help. Spammychips recommendation also doesn't work.
