### ISSUE TITLE
problem install addon 

### ISSUE THREAD

**Issue by maxence59110** [CastagnaIT/plugin.video.netflix#187]
## Support request

- Netflix : 15.2
- OSMC sur RP3

when i try to launch a video on netflix, the program lauch the download and uncompressed the  "widevine"

after, it's ko with this error

2019-09-03 18:16:13.372 T:1143964384   ERROR: [plugin.video.netflix (41)] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/addon.py", line 109, in <module>
                                                route(filter(None, g.PATH.split('/')))
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/addon.py", line 50, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/addon.py", line 70, in route
                                                player.play(pathitems=pathitems[1:])
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/videoid.py", line 287, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 246, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 57, in play
                                                list_item = get_inputstream_listitem(videoid)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 102, in get_inputstream_listitem
                                                if not is_helper.check_inputstream():
                                              File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 1004, in check_inputstream
                                                return self._check_drm()
                                              File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 962, in _check_drm
                                                return self.install_widevine()
                                              File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 745, in install_widevine
                                                return self._install_widevine_arm()
                                              File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 710, in _install_widevine_arm
                                                self._losetup(bin_path),
                                              File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 371, in _losetup
                                                output = self._run_cmd(cmd, sudo=True)
                                              File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 324, in _run_cmd
                                                output = subprocess.check_output(cmd, shell=shell, stderr=subprocess.STDOUT)
                                              File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
                                                process = Popen(stdout=PIPE, *popenargs, **kwargs)
                                              File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
                                                errread, errwrite)
                                              File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
                                                raise child_exception
                                            TypeError: execv() arg 2 must contain only strings

can you help me?

**Comment by Smeulf** [comment]
Did you follow this guide to setup the addon? https://discourse.osmc.tv/t/how-to-all-platforms-can-i-use-netflix-on-osmc-post-4/54741/4

Also regarding your (partial) log, the issue seems to be in script.module.inputstreamhelper addon we do not maintain.

**Comment by maxence59110** [comment]
yes i try but it's ko
can you tell me if you have a recommandation about  script.module.inputstreamhelper to use?

**Comment by Smeulf** [comment]
There's no specific settings for InputStream helper.

You still can try to uninstall/reinstall it, or to install Widevine again by forcing "last_update" to 0 in InputStream helper settings.xml file.

**Comment by ferrap** [comment]
I've got the same issue.

**Comment by maxence59110** [comment]
I try to install but it s ko. It s possible to make a install manual of widevine?

**Comment by Smeulf** [comment]
Can you enable debug, restart OSMC and post a full debug log?

**Comment by Smeulf** [comment]
Hold on, there's an update of inputstream helper released one hour ago, that should solve your issue.

Please try 0.4.2: https://github.com/emilsvennesson/script.module.inputstreamhelper/releases

**Comment by Smeulf** [comment]
https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/146

**Comment by ferrap** [comment]
Thanks for the hint @Smeulf , it's now working with the new update!

**Comment by maxence59110** [comment]
ok thanks @Smeulf . now no error. butwhen i launch a episode, i have a black screen and no sound. can you help me ? @ferrap  : can you tell me your configuration (option) addon netflix ? I think that the problem is the configuration

**Comment by maxence59110** [comment]
i solved my problem. i disabled omxplayer. thanks a lot
