### ISSUE TITLE
KeyError: u'licenseResponseBase64'

### ISSUE THREAD

**Issue by Leviathan09** [CastagnaIT/plugin.video.netflix#2]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?
YES

### Description
When selecting a title in the menu, the loading wheel apears for a second or two then a Screen with the Error 'licenseResponseBase64' appears and wnat me to enable debug log for more informations

### Steps to Reproduce

1. Opened Netflix Add-On
2. Selected Series
3. Selected Episode

**Expected behavior:** [What you expected to happen]
Play the selected episode

**Actual behavior:** [What actually happened]
Error 'licenseResponseBase64' appears
### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment
Latest nightly of OSMC

## Debug log

[https://file.io/Gg7COJ](url)

### Screenshots

[https://imgur.com/a/M0MwXHP](url)

**Comment by CastagnaIT** [comment]
please put the complete log file,
and write me the name of series you tried

**Comment by Leviathan09** [comment]
Complete Log [http://sprunge.us/BQCIkb](url)

Tried to watch Nightflyers

**Comment by wintuxx** [comment]
http://sprunge.us/BQCIkb

**Comment by CastagnaIT** [comment]
I'm sorry, but I haven't been able to reproduce your problem,
I also tried to change the language in German but the series you mentioned to me works correctly.

I noticed that in your log, there is a lack of logging debug information and profile debugging which is particularly strange... unless you deleted it.

The error however reports that the series mentioned is not playable in streaming. Maybe a temporary problem?

**Comment by ernstp** [comment]
Also getting this error. Running under Swedish locale...

```
2019-08-30 21:51:15.959 T:3011836384  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.netflix/play/show/80073754/season/80073803/episode/80073804/
2019-08-30 21:51:15.960 T:2615628656  NOTICE: Creating InputStream
2019-08-30 21:51:15.969 T:2615628656   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2019-08-30 21:51:20.161 T:2657592176   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/http_server.py", line 34, in do_POST
                                                challenge=data[0], sid=base64.standard_b64decode(data[1]))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 41, in error_catching_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 246, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 231, in get_license
                                                return response[0]['licenseResponseBase64']
                                            KeyError: u'licenseResponseBase64'
2019-08-30 21:51:20.162 T:2615628656   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
2019-08-30 21:51:20.162 T:2615628656   ERROR: CCurlFile::Open failed with code 400 for http://localhost:48729/license?id=80073804:
2019-08-30 21:51:20.162 T:2615628656   ERROR: AddOnLog: InputStream Adaptive: License server returned failure
2019-08-30 21:51:20.163 T:2615628656   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
2019-08-30 21:51:20.163 T:2657592176   ERROR: Traceback (most recent call last):
2019-08-30 21:51:20.163 T:2657592176   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
2019-08-30 21:51:20.163 T:2657592176   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
2019-08-30 21:51:20.163 T:2657592176   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2019-08-30 21:51:20.164 T:2657592176   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
2019-08-30 21:51:20.164 T:2657592176   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
2019-08-30 21:51:20.164 T:2657592176   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
2019-08-30 21:51:20.164 T:2657592176   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
2019-08-30 21:51:20.164 T:2657592176   ERROR: error: [Errno 32] Broken pipe
2019-08-30 21:51:20.204 T:2615628656   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
2019-08-30 21:51:20.206 T:2615628656   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/play/show/80073754/season/80073803/episode/80073804/]
2019-08-30 21:51:20.207 T:2615628656  NOTICE: CVideoPlayer::OnExit()
2019-08-30 21:51:20.228 T:3011836384  NOTICE: CVideoPlayer::CloseFile()
2019-08-30 21:51:20.228 T:3011836384  NOTICE: VideoPlayer: waiting for threads to exit
2019-08-30 21:51:20.228 T:3011836384  NOTICE: VideoPlayer: finished waiting ```

**Comment by ernstp** [comment]
When I logged in I did not have the Widevine plugin installed yet. Logging out and logging in again after that was installed seems to have solved the problem.

**Comment by CastagnaIT** [comment]
this log segment does not help is not clear, i need a full log with kodi debug activated

**Comment by tkerber** [comment]
Here's a full kodi debug log with the same issue: [kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3602313/kodi.log)
