### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by nahemoth33** [CastagnaIT/plugin.video.netflix#213]
#### Your Environment
- Netflix add-on version: 0.15.2
- Operating system version/name: Raspbian Stretch
- Device model:  Raspberry Pi 3B+
- Kodi version: 18.2-1~stretch 500                                                                                                                          500 http://archive.raspberrypi.org/debian stretch/main armhf Packages

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request

I'm not able getting the plugin working. The error is only to look in the log file for errors.
Thereˋs the log file:
[kodilog.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/3613146/kodilog.txt)
Thx 4 hlp!

**Comment by Smeulf** [comment]
`from Cryptodome.Util import Padding
                                            ImportError: cannot import name Padding`

You miss Cryptodome package.
https://github.com/CastagnaIT/plugin.video.netflix#prerequisites

**Comment by dagwieers** [comment]
It's a problem I noticed having on Windows Kodi + Python 3. I noticed that the Python 3 specific build has disappeared. Maybe it is now enabled by default in all nightly builds?
https://github.com/xbmc/xbmc/pull/16116#issuecomment-529961993

**Comment by nahemoth33** [comment]
ok, now I'm one step further:
[kodilog.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/3613573/kodilog.txt)

**Comment by Smeulf** [comment]
Try uninstall the add-on with delete settings. Then install it again.

Should you get an error again, I'll need the full debug log since Kodi start: enable debug, restart Kodi, reproduce error, provide log.

**Comment by TheProgramableTurtle** [comment]
I have the same problem, I pip installed Cryptodome, restarted the system, uninstalled and reinstalled the addon, but still get this error:

 Control 55 in window 10025 has been asked to focus, but it can't
2019-09-15 19:31:39.876 T:2975806048   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.netflix/)
2019-09-15 19:31:39.876 T:2975806048   DEBUG:   ParentPath = [plugin://plugin.video.netflix/]
2019-09-15 19:31:39.884 T:2777465584   DEBUG: Thread waiting start, auto delete: false
2019-09-15 19:31:39.895 T:2837463792   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.netflix] took 19 ms
2019-09-15 19:31:39.898 T:2777465584   DEBUG: StartScript - calling plugin Netflix('plugin://plugin.video.netflix/','3','','resume:false')
2019-09-15 19:31:39.898 T:2674606832   DEBUG: Thread LanguageInvoker start, auto delete: false
2019-09-15 19:31:39.899 T:2674606832    INFO: initializing python engine.
2019-09-15 19:31:39.899 T:2674606832   DEBUG: CPythonInvoker(5, /home/kodi/.kodi/addons/plugin.video.netflix/addon.py): start processing
2019-09-15 19:31:39.984 T:2975806048   DEBUG: ------ Window Init (DialogBusy.xml) ------
2019-09-15 19:31:40.915 T:2674606832   DEBUG: -->Python Interpreter Initialized<--
2019-09-15 19:31:40.916 T:2674606832   DEBUG: CPythonInvoker(5, /home/kodi/.kodi/addons/plugin.video.netflix/addon.py): the source file to load is "/home/kodi/.kodi/ad$
2019-09-15 19:31:40.921 T:2674606832   DEBUG: CPythonInvoker(5, /home/kodi/.kodi/addons/plugin.video.netflix/addon.py): setting the Python path to /home/kodi/.kodi/add$
2019-09-15 19:31:40.922 T:2674606832   DEBUG: CPythonInvoker(5, /home/kodi/.kodi/addons/plugin.video.netflix/addon.py): entering source directory /home/kodi/.kodi/addo$
2019-09-15 19:31:40.922 T:2674606832   DEBUG: CPythonInvoker(5, /home/kodi/.kodi/addons/plugin.video.netflix/addon.py): instantiating addon using automatically obtaine$
2019-09-15 19:31:41.936 T:2674606832   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
2019-09-15 19:31:41.937 T:2674606832   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
2019-09-15 19:31:42.594 T:2674606832   DEBUG: [plugin.video.netflix (3)] Trying connection to the database nf_local.sqlite3
2019-09-15 19:31:42.597 T:2674606832   DEBUG: [plugin.video.netflix (3)] Database connection nf_local.sqlite3 was successful (SQLite ver. 3.16.2)
2019-09-15 19:31:44.493 T:2674606832   DEBUG: [plugin.video.netflix (3)] Trying connection to the database nf_shared.sqlite3
2019-09-15 19:31:44.495 T:2674606832   DEBUG: [plugin.video.netflix (3)] Database connection nf_shared.sqlite3 was successful (SQLite ver. 3.16.2)
2019-09-15 19:31:52.775 T:2674606832   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named Cryptodome.Random
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/addon.py", line 28, in <module>
                                                import resources.lib.navigation.player as player
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 16, in <module>
                                                from resources.lib.services.playback import get_timeline_markers
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/__init__.py", line 6, in <module>
                                                from .msl.http_server import MSLTCPServer
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/http_server.py", line 17, in <module>
                                                from .msl_handler import MSLHandler
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 22, in <module>
                                                from .request_builder import MSLRequestBuilder
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/request_builder.py", line 23, in <module>
                                                from .default_crypto import DefaultMSLCrypto as MSLCrypto
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/default_crypto.py", line 7, in <module>
                                                from Cryptodome.Random import get_random_bytes
                                            ImportError: No module named Cryptodome.Random
                                            -->End of Python script error report<--

**Comment by TheProgramableTurtle** [comment]
Nevermind, I have fixed this issue and logged in.

**Comment by nahemoth33** [comment]
> Try uninstall the add-on with delete settings. Then install it again.
> 
> Should you get an error again, I'll need the full debug log since Kodi start: enable debug, restart Kodi, reproduce error, provide log.

OK, I will test that on Friday and provide the log file.
