### ISSUE TITLE
pycparser error prevents start of plugin

### ISSUE THREAD

**Issue by pete-dawgg** [CastagnaIT/plugin.video.netflix#219]
#### Your Environment
- Netflix add-on version: 0.15.2
- Platform: Linux x86 64-bit
- Kodi 18.4 Git:20190910 compiled 2019-09-10 by GCC 9.2.0 
- Gentoo-Linux ~amd64
- Kernel: Linux x86 64-bit version 5.3.0-gentoo
- FFmpeg version/source: 4.2.1

Used Operating system:
* [X ] Linux

### Describe the bug
Plugin does not start (and cannot be configured: account-data cannot be typed in anywhere)
There is an error-msg on the KODI-gui: "Netflix-Plugin Error"
More details in kodi.log

#### Expected behavior
plugin should start

#### Actual behavior
Error - cannot be started
#### Steps to reproduce the behavior
run KODI with activated plugin

### Debug log
there are 100+ errors like this one:
`ERROR: WARNING: /usr/lib64/python2.7/site-packages/pycparser/c_parser.py:1688: No documentation string specified in function 'p_postfix_expression_4' (ignored)`
and after the last one:
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'pycparser.ply.yacc.YaccError'>
                                            Error Contents: Unable to build parser
                                            Traceback (most recent call last):
                                              File "/home/ice/.kodi/addons/plugin.video.netflix/service.py", line 23, in <module>
```
full log:  http://dpaste.com/1Y8WG69

full debug log: https://eismanns.org/bin/?d2443a9a52cf63b5#J1USzarJ8jmF6rVLEyqqA9wHjDs21vFxRRvoyoEkHiqW
(Download attachment: kodi.log.xz)

### Additional context or screenshots (if appropriate)
KODI runs with python2.7 in gentoo.
I had to copy the crytodomex-files in the kodi-running user's homedir from python3.6 to  python2.7 or there would be an import error of module Crypto.Random.

**Comment by Smeulf** [comment]
> I had to copy the crytodomex-files in the kodi-running user's homedir from python3.6 to python2.7 or there would be an import error of module Crypto.Random.

Was Cryptodomex installed for for Python 2.7 before you copy the files?

If not, you should try to remove the files you copied and install Cryptodomex correctly.

**Comment by pete-dawgg** [comment]
THX for you reply!
Removed pycryptodomex and reinstalled with
` pip2.7 install --user pycryptodomex`
now it looks like this:
```
ls ~/.local/lib64/python2.7/site-packages/
Cryptodome  pycryptodomex-3.9.0.dist-info
```
but the error remains (almost) the same.
 ```
ERROR: ERROR: start symbol translation_unit_or_empty undefined
2019-09-18 20:02:56.438 T:139926360266496   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'pycparser.ply.yacc.YaccError'>
                                            Error Contents: Unable to build parser
                                            Traceback (most recent call last):
                                              File "/home/ice/.kodi/addons/plugin.video.netflix/service.py", line 23, in <module>
                                                import resources.lib.services as services
                                              File "/home/ice/.kodi/addons/plugin.video.netflix/resources/lib/services/__init__.py", line 6, in <module>
                                                from .msl.http_server import MSLTCPServer
                                              File "/home/ice/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/http_server.py", line 17, in <module>
                                                from .msl_handler import MSLHandler
                                              File "/home/ice/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 22, in <module>
                                                from .request_builder import MSLRequestBuilder
                                              File "/home/ice/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/request_builder.py", line 23, in <module>
                                                from .default_crypto import DefaultMSLCrypto as MSLCrypto
                                              File "/home/ice/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/default_crypto.py", line 8, in <module>
                                                from Cryptodome.Hash import HMAC, SHA256
                                              File "/home/ice/.local/lib64/python2.7/site-packages/Cryptodome/Hash/HMAC.py", line 38, in <module>
                                                from Cryptodome.Hash import MD5
                                              File "/home/ice/.local/lib64/python2.7/site-packages/Cryptodome/Hash/MD5.py", line 23, in <module>
                                                from Cryptodome.Util._raw_api import (load_pycryptodome_raw_lib,
                                              File "/home/ice/.local/lib64/python2.7/site-packages/Cryptodome/Util/_raw_api.py", line 89, in <module>
                                                uint8_t_type = ffi.typeof(ffi.new("const uint8_t*"))
                                              File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 262, in new
                                                cdecl = self._typeof(cdecl)
                                              File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 182, in _typeof
                                                result = self._typeof_locked(cdecl)
                                              File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 167, in _typeof_locked
                                                type = self._parser.parse_type(cdecl)
                                              File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 508, in parse_type
                                                return self.parse_type_and_quals(cdecl)[0]
                                              File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 511, in parse_type_and_quals
                                                ast, macros = self._parse('void __dummy(\n%s\n);' % cdecl)[:2]
                                              File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 294, in _parse
                                                ast = _get_parser().parse(fullcsource)
                                              File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 52, in _get_parser
                                                _parser_cache = pycparser.CParser()
                                              File "/usr/lib64/python2.7/site-packages/pycparser/c_parser.py", line 117, in __init__
                                                outputdir=taboutputdir)
                                              File "/usr/lib64/python2.7/site-packages/pycparser/ply/yacc.py", line 3352, in yacc
                                                raise YaccError('Unable to build parser')
```

full log [here](http://dpaste.com/2XJK421)

pycryptodome-3.8.2 is also installed system-wide for python2.7, python3.6 and python3.7

**Comment by Smeulf** [comment]
For a test, can you uninstall all Python version but 2.7?

Or ensure Python 2.7 paths are the firsts to find the binaries...

**Comment by pete-dawgg** [comment]
As  much as i'd like to get this plugin running uninstalling all of the 3*-versions is problematic since there is some other software and specifically the distros's package- and config-manager ("portage") that depends on it.
But i set the default python-version to 2.7 so when i just execute python i get 2.7:
 ```
~/.kodi/temp $ python
Python 2.7.16 (default, Jul  1 2019, 10:24:16) 
[GCC 9.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
ice@medi ~/.kodi/temp $ 
```
However, the error persists just in the same way.
Can it be related to the way python was built (stripped of some symbols bc of "-O2")?

**Comment by Smeulf** [comment]
> As much as i'd like to get this plugin running uninstalling all of the 3*-versions is problematic

I do understand.

Just did a quick search on the error, an found this https://github.com/eliben/pycparser/issues/291

Looks like a known issue as you guessed, related to "-O2" build option.

So it's something you will have to fix on you side...

**Comment by pete-dawgg** [comment]
Don't mean to nag, but....
I recompiled python 2.7 and all related PKGs (dev-python/certifi dev-python/cffi dev-python/docutils  dev-python/mako dev-python/markupsafe dev-python/olefile dev-python/pillow dev-python/pip dev-python/ply  dev-python/pyblake2 dev-python/pycparser dev-python/pycryptodome  dev-python/pygments dev-python/setuptools) with
`CFLAGS="-march=x86-64 -mtune=k8 -O0  -fomit-frame-pointer -pipe" CXXFLAGS="${CFLAGS}"`
and the error still persists in the very same way. The system default is -O2 and all software is installed with that.

I'll try to fix it (LDFLAGS?)  and if i make any progress i'll report it.
THX for your help!

**Comment by pete-dawgg** [comment]
It runs now.
The problem i faced was an old [bug](https://bugs.gentoo.org/667764) in (gentoo's versions of) pycparser-2.17 to -2.19. I installed pycparser-2.14 and the plugin runs now. (I had already wondered what kind of optimizations GCC and LD might apply to python-programs which are basically textfiles.)
I like this plugin! Very nice work. Thank Youi

**Comment by Smeulf** [comment]
Thanks for the feedback!

**Comment by hpkkumar007** [comment]
Thanks @pete-dawgg 
Downgrading to pycparser-2.14, solved this issue for me also.
