### ISSUE TITLE
error licenseResponseBase64

### ISSUE THREAD

**Issue by quatreplusquatre** [CastagnaIT/plugin.video.netflix#222]
## Bug report
Hi guys,
On my new installation of Libreelec, when I run any episode of any series, I have an error with the licenseResponseBase64. (HTTP returned error 400)
I seem missing files but I do not know how to fix. I already reinstall the addon.

Thank you for your help.

#### Your Environment
- Netflix add-on version: 
- Operating system version/name: 
- Device model:  

Used Operating system:
* [ *] Raspberry-Pi

### Debug log

VideoPlayer::OpenFile: plugin://plugin.video.netflix/play/show/80023644/season/80023791/episode/80023656/
2019-09-22 19:11:53.505 T:2519872368  NOTICE: Creating InputStream
2019-09-22 19:11:53.578 T:2519872368   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2019-09-22 19:12:09.209 T:2643968880   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/http_server.py", line 34, in do_POST
                                                challenge=data[0], sid=base64.standard_b64decode(data[1]))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 41, in error_catching_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 236, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 232, in get_license
                                                return response[0]['licenseResponseBase64']
                                            KeyError: u'licenseResponseBase64'
2019-09-22 19:12:09.210 T:2519872368   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
2019-09-22 19:12:09.210 T:2519872368   ERROR: CCurlFile::Open failed with code 400 for http://localhost:37443/license?id=80023656:
2019-09-22 19:12:09.210 T:2519872368   ERROR: AddOnLog: InputStream Adaptive: License server returned failure
2019-09-22 19:12:09.210 T:2519872368   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
2019-09-22 19:12:09.210 T:2643968880   ERROR: Traceback (most recent call last):
2019-09-22 19:12:09.210 T:2643968880   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
2019-09-22 19:12:09.211 T:2643968880   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
2019-09-22 19:12:09.211 T:2643968880   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2019-09-22 19:12:09.211 T:2643968880   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
2019-09-22 19:12:09.211 T:2643968880   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
2019-09-22 19:12:09.212 T:2643968880   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
2019-09-22 19:12:09.212 T:2643968880   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
2019-09-22 19:12:09.212 T:2643968880   ERROR: error: [Errno 32] Broken pipe
2019-09-22 19:12:09.251 T:2519872368   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
2019-09-22 19:12:09.260 T:2519872368   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/play/show/80023644/season/80023791/episode/80023656/]
2019-09-22 19:12:09.260 T:2519872368  NOTICE: CVideoPlayer::OnExit()
2019-09-22 19:12:09.336 T:3011776528  NOTICE: CVideoPlayer::CloseFile()
2019-09-22 19:12:09.336 T:3011776528  NOTICE: VideoPlayer: waiting for threads to exit
2019-09-22 19:12:09.336 T:3011776528  NOTICE: VideoPlayer: finished waiting
2019-09-22 19:12:38.072 T:2864452464  NOTICE: NordVPN : (common.py) Received connection info from ipinfo.io, IP 184.162.34.99 location Quebec, CA, ISP AS5769 Videotron Telecom Ltee
2019-09-22 19:14:08.545 T:3011776528   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-09-22 19:14:19.535 T:3011776528  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.netflix/play/show/80023644/season/80023791/episode/80023656/
2019-09-22 19:14:19.536 T:2509288304  NOTICE: Creating InputStream
2019-09-22 19:14:19.548 T:2509288304   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2019-09-22 19:14:48.637 T:2509288304   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
2019-09-22 19:14:48.637 T:2509288304   ERROR: CCurlFile::Open failed with code 0 for http://localhost:37443/license?id=80023656:
2019-09-22 19:14:48.637 T:2509288304   ERROR: AddOnLog: InputStream Adaptive: License server returned failure
2019-09-22 19:14:48.637 T:2509288304   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
2019-09-22 19:14:48.678 T:2509288304   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
2019-09-22 19:14:48.681 T:2509288304   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/play/show/80023644/season/80023791/episode/80023656/]
-->
The debug log can be found here: http://ix.io/1Wtz

#### Installation
* [ *] I'm using other Netflix Repo

**Comment by quatreplusquatre** [comment]
Ok i find the problem. It's in my file advancedsettings.xml. The memory size was 0 (to use the hard disk)

Bye
