### ISSUE TITLE
Everytime get AddOn Error

### ISSUE THREAD

**Issue by madsters** [CastagnaIT/plugin.video.netflix#292]
#### Your Environment
- Netflix add-on version: newses (0.15.8)
- Operating system version/name: Kodi 18.4 on MacOS
- Device model:  MacBook Pro 2016

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [x] OSX
* [] Raspberry-Pi
* [ ] Windows

### Describe the bug
When i start the Addon for the first time i can log in, enter my passwort and then i get an AddON´n Error (look at Debug Log)

#### Expected behavior
What should happen is, that the Profile List Opens

#### Actual behavior

I get an Error.

#### Steps to reproduce the behavior

1.  Start Netflix-Addon
2. Enter E-Mail
3. Enter Passwort (press Enter)

### Debug log

The debug log can be found here: https://paste.kodi.tv/sinaxuxaxu (in Line 2249)
Copied from Debug Log:
`019-11-10 18:29:50.782 T:4547775936   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2019-11-10 18:30:27.246 T:123145497804800   ERROR: [plugin.video.netflix (26)] Traceback (most recent call last):
                                              File "/Users/matti/Library/Application Support/Kodi/addons/plugin.video.netflix/addon.py", line 106, in <module>
                                                if check_valid_credentials():
                                              File "/Users/matti/Library/Application Support/Kodi/addons/plugin.video.netflix/addon.py", line 88, in check_valid_credentials
                                                if not api.login():
                                              File "/Users/matti/Library/Application Support/Kodi/addons/plugin.video.netflix/resources/lib/api/shakti.py", line 46, in login
                                                if not common.make_call('login'):
                                              File "/Users/matti/Library/Application Support/Kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 236, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/Users/matti/Library/Application Support/Kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 61, in make_call
                                                return make_addonsignals_call(callname, data)
                                              File "/Users/matti/Library/Application Support/Kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 98, in make_addonsignals_call
                                                raise Exception('AddonSignals call timed out')
                                            Exception: AddonSignals call timed out
2019-11-10 18:30:31.781 T:123145496117248   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
2019-11-10 18:30:31.798 T:4547775936   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed`

### Additional context or screenshots (if appropriate)
https://paste.pics/7db57421efbf918c19cc52e30df64b44

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 
* I've used the ZIP File downloaded from GitHub

**Comment by madsters** [comment]
Sorry. It's not a problem from the Addon. It's one from my Mac. Opened on RPi - it works
