### ISSUE TITLE
Exporting show to library fails. 

### ISSUE THREAD

**Issue by jlo88** [CastagnaIT/plugin.video.netflix#314]
#### Your Environment
- Netflix add-on version: 15.9
- Operating system version/name: LibreElec 9.1.501 (leila 18.4)
- Device model:  Raspberry Pi 4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
I'm trying to export a show to my library. I get an error when I use this option. The show is not visible in tv shows. Exploring via ssh shows that the show was exported and the folder contains the stream files. 

#### Expected behavior
No error should occur and the show should be visible in tv shows

#### Actual behavior
An error occured and the show is not visible in tv shows. From the log: 
`2019-11-17 14:02:44.065 T:2471240560   ERROR: EXCEPTION: Invalid setting type
2019-11-17 14:02:44.081 T:2471240560   ERROR: [plugin.video.netflix (-1)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/addon.py", line 116, in <module>
                                                route(list(filter(None, g.PATH.split('/'))))
                                              File "/storage/.kodi/addons/plugin.video.netflix/addon.py", line 56, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/addon.py", line 85, in route
                                                g.REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/__init__.py", line 20, in execute
                                                executor(pathitems=pathitems)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/videoid.py", line 287, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/library.py", line 35, in remove
                                                common.get_local_string(30030))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/kodi/library.py", line 158, in kodi_library_update_wrapper
                                                library_operation(videoid, task_handler, *args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/kodi/library.py", line 713, in execute_library_tasks
                                                _sync_mylist(videoid, task_handler, sync_mylist)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/kodi/library.py", line 738, in _sync_mylist
                                                if enabled and operation and g.ADDON.getSettingBool('mylist_library_sync'):
                                            TypeError: Invalid setting type`

#### Steps to reproduce the behavior
Export a show. 

### Debug log
The debug log can be found from this link:
https://paste.kodi.tv/epugecozat.kodi
Error occurs at line 1456

#### Other information
I'm using a custom folder: /storage/netflix/

**Comment by CastagnaIT** [comment]
my oversight
install this and let me know
[plugin.video.netflix_0.15.9_20191117.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3855586/plugin.video.netflix_0.15.9_20191117.zip)

**Comment by jlo88** [comment]
Thanks! That fixed the error! 

I just seem to have a problem with the shows still not showing up in tv shows after updating but that might be unrelated. I saw that there are problems with the tvdb so maybe that causes issues as well. 

What was the problem in the end? The version number seems the same.. Just out of interest!

**Comment by CastagnaIT** [comment]
Wrong name when reading a setting,
unfortunately in my tests i had the xml file not cleaned so i never found the error...
