### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by FWeissenb** [CastagnaIT/plugin.video.netflix#351]
Hi,

my password includes a "ß" and I'm unable to login.
I get this error: 

`2019-12-01 13:06:49.733 T:2455761776   ERROR: [plugin.video.netflix (3)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 124, in run
                                                if _check_valid_credentials():
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 90, in _check_valid_credentials
                                                if not login():
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/api/shakti.py", line 45, in login
                                                ui.ask_credentials()
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/kodi/ui/dialogs.py", line 34, in ask_credentials
                                                common.set_credentials(email, password)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/credentials.py", line 106, in set_credentials
                                                g.LOCAL_DB.set_value('account_password', encrypt_credential(password))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/credentials.py", line 32, in encrypt_credential
                                                raw = bytes(Padding.pad(data_to_pad=raw.encode('utf-8'), block_size=__BLOCK_SIZE__))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)`

Any suggestions (yeah.. i can change my password. I mean OTHER suggestions :D)

**Comment by FWeissenb** [comment]
What is meant with "ignored rules"? What have I ignored?

**Comment by CastagnaIT** [comment]
you didn't follow the rules to publish an issue,
open an "issue" in a right way and it will be accepted
