### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by FWeissenb** [CastagnaIT/plugin.video.netflix#352]
#### Your Environment
- Netflix add-on version: 0.16.0
- Operating system version/name:Libreelec 9.2
- Device model: Raspberry Pi 4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
Hi,

my password includes a "ß" and I'm unable to login.
I get this error:

#### Expected behavior
Successful login

#### Actual behavior
Error/No login possible

#### Steps to reproduce the behavior

1. Put a non ascii character in your password
2. try login

#### Possible fix
Change password  handling (in the database?) from ascii to unicode

### Debug log
2019-12-01 13:06:49.733 T:2455761776 ERROR: [plugin.video.netflix (3)] Traceback (most recent call last): File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 124, in run if _check_valid_credentials(): File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 90, in _check_valid_credentials if not login(): File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/api/shakti.py", line 45, in login ui.ask_credentials() File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/kodi/ui/dialogs.py", line 34, in ask_credentials common.set_credentials(email, password) File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/credentials.py", line 106, in set_credentials g.LOCAL_DB.set_value('account_password', encrypt_credential(password)) File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/credentials.py", line 32, in encrypt_credential raw = bytes(Padding.pad(data_to_pad=raw.encode('utf-8'), block_size=__BLOCK_SIZE__)) UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)

The debug log can be found from this link:
http://ix.io/23hx

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by Baerht** [comment]
Dont create passwords with I ,l ,O, 0.  if your using different monitors . The Fonts can get distorted . I creates the password on a LED 21 computer screen but view Kodi on a 32' LCD TV . the letters I listed were a pain to figure out. As soon as I removed those letters, the password went in fine

**Comment by notoco** [comment]
I have been using passwords with I, l, 0, O ... for many years but I don't write them down, I only remember them. It always works.

**Comment by FWeissenb** [comment]
Ok. Thanks for this advice. But I know my password. And it works with many devices, but not with this Netflix plugin. :)
Yes, sure, I'm able to change my password. But I don't want to. :D

**Comment by CastagnaIT** [comment]
Install this test and let me know
[plugin.video.netflix_0.16.0_20191202_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3910071/plugin.video.netflix_0.16.0_20191202_t1.zip)

**Comment by FWeissenb** [comment]
Works4Me :) 

Thx

**Comment by CastagnaIT** [comment]
very good!

**Comment by FWeissenb** [comment]
It will be integrated in next official version that I can switch back to official release?

**Comment by CastagnaIT** [comment]
yes but there will be no short-term release, you can keep that installed
