### ISSUE TITLE
Error with Matrix nightly (since transitioning to Python3)

### ISSUE THREAD

**Issue by CiNcH83** [CastagnaIT/plugin.video.netflix#389]
#### Your Environment
- Netflix add-on version: 16.1
- Operating system version/name: Android 8.0 Oreo
- Device model:  Sony BRAVIA KD65-XF9005 (FW 6.6545)

Used Operating system:
* [X] Android

### Describe the bug
Netflix has been broken for me on Kodi 19 nightlies since transitioning to Python3. I did a fresh install and properly applied ESN. Still does not work. There is always an error during Netflix startup.

#### Steps to reproduce the behavior
1. Install Matrix nightly (e.g. kodi-20191217-cba7e017-master-armeabi-v7a) on Sony BRAVIA with Android TV
2. Start Kodi - error occurs during Netflix startup or when trying to play some video

### Debug log
The debug log can be found from this link: [CLICK](https://www.dropbox.com/s/4o3bo98n29iwtdq/kodi_netflix_error.log?dl=1)

```
019-12-18 18:55:40.876 T:21331   ERROR: EXCEPTION: argument "init" for "GetKeyRequest" must be a string or a bytearray
...
2019-12-18 18:55:40.876 T:21331   ERROR: EXCEPTION: argument "init" for "GetKeyRequest" must be a string or a bytearray
2019-12-18 18:55:50.532 T:21331   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 80, in __init__
                                                self.check_mastertoken_validity()
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 103, in check_mastertoken_validity
                                                if self.perform_key_handshake():
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 51, in error_catching_wrapper
                                                return func(*args, **kwargs)
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 264, in timing_wrapper
                                                return func(*args, **kwargs)
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 123, in perform_key_handshake
                                                self.request_builder.handshake_request(esn)))
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 264, in timing_wrapper
                                                return func(*args, **kwargs)
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/request_builder.py", line 58, in handshake_request
                                                compression=None, esn=esn).encode('utf-8')).decode('utf-8'),
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/request_builder.py", line 94, in _headerdata
                                                header_data['keyrequestdata'] = self.crypto.key_request_data()
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/android_crypto.py", line 62, in key_request_data
                                                bytes([10, 122, 0, 108, 56, 43]), 'application/xml', True, dict())
    TypeError: argument "init" for "GetKeyRequest" must be a string or a bytearray
```

**Comment by CastagnaIT** [comment]
Until Kodi 19 remains in apha phase, it's not a priority

python 3 on kodi 19 is not yet stable on all platforms kodi devs still working on it

can you give availability to test both versions (kodi 18 and 19) on android?

**Comment by CiNcH83** [comment]
> can you give availability to test both versions (kodi 18 and 19) on android?

Yes I can.

**Comment by CastagnaIT** [comment]
Here:
[plugin.video.netflix_0.16.1_20191221.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3991545/plugin.video.netflix_0.16.1_20191221.zip)

let me know on both Kodi's

**Comment by CiNcH83** [comment]
18.5: Error when trying to play video ([LOG](https://www.dropbox.com/s/xebacstyn0tueu6/kodi_netflix_18.5.log?dl=1))
20191220-c0cd2956: working (up to 4K with HDR, including Dolby Vision)

One thing I noticed with nightly was that Netflix service startup took much longer on the nightly compared to 18.5.

**Comment by CastagnaIT** [comment]
Here, now should working on both versions
[plugin.video.netflix_0.16.1_20191221_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3991579/plugin.video.netflix_0.16.1_20191221_t2.zip)

**Comment by CastagnaIT** [comment]
if it is slow, you can try purge cache (mem and on disk) on addon expert settings
it could be that the cache stored by Kodi 18 creates problems

**Comment by CiNcH83** [comment]
t2 gives me an error on installation:
```
2019-12-21 17:43:38.033 T:9113   ERROR: CAddonInstallJob[plugin.video.netflix]: The dependency on script.module.addon.signals version 0.0.3 could not be satisfied.
```

**Comment by CastagnaIT** [comment]
I didn't touch the dependecies, so there is a problem in your kodi
to my android install works

**Comment by CiNcH83** [comment]
I did a fresh Kodi install as rollback from nightly to 18.5 does not work anyway. Something seems to have gone wrong. I now did another Kodi reinstall and now it works. t2 plays stuff fine now too on 18.5.

Nightly also still works with t2.

Tried the cache purging thing with nightly too but it does not fix the slow Netflix service startup. It takes another 20s after Kodi is fully up.

**Comment by CiNcH83** [comment]
I now measured Kodi+Netflix service startup on fresh installs without configuring Netflix (not logged in a.s.o.).

Kodi Leia 18.5: <10s
Kodi Matrix 20191220-c0cd2956: ~30s

**Comment by CastagnaIT** [comment]
the loading time unfortunately depends on the weight of the libraries and the device. With the switch to python 3 some libraries have become more heavy,
i don't exclude some Python 3 issue with Kodi19 not yet resolved

even on my device it charges slower with Kodi 19, but it takes about:
3 seconds to show service ready message
8 seconds first addon run 
on smarthphone (android 8.0), fresh install

in daily build you can get updated version with others py3 fixes

**Comment by CiNcH83** [comment]
I see. Also Amazon VOD is painfully slow to navigate. Looks like we are still far away from a stable Py3.

**Comment by CastagnaIT** [comment]
Closed main problem is solved

**Comment by CiNcH83** [comment]
Netflix add-on gets disabled with recent Matrix nightlies. Suppose it is due to [this commit](https://github.com/xbmc/xbmc/pull/17188).
