### ISSUE TITLE
Queue Error

### ISSUE THREAD

**Issue by MediaBrasil** [CastagnaIT/plugin.video.netflix#41]
*I'm submitting a ...*
  - [ x ] bug report
  - [ ] feature request
  - [ ] support request

## General information

2019-03-31 15:15:49.231 T:2152   ERROR: [plugin.video.netflix (3)] Traceback (most recent call last):
                                              File "C:\Users\campo\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py", line 89, in <module>
                                                route(filter(None, g.PATH.split('/')))
                                              File "C:\Users\campo\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py", line 49, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "C:\Users\campo\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py", line 77, in route
                                                g.REQUEST_PARAMS)
                                              File "C:\Users\campo\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\navigation\__init__.py", line 21, in execute
                                                executor(pathitems=pathitems)
                                              File "C:\Users\campo\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\misc_utils.py", line 235, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "C:\Users\campo\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\navigation\directory.py", line 58, in video_list
                                                menu_data = g.PERSISTENT_STORAGE['sub_menus'][pathitems[1]]
                                            KeyError: u'queue'

### Addon version used

Latest version created in 03.31, with fix checked credentials included

### Description
Using windows 10 64 bits, appear this error queue when to try launch the addon, with Kodi Leia nigthly 18.2

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

**Comment by CastagnaIT** [comment]
Enable Kodi debug and include the log as described in the issue guide:

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/) or [https://pastebin.com/](https://pastebin.com/)) or similar, please do not paste]

**Comment by MediaBrasil** [comment]
Here debug, I clean install, but now I have distinct errors

https://pastebin.com/wpb9c9LN

**Comment by CastagnaIT** [comment]
in the debug it says that the server has a non-specific problem
if you haven't already done the only test you can do is reinstall the addon,
make sure after uninstall that the folder \userdata\addon_data\plugin.video.netflix
is completely deleted.

I don't know what else to suggest to you..
if after the reinstallation you still show up try to put here a new log to see if it turns out to be the same errors

**Comment by MediaBrasil** [comment]
I discover the issue, request widgets to Netflix with old values, its ok now.

I have one error only with recently added when try enter crash and don't appear items list.
