### ISSUE TITLE
InvalidProfilesError after upgrading to latest addon version

### ISSUE THREAD

**Issue by 0xced** [CastagnaIT/plugin.video.netflix#430]
#### Your Environment
- Netflix add-on version: 0.16.2
- Operating system version/name: Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
When launching the Netflix plugin I got an error dialog. Here are the detailed underlying error logs:
```
2020-01-12 21:21:15.083 T:1471922912   ERROR: [plugin.video.netflix (1)] convert_to_string: Data type <class 'collections.OrderedDict'> not mapped
2020-01-12 21:21:15.085 T:1471922912   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/api/website.py", line 113, in parse_profiles
                                                g.LOCAL_DB.set_profile_config(key, value, guid)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_base_sqlite.py", line 52, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_local.py", line 72, in set_profile_config
                                                value = common.convert_to_string(value)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/data_conversion.py", line 48, in convert_to_string
                                                raise DataTypeNotMapped
                                            DataTypeNotMapped
2020-01-12 21:21:15.088 T:1471922912   ERROR: [plugin.video.netflix (1)] Profile list data: OrderedDict([…redacted...])
2020-01-12 21:21:15.090 T:1471922912   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 165, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 32, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 67, in route
                                                execute(_get_nav_handler(root_handler), pathitems[1:], g.REQUEST_PARAMS)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/__init__.py", line 27, in execute
                                                executor(pathitems=pathitems)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 56, in root
                                                self.profiles()
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 62, in profiles
                                                api.update_profiles_data()
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/api/shakti.py", line 73, in update_profiles_data
                                                parse_profiles(profiles_data)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 266, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/api/website.py", line 120, in parse_profiles
                                                raise InvalidProfilesError
                                            InvalidProfilesError
```

#### Steps to reproduce the behavior
1. Open the Netflix plugin

#### Other information
In order to be able to use the Netflix plugin again, I did a backup of `~/.kodi/userdata/addon_data/plugin.video.netflix` then started with an empty `addon_data/plugin.video.netflix` directory. After entering my email + password and rebooting the error was gone but all my read status were gone too.

Is there a way to get back my read status from my backup?

**Comment by CastagnaIT** [comment]
"read status" do you mean watched status of videos?
watched status are stored in Kodi not in the nf addon

The log must be complete and not modified in any way,
follow the rules to get the log or i do not provide help

**Comment by ccope** [comment]
I am also experiencing this, and spent some time trying to figure out the problem in the code. I got a dump of the profile data in my log output, which looks valid. The error seems to be happening because an `OrderedDict` is being passed to `g.LOCAL_DB.set_profile_config`, and the `common.convert_to_string` function doesn't know how to handle `OrderedDIct`. This is a chunk of profiles_list after running `resolve_refs`:

```
# print(list(profiles_list.items())[0])
(u'<redacted GUID>',
 OrderedDict([(u'avatar',
               [u'avatars', u'nf', u'icon29', u'images', u'byWidth', u'320']),
              (u'summary',
               OrderedDict([(u'isPinLocked', False),
                            (u'maturityLevel', u'ADULTS'),
                            (u'showOnRamp', False),
                            (u'language', u'en-US'),
                            (u'isDefaultKidsProfile', False),
                            (u'isAccountOwner', True),
                            (u'isKids', False),
                            (u'avatarName', u'icon29'),
                            (u'experience', u'standard'),
                            (u'maturityStrings',
                             OrderedDict([(u'labels', [u'NC-17']),
                                          (u'isHighest', True),
                                          (u'isLowest', False)])),
                            (u'$type', u'leaf'),
                            (u'profileName', u'Cameron'),
                            (u'guid', u'<redacted GUID)]))]))
```

**Comment by CastagnaIT** [comment]
Try Install daily build

**Comment by ccope** [comment]
I confirmed that the change to convert_to_string worked.

**Comment by lozbrown** [comment]
@CastagnaIT Could you point me at a link for the daily build? I'm seeing the same issue as above.

**Comment by CastagnaIT** [comment]
New version released
