### ISSUE TITLE
Unicode error. Unable to do any operation with Netflix addon.

### ISSUE THREAD

**Issue by pckeller29** [CastagnaIT/plugin.video.netflix#436]
Hi
I'm using:
Official Libreelec  9.0.2
Kodi 18.2
Architecture: RPi2.arm
Netflix addon: 0.16.2
Repository: Castagnait Repository 1.0.0
Regional settings: French

Whatever operation I try with the Netflix addon, I got a "Netflix Error, please check the logs".
This include, of course, starting Netflix from the extension page, starting any show from the favorites page, any action from the Settings page of the Netflix addon like, for example, Purge cache, Reinit ESN, Purge Media Library...

I activated kodi log files and set Netflix addon log to verbose.
Here is what I have:

`2020-01-16 11:07:08.676 T:1937203216   DEBUG: HandleKey: return (0xf00d) pressed, action is Select
2020-01-16 11:07:08.677 T:1937203216   DEBUG: Activating window ID: 10025
2020-01-16 11:07:09.004 T:1937203216   DEBUG: ------ Window Deinit (Home.xml) ------
2020-01-16 11:07:09.004 T:1937203216   DEBUG: FreeVisualisation() done
2020-01-16 11:07:09.027 T:1937203216   DEBUG: ------ Window Init (MyVideoNav.xml) ------
2020-01-16 11:07:09.043 T:1937203216   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-01-16 11:07:09.097 T:1937203216   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.netflix/)
2020-01-16 11:07:09.097 T:1937203216   DEBUG:   ParentPath = [plugin://plugin.video.netflix/]
2020-01-16 11:07:09.101 T:1790935920   DEBUG: Thread waiting start, auto delete: false
2020-01-16 11:07:09.120 T:1555448688   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.netflix] took 23 ms
2020-01-16 11:07:09.122 T:1790935920   DEBUG: StartScript - calling plugin Netflix('plugin://plugin.video.netflix/','2','','resume:false')
2020-01-16 11:07:09.122 T:1400931184   DEBUG: Thread LanguageInvoker start, auto delete: false
2020-01-16 11:07:09.123 T:1400931184    INFO: initializing python engine.
2020-01-16 11:07:09.123 T:1400931184   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.video.netflix/addon.py): start processing
2020-01-16 11:07:09.164 T:1400931184   DEBUG: -->Python Interpreter Initialized<--
2020-01-16 11:07:09.164 T:1400931184   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.video.netflix/addon.py): the source file to load is "/storage/.kodi/addons/plugin.video.netflix/addon.py"
2020-01-16 11:07:09.166 T:1400931184   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.video.netflix/addon.py): setting the Python path to /storage/.kodi/addons/plugin.video.netflix:/storage/.kodi/addons/script.module.addon.signals/lib:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.future/libs:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.inputstreamhelper/lib:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/share/kodi/addons/script.module.pycryptodome/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
2020-01-16 11:07:09.166 T:1400931184   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.video.netflix/addon.py): entering source directory /storage/.kodi/addons/plugin.video.netflix
2020-01-16 11:07:09.166 T:1400931184   DEBUG: CPythonInvoker(19, /storage/.kodi/addons/plugin.video.netflix/addon.py): instantiating addon using automatically obtained id of "plugin.video.netflix" dependent on version 2.26.0 of the xbmc.python api
2020-01-16 11:07:09.201 T:1937203216   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-01-16 11:07:09.387 T:1400931184   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
2020-01-16 11:07:09.387 T:1400931184   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
2020-01-16 11:07:09.394 T:1400931184   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
2020-01-16 11:07:09.411 T:1400931184    INFO: [plugin.video.netflix (2)] Debug logging level is Verbose
2020-01-16 11:07:09.412 T:1400931184   DEBUG: [plugin.video.netflix (2)] Trying connection to the database nf_local.sqlite3
2020-01-16 11:07:09.413 T:1400931184   DEBUG: [plugin.video.netflix (2)] Database connection nf_local.sqlite3 was successful (SQLite ver. 3.26.0)
2020-01-16 11:07:09.557 T:1400931184   DEBUG: [plugin.video.netflix (2)] Trying connection to the MySQL database netflix_addon
2020-01-16 11:07:09.601 T:1400931184   DEBUG: [plugin.video.netflix (2)] MySQL database connection was successful (MySQL server ver. 5.6.30-1~bpo8+1)
2020-01-16 11:07:09.607 T:1400931184   DEBUG: [plugin.video.netflix (2)] Executing JSON-RPC: {"params": {"properties": ["thumbnail", "lockmode"]}, "jsonrpc": "2.0", "method": "Profiles.GetCurrentProfile", "id": 1}
2020-01-16 11:07:09.608 T:1400931184    INFO: [plugin.video.netflix (2)] Debug logging level is Verbose
2020-01-16 11:07:09.608 T:1400931184    INFO: [plugin.video.netflix (2)] Started (Version 0.16.2)
2020-01-16 11:07:09.609 T:1400931184    INFO: [plugin.video.netflix (2)] URL is ParseResult(scheme='plugin', netloc='plugin.video.netflix', path='/', params='', query='', fragment='')
2020-01-16 11:07:09.609 T:1400931184   DEBUG: [plugin.video.netflix (2)] Executing JSON-RPC: {"params": {"properties": ["thumbnail", "lockmode"]}, "jsonrpc": "2.0", "method": "Profiles.GetCurrentProfile", "id": 1}
2020-01-16 11:07:09.642 T:1400931184   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 25: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/addon.py", line 15, in <module>
                                                run(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 154, in run
                                                if window_cls.getProperty(prop_nf_service_status) != 'running':
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 25: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-01-16 11:07:09.642 T:1400931184   DEBUG: onExecutionDone(19, /storage/.kodi/addons/plugin.video.netflix/addon.py)
2020-01-16 11:07:09.755 T:1937203216   DEBUG: ------ Window Init (DialogNotification.xml) ------
2020-01-16 11:07:09.894 T:1400931184    INFO: Python interpreter stopped
2020-01-16 11:07:09.894 T:1400931184   DEBUG: Thread LanguageInvoker 1400931184 terminating
2020-01-16 11:07:09.912 T:1790935920   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
2020-01-16 11:07:09.912 T:1790935920   DEBUG: Thread waiting 1790935920 terminating
2020-01-16 11:07:09.912 T:1937203216   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-01-16 11:07:09.914 T:1937203216   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
2020-01-16 11:07:09.914 T:1937203216   DEBUG: CGUIMediaWindow::GetDirectory ()
2020-01-16 11:07:09.915 T:1937203216   DEBUG:   ParentPath = [plugin://plugin.video.netflix/]
2020-01-16 11:07:09.924 T:1790935920   DEBUG: Thread waiting start, auto delete: false
2020-01-16 11:07:09.928 T:1790935920   DEBUG: Thread waiting 1790935920 terminating
2020-01-16 11:07:09.956 T:1790935920   DEBUG: Thread BackgroundLoader start, auto delete: false
2020-01-16 11:07:09.974 T:1790935920   DEBUG: Thread BackgroundLoader 1790935920 terminating
2020-01-16 11:07:15.371 T:1937203216   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
2020-01-16 11:07:15.453 T:1639867248  NOTICE: script.tv.show.next.aired: ### starting data update
2020-01-16 11:07:15.453 T:1639867248  NOTICE: script.tv.show.next.aired: ### grabbing a new country mapping list
2020-01-16 11:07:16.785 T:1639867248   DEBUG: script.tv.show.next.aired: ### search language = "en"
2020-01-16 11:07:16.786 T:1639867248   DEBUG: script.tv.show.next.aired: ### Update period: week (4169 mins)
2020-01-16 11:07:17.037 T:1639867248   ERROR: script.tv.show.next.aired: ### ERROR retreiving updates from thetvdb.com: File is not a zip file
2020-01-16 11:07:17.120 T:1639867248  NOTICE: script.tv.show.next.aired: ### data update finished
`
This log file is also available here:
https://pastebin.com/68BSkhJw

I tried a lot of things but completely dry now. This include totally removed the addon, the repository, removed the directories...
I also switched to english, set the skin to the default one, no luck.
Any help would be greatly appreciated. I could of course reinstall my Libreelec but I'd like to figure out what's happening, in case this comes again or someone else is having the same issue.
Thanx

**Comment by CastagnaIT** [comment]
Hi,
please install this test and let me know if is resolved
[plugin.video.netflix_0.16.2_20200116_test1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4071295/plugin.video.netflix_0.16.2_20200116_test1.zip)

**Comment by CastagnaIT** [comment]
Here:
[plugin.video.netflix_0.16.2_20200116_test2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4071997/plugin.video.netflix_0.16.2_20200116_test2.zip)
let me know

**Comment by CastagnaIT** [comment]
new version released

**Comment by pckeller29** [comment]
Oh sorry, didn't get any notification. I will try it out asap and let you know. Thanx.

**Comment by pckeller29** [comment]
I checked. So yes, the problem has been solved but I still can't use this addon. Actually, there is an "é" e with acute in my Netflix profile name and I guess this originally caused the error mentionned in this issue.
The problem I hit now is that my profile name is containing the string "acute" in it and, of course, nothing appears in the addon main menu, it's totally empty.
`2020-01-20 20:18:05.352 T:1471509360   DEBUG: StartScript - calling plugin Netflix('plugin://plugin.video.netflix/','1','','resume:false')
2020-01-20 20:18:05.353 T:1471509360   DEBUG: GetLanguageInvoker - Reusing LanguageInvokerThread 17 for script /storage/.kodi/addons/plugin.video.netflix/addon.py
2020-01-20 20:18:05.353 T:1456874352    INFO: initializing python engine.
2020-01-20 20:18:05.353 T:1456874352   DEBUG: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.netflix/addon.py): start processing
2020-01-20 20:18:05.353 T:1456874352   DEBUG: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.netflix/addon.py): entering source directory /storage/.kodi/addons/plugin.video.netflix
2020-01-20 20:18:05.353 T:1456874352   DEBUG: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.netflix/addon.py): instantiating addon using automatically obtained id of "plugin.video.netflix" dependent on version 2.26.0 of the xbmc.python api
2020-01-20 20:18:05.360 T:1456874352   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
2020-01-20 20:18:05.360 T:1456874352   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
2020-01-20 20:18:05.368 T:1456874352   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
2020-01-20 20:18:05.377 T:1456874352    INFO: [plugin.video.netflix (1)] Debug logging level is Verbose
2020-01-20 20:18:05.377 T:1456874352    INFO: [plugin.video.netflix (1)] Started (Version 0.16.3)
2020-01-20 20:18:05.377 T:1456874352    INFO: [plugin.video.netflix (1)] URL is ParseResult(scheme='plugin', netloc='plugin.video.netflix', path='/', params='', query='', fragment='')
2020-01-20 20:18:05.436 T:1937088528   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-01-20 20:18:05.543 T:1456874352   DEBUG: [plugin.video.netflix (1)] Routing navigation request
2020-01-20 20:18:05.543 T:1456874352   DEBUG: [plugin.video.netflix (1)] Initializing directory builder: {}
2020-01-20 20:18:05.543 T:1456874352   DEBUG: [plugin.video.netflix (1)] Invoking action executor root
2020-01-20 20:18:05.544 T:1456874352    INFO: [plugin.video.netflix (1)] Performing auto-login for selected profile QMW3GVJDONHLZFQ74QFROOEZ3U
2020-01-20 20:18:05.544 T:1456874352   DEBUG: [plugin.video.netflix (1)] Handling AddonSignals IPC call to activate_profile
2020-01-20 20:18:05.544 T:1937085296   DEBUG: CAnnouncementManager - Announcement: activate_profile from plugin.video.netflix.SIGNAL
2020-01-20 20:18:05.545 T:1937085296   DEBUG: GOT ANNOUNCEMENT, type: 512, from plugin.video.netflix.SIGNAL, message activate_profile
2020-01-20 20:18:05.573 T:1648259952   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender plugin.video.netflix.SIGNAL - method: Other.activate_profile  - data: ["IlFNVzNHVkpET05ITFpGUTc0UUZST09FWjNVIg=="]
2020-01-20 20:18:05.632 T:1681830768   DEBUG: Skin Helper Service --> Kodi_Monitor: sender plugin.video.netflix.SIGNAL - method: Other.activate_profile  - data: ["IlFNVzNHVkpET05ITFpGUTc0UUZST09FWjNVIg=="]
2020-01-20 20:18:05.703 T:1614689136    INFO: [plugin.video.netflix (0)] Activating profile QMW3GVJDONHLZFQ74QFROOEZ3U
2020-01-20 20:18:05.705 T:1614689136   DEBUG: [plugin.video.netflix (0)] Profile QMW3GVJDONHLZFQ74QFROOEZ3U is already active
2020-01-20 20:18:05.706 T:1937085296   DEBUG: CAnnouncementManager - Announcement: _return.activate_profile from plugin.video.netflix.SIGNAL
2020-01-20 20:18:05.706 T:1937085296   DEBUG: GOT ANNOUNCEMENT, type: 512, from plugin.video.netflix.SIGNAL, message _return.activate_profile
2020-01-20 20:18:05.733 T:1681830768   DEBUG: Skin Helper Service --> Kodi_Monitor: sender plugin.video.netflix.SIGNAL - method: Other._return.activate_profile  - data: ["ZmFsc2U="]
2020-01-20 20:18:05.745 T:1456874352   DEBUG: [plugin.video.netflix (1)] Showing root video lists
2020-01-20 20:18:05.747 T:1471509360   DEBUG: Thread waiting 1471509360 terminating
2020-01-20 20:18:05.747 T:1937088528   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-01-20 20:18:05.756 T:1471509360   DEBUG: Thread BackgroundLoader start, auto delete: false
2020-01-20 20:18:05.775 T:1471509360   DEBUG: Thread BackgroundLoader 1471509360 terminating
2020-01-20 20:18:05.802 T:1648259952   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender plugin.video.netflix.SIGNAL - method: Other._return.activate_profile  - data: ["ZmFsc2U="]
2020-01-20 20:18:05.863 T:1456874352   DEBUG: [plugin.video.netflix (1)] Released lock on cache_common
2020-01-20 20:18:05.863 T:1456874352   DEBUG: [plugin.video.netflix (1)] Cache commit successful
2020-01-20 20:18:05.863 T:1456874352    INFO: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
`

**Comment by pckeller29** [comment]
Better log output:
https://pastebin.com/UCjneyhr

**Comment by CastagnaIT** [comment]
this is not useful i need a full log

**Comment by CastagnaIT** [comment]
Try this and le me know
[plugin.video.netflix_0.16.3_20200121_test2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4091088/plugin.video.netflix_0.16.3_20200121_test2.zip)

**Comment by pckeller29** [comment]
Perfect, it works!
Thank you very much.

**Comment by shablamy** [comment]
@CastagnaIT I have the same issue.

Tried installing from the repo and directly from zip.

Device: Minix U9-H
CoreELEC (official): 9.2.2
Kodi 18.6

My workaround is to switch off InputStreamHelper, but then I get 1080P max only as its on software decoder.

https://pastebin.com/7y487npn

Please help how I can get past the Widevine CDM decode error: "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 29: ordinal not in range(128)".

Seems like my download completes successfully and then the extract fails with the error above..

CoreELEC:~ # ls -lah /storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp
total 974M
drwxr-xr-x    3 root     root        1.0K May  3 16:50 .
drwxr-xr-x    4 root     root        1.0K May  3 15:48 ..
-rw-r--r--    1 root     root        4.1M May  3 15:48 4.10.1582.2-mac-x64.zip
-rw-r--r--    1 root     root      970.1M May  3 15:54 chromeos_12739.111.1_bob_recovery_stable-channel_mp.bin.zip
drwxr-xr-x    2 root     root        1.0K May  3 16:07 mnt
CoreELEC:~ #

Tested and verified:
Profiles work
Atmos works

Not working:
4k not working

Please help

**Comment by CastagnaIT** [comment]
if you have problem with inputstreamhelper report to inputstreamhelper addon not here

**Comment by farkaslory** [comment]
Hi!

I got error with UnicodeEncodeError. Here is the log:
`2020-05-20 15:29:22.838 T:2799686512   ERROR: [plugin.video.netflix (0)] IPC callback raised exception: 'ascii' codec can't encode character u'\xe9' in position 3: ordinal not in range(128)
2020-05-20 15:29:22.843 T:2799686512   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 173, in make_return_call
                                                result = call(instance, func, data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 194, in call
                                                return func(instance, **data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/directorybuilder/dir_builder.py", line 73, in get_seasons
                                                return build_season_listing(season_list, tvshowid, pathitems)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/directorybuilder/dir_builder_items.py", line 123, in build_season_listing
                                                in iteritems(season_list.seasons)]
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/directorybuilder/dir_builder_items.py", line 137, in _create_season_item
                                                add_info_dict_item(dict_item, seasonid, season, season_list.data, False, common_data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/kodi/infolabels.py", line 66, in add_info_dict_item
                                                infos, quality_infos = get_info(videoid, item, raw_data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/kodi/infolabels.py", line 59, in get_info
                                                infos, quality_infos = parse_info(videoid, item, raw_data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/kodi/infolabels.py", line 146, in parse_info
                                                infos.update(_parse_atomic_infos(item))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/kodi/infolabels.py", line 161, in _parse_atomic_infos
                                                infos[target] = _transform_value(target, value)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/kodi/infolabels.py", line 168, in _transform_value
                                                if target in paths.INFO_TRANSFORMATIONS
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/api/paths.py", line 118, in <lambda>
                                                'Season': lambda s_value: ''.join([n for n in str(s_value) if n.isdigit(
)]),  # isdigit is needed for shortName key
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 3: ordinal not in range(128)`

I think the main problem is that the episode list in Netflix is in hungarian (it is common in hungary that the title is translated) and there are lot of unicode character in hungary.

I think a  ".encode('utf-8')" is missing after .join(...)
