### ISSUE TITLE
 "Can't see the title instantly right now" 

### ISSUE THREAD

**Issue by Renetrox** [CastagnaIT/plugin.video.netflix#447]
## Bug report
"Can't see the title instantly right now"
Every time I want to see a content I get this message. On the flaw, Netflix gives the following guidance: https://help.netflix.com/en/node/109329. What can I do to fix this in the addon? Operating system: Raspbian 9.
device: Raspberry pi 3b.
Nothing specific is performed for the failure to occur, directly the message appears when you try to play a video.

**Comment by Renetrox** [comment]
@CastagnaIT I don't know if that information is enough, I didn't put myself properly on the case before.

**Comment by CastagnaIT** [comment]
- Report not compiled in right way
- The rules for get the log file have not been followed

**Comment by Renetrox** [comment]
ERROR: [plugin.video.netflix (0)] Full MSL error information:
2020-01-24 11:08:48.116 T:875541216   ERROR: [plugin.video.netflix (0)] {"from": "nq_cadmium_pbo_licenses@1.43.1/pbo-client@1.43.0", "version": 2, "serverTime": 1579874927966, "id": 15798749275864, "result": [{"errorParams": {"sessionId": "BC2AAC5BF8061941D3A8F306AB08CF08"}, "error": {"code": "DEVICE_EOL_FINAL", "bladeRunnerMessage": "license/pbl-3078: DeviceEolFinal (E2-BQFRAAELEIJ-jyMfGElEGzB54vWLv_OAwxy0rMuaW0Q2o_H_MYFkyaD39_28es0etNHwI0kTy73sovUWtnZgOdIpoXO16mZsHUsjD-6Mpm2qJfG0ooTfEXT3xnGTSfl3N0q8r1Pp2Rkn2khmJIpljj5oPSa_7xGxDmlold1pE8lhg4_-cwos9cn6_0hGQDeJaI8wu7SoNOb3NDSBx25hkvGUBDFPK5os9l_YmEgDbajGbnXMR3U9QYwS7SjGHhmxgSewkK_i9ix2438XDNXQJhhzMc7ZKXWY6wjk_w..) (nq_cadmium_pbo_licenses@1.43.1/pbo-client@1.43.0)", "errorNccpCode": 0, "pboc": true, "detail": "license/pbl-3078: DeviceEolFinal (E2-BQFRAAELEIJ-jyMfGElEGzB54vWLv_OAwxy0rMuaW0Q2o_H_MYFkyaD39_28es0etNHwI0kTy73sovUWtnZgOdIpoXO16mZsHUsjD-6Mpm2qJfG0ooTfEXT3xnGTSfl3N0q8r1Pp2Rkn2khmJIpljj5oPSa_7xGxDmlold1pE8lhg4_-cwos9cn6_0hGQDeJaI8wu7SoNOb3NDSBx25hkvGUBDFPK5os9l_YmEgDbajGbnXMR3U9QYwS7SjGHhmxgSewkK_i9ix2438XDNXQJhhzMc7ZKXWY6wjk_w..) (nq_cadmium_pbo_licenses@1.43.1/pbo-client@1.43.0)", "errorExternalCode": 0, "errorDisplayMessage": "Este t\u00edtulo no se encuentra disponible para ver al instante. Prueba con otro t\u00edtulo.", "nccpError": {}, "bladeRunnerCode": "3078", "errorActionId": 3, "errorSubCode": 0, "errorReasonCode": 0, "display": "Este t\u00edtulo no se encuentra disponible para ver al instante. Prueba con otro t\u00edtulo."}}]}
2020-01-24 11:08:59.564 T:875541216   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/http_server.py", line 47, in do_POST
                                                challenge=data[0], sid=base64.standard_b64decode(data[1]).decode('utf-8'))
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 51, in error_catching_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 266, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 278, in get_license
                                                response = self._chunked_request(ENDPOINTS['license'], license_request_data, g.get_esn())
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 266, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 293, in _chunked_request
                                                mt_validity['renewable'] if mt_validity else None)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 266, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 337, in _process_chunked_response
                                                return _raise_if_error(decrypted_response)
                                              File "/home/pi/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 361, in _raise_if_error
                                                raise MSLError(_get_error_details(decoded_response))
                                            MSLError: Este título no se encuentra disponible para ver al instante. Prueba con otro título.

**Comment by CastagnaIT** [comment]
The log is not good, and must not be pasted in a message

I suggest you to open a new issue by **following the Issue rules**
otherwise it will not be accepted
