### ISSUE TITLE
New Profile auto-selection doesn't handle special characters

### ISSUE THREAD

**Issue by michaelarnauts** [CastagnaIT/plugin.video.netflix#531]
#### Your Environment
- Netflix add-on version: 1.1.0
- Operating system version/name: Ubuntu 19.10 with Kodi 18.6

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
When I mark my user as auto-selection, I get the below stacktrace. This is related to the encoding of my profile name (Michaël). This only seems to be a problem for the notification, since the actual profile will be correctly autoselected.

#### Steps to reproduce the behavior

1. Mark a profile with a special character as auto selection.
2.
3.

#### Possible fix

Handle encoding of special characters.

### Debug log
```
2020-03-21 13:17:09.975 T:140312006649600   ERROR: [plugin.video.netflix (-1)] Traceback (most recent call last):
                                              File "/home/michael/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 182, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/home/michael/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 33, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/michael/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 68, in route
                                                execute(_get_nav_handler(root_handler), pathitems[1:], g.REQUEST_PARAMS)
                                              File "/home/michael/.kodi/addons/plugin.video.netflix/resources/lib/navigation/__init__.py", line 27, in execute
                                                executor(pathitems=pathitems)
                                              File "/home/michael/.kodi/addons/plugin.video.netflix/resources/lib/navigation/actions.py", line 39, in autoselect_profile_set
                                                ui.show_notification(common.get_local_string(30058).format(self.params['profile_name']))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)
```

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
Thanks fixed,
you can download the update from the Daily Build link in Readme

**Comment by michaelarnauts** [comment]
Thanks!
