### ISSUE TITLE
Exception: Addon Signals Call timeout

### ISSUE THREAD

**Issue by abbaskip** [CastagnaIT/plugin.video.netflix#549]
I'm suddenly getting the above error when trying to launch the addon.

Netflix version is 1.1.1 and I'm on Windows 10 and Kodi 18.6

Log when launching Netflix:
`2020-04-04 16:53:54.446 T:36540   ERROR: [plugin.video.netflix (378)] Traceback (most recent call last):
                                              File "C:\Users\Abba\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 182, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "C:\Users\Abba\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 33, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "C:\Users\Abba\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 68, in route
                                                execute(_get_nav_handler(root_handler), pathitems[1:], g.REQUEST_PARAMS)
                                              File "C:\Users\Abba\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\navigation\__init__.py", line 27, in execute
                                                executor(pathitems=pathitems)
                                              File "C:\Users\Abba\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\navigation\directory.py", line 49, in root
                                                self.profiles()
                                              File "C:\Users\Abba\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\navigation\directory.py", line 78, in profiles
                                                api.update_profiles_data()
                                              File "C:\Users\Abba\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\api\shakti.py", line 73, in update_profiles_data
                                                ['lolomo']])
                                              File "C:\Users\Abba\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\logging.py", line 133, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "C:\Users\Abba\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\ipc.py", line 86, in make_call
                                                return make_addonsignals_call(callname, data)
                                              File "C:\Users\Abba\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\ipc.py", line 126, in make_addonsignals_call
                                                raise Exception('Addon Signals call timeout')
                                            Exception: Addon Signals call timeout
2020-04-04 16:53:54.447 T:23244   DEBUG: ------ Window Init (DialogConfirm.xml) ------`

**Comment by npmstart-pray** [comment]
Same, but the error dialog pointed to a plugin setting that could be changed; I did, got a day of use, and now anything I try to play won’t, but it tries and fails with a dialog saying something about a connection timeout.

Log to follow, (typing from my mobile) but RasPi4, kodi 18.6 on xbian with v1.1.1 of the addon. I even tried to reinstall WideVine, but no change.

**Comment by CastagnaIT** [comment]
try read wiki FAQ

**Comment by npmstart-pray** [comment]
Same result.  see previous post for attached log.  If you want the whole thing, I'll be happy to provide it

**Comment by huyld** [comment]
I've got similar error and log as @abbaskip (`Addon Signals call timeout` exception). Following the instruction in [Wiki FAQ](https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ#the-error---addon-signals-call-timeout) did resolve the issue.
I'm not sure about @npmstart-pray 's case though.

**Comment by CastagnaIT** [comment]
no "Connection aborted" are problems with network

**Comment by CastagnaIT** [comment]
closed due to missing log and inactivity
