### ISSUE TITLE
Problem netflix addon rpi 3 b+

### ISSUE THREAD

**Issue by Mintux92** [CastagnaIT/plugin.video.netflix#552]
Good morning,
I am installing neflix on libreelec. Netflix installs without problems, when I try to log in it asks me to install the various addons but when it tries chrome os at some point it stops and in the logs I find what I attach. How could I solve it?

KODI 18.2
ARCHITECTURE: RPi 3 B+
Repository: Castagnait Repository 1.1.1

log:
2020-04-05 20:49:55.974 T:1545548656   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 182, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 33, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 57, in route
                                                play(videoid=pathitems[1:])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/videoid.py", line 294, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 133, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 72, in play
                                                list_item = get_inputstream_listitem(videoid)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 144, in get_inputstream_listitem
                                                if not is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 1053, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 1008, in _check_drm
                                                return self.install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 776, in install_widevine
                                                return self._install_widevine_arm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 703, in _install_widevine_arm
                                                downloaded = self._http_download(url, message=localize(30022), checksum=arm_device['sha1'], hash_alg='sha1', dl_size=int(arm_device['zipfilesize']))  # Downloading the recovery image
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 414, in _http_download
                                                chunk = req.read(chunk_size)
                                              File "/usr/lib/python2.7/socket.py", line 384, in read
                                              File "/usr/lib/python2.7/httplib.py", line 597, in read
                                              File "/usr/lib/python2.7/socket.py", line 384, in read
                                              File "/usr/lib/python2.7/ssl.py", line 772, in recv
                                              File "/usr/lib/python2.7/ssl.py", line 659, in read
                                            SSLError: ('The read operation timed out',)
2020-04-05 20:50:12.348 T:1936587152   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.netflix/play/movie/81033429/?profile_guid=NPDMLGKCNBEABNDKVTJBXE6DSE]

**Comment by CastagnaIT** [comment]
is clear the error not come from nf addon but inputstreamhelper
