### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by major-mayer** [CastagnaIT/plugin.video.netflix#554]
#### Your Environment
- Netflix add-on version: 
- Operating system version/name: CoreELEC latest nightly
- Device model:  S905X3 SOC (X96 Max Plus)

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
Hi, since a few days I often get the error "IndexError: list index out of range" while I don't even use the (really great) Netflix app.
When I am activly using the Netflix app (in foreground) i don't get any errors and everything is working pretty well.
It's not a real problem, just annoying.
One thing that could be helpful is, that i placed a Netflix widget on my homescreen, so maybe this triggers the error.

#### Expected behavior
The error should not happen

#### Steps to reproduce the behavior
1. Install the app
2. Just start Kodi normally, the exception happens at some point when Netflix is running in the background

### Debug log
```
2020-04-06 00:08:25.079 T:2968376192   ERROR: [plugin.video.netflix (11)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 182, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 33, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 68, in route
                                                execute(_get_nav_handler(root_handler), pathitems[1:], g.REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/__init__.py", line 27, in execute
                                                executor(pathitems=pathitems)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 133, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 97, in video_list
                                                list_id = api.list_id_for_type(menu_data['lolomo_contexts'][0])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/cache.py", line 108, in wrapper
                                                output = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/api/shakti.py", line 202, in list_id_for_type
                                                list_id = list(root_lists().lists_by_context(list_type))[0][0]
                                            IndexError: list index out of range
```
a few lines later...
```
2020-04-06 00:08:28.306 T:3441341312   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/directory/video_list/continueWatching/continueWatching/?genre_id=None&reload=20200405220738
```

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source 
* [x] I'm using the CastagnalIT repo

**Comment by CastagnaIT** [comment]
Before is needed to remove all the widgets, and check if no error occours again

widgets can perform bad unexpected access to addon, and are not really supported by this addon

**Comment by major-mayer** [comment]
All right, i will disable it and report if the error still happens after that

**Comment by major-mayer** [comment]
Yeah indeed it seems to be the widgets.
Can be closed
