### ISSUE TITLE
Widevine extract issue

### ISSUE THREAD

**Issue by fesarlis** [CastagnaIT/plugin.video.netflix#611]
I am experimenting with a S905W TV box and reinstalling Kodi and/or this plugin frequently. Over the last 24 hours I'm facing a strange issue not happening before. It occurs at first play of a video, when Widevine needs to be installed. It fails. I am guessing it has something to do with the fact that there are profiles with Greek characters on Netflix. But this was not happening before, and I have not changed anything regarding the profiles.
Here is the error produced:

2020-05-01 07:46:04.420 T:3664741232   ERROR: [plugin.video.netflix (2)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 182, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 33, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 57, in route
                                                play(videoid=pathitems[1:])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/videoid.py", line 294, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 133, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 72, in play
                                                list_item = get_inputstream_listitem(videoid)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 144, in get_inputstream_listitem
                                                if not is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 362, in _check_drm
                                                return self.install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 33, in clean_before_after
                                                result = func(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 223, in install_widevine
                                                result = install_widevine_arm(backup_path())
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 240, in install_widevine_arm
                                                extract_widevine_from_img(os.path.join(backup_path, arm_device['version']))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 253, in extract_widevine_from_img
                                                for root, _, files in os.walk(mnt_path()):
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 286, in walk
                                              File "/usr/lib/python2.7/posixpath.py", line 73, in join
                                            **UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 29: ordinal not in range(128)**

**Comment by CastagnaIT** [comment]
`"/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py"`
it is clearly written that the error does not come from this add-on

**Comment by fesarlis** [comment]
Yes but the above addon was installed by yours. It is a dependency.

**Comment by CastagnaIT** [comment]
if the dependencies don't work, it's not a problem that needs to be solved here
Nothing i can do for you

**Comment by fesarlis** [comment]
I undestand. Thank you for your time.
