### ISSUE TITLE
Error "Addon signals call timeouts"

### ISSUE THREAD

**Issue by pardokan** [CastagnaIT/plugin.video.netflix#612]
#### Your Environment
- Netflix add-on version: 1.2.0
- Operating system version/name: Libreelec 9.2.1
- Device model:  Raspberry Pi 2.0

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ x] Raspberry-Pi
* [ ] Windows

### Describe the bug
I have problem with open media in plugin, login to account-OK. Error appears while choosing films or series and another choice 

#### Actual behavior

video content cannot be played

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log
"2020-04-28 19:57:16.175 T:1235153792 ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 207, in run
route([part for part in g.PATH.split('/') if part])
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 38, in lazy_login_wrapper
return func(*args, **kwargs)
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 72, in route
_execute(nav_handler, pathitems[1:], g.REQUEST_PARAMS)
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 100, in _execute
executor(pathitems=pathitems)
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
return func(*args, **kwargs)
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_utils.py", line 34, in set_custom_viewmode
override_partial_setting_id = func(*args, **kwargs)
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 102, in home
list_data, extra_data = common.make_call('get_mainmenu') # pylint: disable=unused-variable
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
return func(*args, **kwargs)
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 87, in make_call
return make_addonsignals_call(callname, data)
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 152, in make_addonsignals_call
raise Exception('Addon Signals call timeout')
Exception: Addon Signals call timeout
2020-04-28 19:57:57.180 T:1606296448 NOTICE: ES: Client from ::ffff:192.168.50.113 timed out
2020-04-28 19:57:57.887 T:1907676032 NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
2020-04-28 19:57:58.153 T:1277117312 ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/directory/home/?switch_profile_guid=6ADDHISE6RCCTMZNEM27MIT72Y
2020-04-28 19:57:58.172 T:1936769040 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/directory/home/?switch_profile_guid=6ADDHISE6RCCTMZNEM27MIT72Y) failed"

#### Installation
* [x ] I'm using other Netflix Repo 
* [ ] I'm using a different source 

#### Screenshots
[]

**Comment by jakermx** [comment]
try enable IPC

**Comment by pardokan** [comment]
i check enable IPC and i have another bug: timeout t:imeout time

**Comment by jakermx** [comment]
I have RPi 2 B,3 B+ and 0W... obviously the 0Wdoes not have enough hw to handle encrypted videos, but the others do it ok
In my expertise,  could say that the USB Dongle as it does not have a  good antenna, its performance over WiFi is not good, if you can have Ethernet cable conection... try increasing the timeout on ipc.py file... there are about 5 ocurrences, I have set it to 60 secs

**Comment by pardokan** [comment]
Hey, I have internet on cable 600 MB-download to my raspberry. The problem appears after the first start, after turning off the error. The next entry allows you to start the movie or series correctly.

**Comment by jakermx** [comment]
Delay is not BW related, it is about the post-time after the request was made, sometimes it is about SD write speed, processor speed, another addons update, etc... what i meant is that what I have seen on my RPis is that the wirelessdongle doest not work as good as the internal wifi, try the mod I suggeste and post back your findings bro

**Comment by jakermx** [comment]
I also had that issue when browsing my list, when it had more than 100 titles

**Comment by pardokan** [comment]
Hello i'm reinstall Kodi on sd card and install Netflix and work great. Thanks for earlier information
