### ISSUE TITLE
Exception: HTTPError

### ISSUE THREAD

**Issue by razorxster** [CastagnaIT/plugin.video.netflix#647]
#### Your Environment
- Netflix add-on version: plugin.video.netflix_1.3.1_20200519_t16.zip, but same with 1.3.1 from repo
- Operating system version/name: OSMC 2020.03-1
- Device model:  RPI3 b+

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug
When is want to start the netlix app i receive an error: Exception HTTPError

#### Expected behavior
Netflix start

#### Actual behavior
Netflix cannot start

#### Steps to reproduce the behavior
Start netflix app

#### Possible fix
I checked, i have internet access and the netflix is working from an other device.

### Debug log
2020-05-19 23:33:16.619 T:1915647536   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-05-19 23:33:21.959 T:1669325536   ERROR: [plugin.video.netflix (0)] IPC callback raised exception: 500 Server Error: Internal Server Error for url: https://www.netflix.com/browse
2020-05-19 23:33:21.970 T:1669325536   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 178, in make_return_call
                                                result = call(instance, func, data)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 202, in call
                                                return func(instance)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_base.py", line 37, in ensure_login
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession.py", line 82, in fetch_initial_page
                                                response = self._get('browse')
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_requests.py", line 45, in _get
                                                **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_requests.py", line 55, in _request_call
                                                return self._request(method, endpoint, None, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_requests.py", line 92, in _request
                                                response.raise_for_status()
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 940, in raise_for_status
                                                raise HTTPError(http_error_msg, response=self)
                                            HTTPError: 500 Server Error: Internal Server Error for url: https://www.netflix.com/browse
2020-05-19 23:33:22.002 T:1443881696   ERROR: [plugin.video.netflix (4)] IPC call fetch_initial_page returned HTTPError: 500 Server Error: Internal Server Error for url: https://www.netflix.com/browse
2020-05-19 23:33:22.012 T:1443881696   ERROR: [plugin.video.netflix (4)] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 207, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 38, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 72, in route
                                                _execute(nav_handler, pathitems[1:], g.REQUEST_PARAMS)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 100, in _execute
                                                executor(pathitems=pathitems)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 59, in root
                                                common.make_call('fetch_initial_page')
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 87, in make_call
                                                return make_addonsignals_call(callname, data)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 155, in make_addonsignals_call
                                                _raise_for_error(callname, result)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 168, in _raise_for_error
                                                raise Exception(result['error'])
                                            Exception: HTTPError
2020-05-19 23:33:24.138 T:1581232864   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
2020-05-19 23:33:24.159 T:1915647536   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed

#### Installation
* [X] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
http error 500 is not an addon error is a netflix server problem
if still persists in next days the only thing you can try is settings>Logout and relogin
