### ISSUE TITLE
Netflix addon error: KeyError

### ISSUE THREAD

**Issue by orclex** [CastagnaIT/plugin.video.netflix#660]
### Describe the bug

Addon does not start anymore and gives a message with 

----
Netflix Add-on Error 
--
The add-on encoutered the following error:
Exception: KeyError

Error details have been written to the Kodi log file. If the error
message does not provide guidance on how to resolve the issue or 
you continue to receive this error, please report it on GitHub by 
following the Readme instructions.
----

In Kodi logfile I found:

2020-05-24 19:52:05.744 T:139660835669760   ERROR: [plugin.video.netflix (0)] IPC callback raised exception: u'lolomo'
2020-05-24 19:52:05.744 T:139660835669760   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 183, in make_return_call
                                                result = call(instance, func, data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 207, in call
                                                return func(instance)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_base.py", line 37, in ensure_login
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession.py", line 84, in fetch_initial_page
                                                api_data = self.website_extract_session_data(response, update_profiles=True)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession.py", line 267, in website_extract_session_data
                                                return website.extract_session_data(content, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 148, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/api/website.py", line 104, in extract_session_data
                                                lolomo_root = falcor_cache['lolomo']['value'][1]
                                            KeyError: u'lolomo'
2020-05-24 19:52:05.827 T:139659420763904   ERROR: [plugin.video.netflix (1)] IPC call fetch_initial_page returned KeyError: u'lolomo'
2020-05-24 19:52:05.828 T:139659420763904   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 207, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 38, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 72, in route
                                                _execute(nav_handler, pathitems[1:], g.REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 100, in _execute
                                                executor(pathitems=pathitems)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 59, in root
                                                common.make_call('fetch_initial_page')
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 148, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 87, in make_call
                                                return make_addonsignals_call(callname, data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 160, in make_addonsignals_call
                                                _raise_for_error(callname, result)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 173, in _raise_for_error
                                                raise Exception(result['error'])
                                            Exception: KeyError
2020-05-24 19:52:10.089 T:139659370407680   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
2020-05-24 19:52:10.105 T:139662369941632   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed

Until last week the addon was running without problems. I also tried downgrading to 1.3.0 and 1.3.1 but I always get the same error.

#### Your Environment
- Netflix add-on version: 1.3.2 
- Operating system version/name: LibreElec 9.2.2
- Device model:  x86/x64

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

#### Expected behavior
start Netflix add-on

#### Actual behavior
does not start

#### Steps to reproduce the behavior
I can reproduce it by just starting the Netflix add-on

### Debug log
The debug log can be found from this link:

https://paste.ubuntu.com/p/htNSpczmGb/

**Comment by thiagolamosa** [comment]
I'm having the same problem with a OSMC install on raspberry pi

**Comment by papaispicolo** [comment]
Same issue here !

**Comment by pbenitez** [comment]
with 1.4.2 is also happening.

**Comment by npmstart-pray** [comment]
V1.5.0 was released today.
