### ISSUE TITLE
Permanent pop-up with "KeyError: u'identifier'"

### ISSUE THREAD

**Issue by dagwieers** [CastagnaIT/plugin.video.netflix#664]
#### Your Environment
- Netflix add-on version: v1.3.2
- Operating system version/name: LibreELEC v9.2.1
- Device model: Raspberry Pi 3B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
We see a permanent pop-up showing:

> **Netflix:**
> KeyError: u'identifier'

And while at first I thought this was a cosmetic issue in Kodi not removing the pop-up, the debug log shows a repeating error continuously causing this.

We have seen this before but I never looked into it.

### Debug log
```
2020-05-25 22:52:00.877 T:1568650112   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_service.py", line 153, in _tick_and_wait_for_abort
                                                g.CACHE_MANAGEMENT.on_service_tick()
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/cache/cache_management.py", line 111, in on_service_tick
                                                self.delete_expired()
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/cache/cache_management.py", line 279, in delete_expired
                                                del bucket_content['identifier']
                                            KeyError: u'identifier'
2020-05-25 22:53:00.217 T:1714033536   ERROR: Previous line repeats 59 times.
```

#### Screenshots
![screenshot036](https://user-images.githubusercontent.com/388198/82842718-e4fbfc80-9eda-11ea-9a3d-55c7d9bd4a27.png)

**Comment by CastagnaIT** [comment]
oh thank you for investigating and fix
