### ISSUE TITLE
Cryptodome.Random missing, AddOn does not run.

### ISSUE THREAD

**Issue by Mebus** [CastagnaIT/plugin.video.netflix#669]
Hallo,

I am using the addon on OSMC with Kodi 18.6.

I installed pycryptodomex accoding to the wiki entry:

https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-install-the-addon

But I still get this error message:

```
2020-05-27 20:51:54.424 T:1602175712   ERROR: [plugin.video.netflix (0)] Background services do not start due to the following error
2020-05-27 20:51:54.886 T:1602175712   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_service.py", line 48, in init_servers
                                                from resources.lib.services.msl.http_server import MSLTCPServer
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/http_server.py", line 32, in <module>
                                                from .msl_handler import MSLHandler
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 25, in <module>
                                                from .msl_requests import MSLRequests
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_requests.py", line 22, in <module>
                                                from resources.lib.services.msl.msl_request_builder import MSLRequestBuilder
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_request_builder.py", line 33, in <module>
                                                from .default_crypto import DefaultMSLCrypto as MSLCrypto
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/default_crypto.py", line 24, in <module>
                                                from Cryptodome.Random import get_random_bytes
                                            ImportError: No module named Cryptodome.Random
2020-05-27 21:12:21.408 T:1767895776   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
2020-05-27 21:12:21.443 T:1915303472   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
2020-05-27 21:12:35.835 T:1915303472   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2020-05-27 21:13:23.557 T:1404039904   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
2020-05-27 21:13:23.608 T:1915303472   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
2020-05-27 21:17:36.094 T:1915303472   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
```

```
python3 -m Cryptodome.SelfTest
```

and

```
python -m Cryptodome.SelfTest
```

This works, too:

```
➜  python
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Cryptodome.Random
>>>
```

```
➜  python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Cryptodome.Random
>>>

```

This:

```
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from Cryptodome.Random import get_random_bytes 
```
works, too.

Can be run, so I suppose the module is there. Why is the Addon unable to find it?

Thanks!

Mebus

**Comment by Mebus** [comment]
After doing

```
pip install pycryptodome
```

and rebooting it worked.

Mebus
