### ISSUE TITLE
IPC call fetch_initial_page returned KeyError: u'lolomo'

### ISSUE THREAD

**Issue by dagwieers** [CastagnaIT/plugin.video.netflix#707]
## Bug report
Today we got another KeyError message when opening Netflix.

#### Your Environment
- Netflix add-on version: v1.4.1
- Operating system version/name: LibreELEC v9.2.3
- Device model:  Raspberry Pi 3B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug
When opening Netflix add-on we get this KeyError.

### Debug log
```
2020-06-19 20:56:34.858 T:1561310080   ERROR: [plugin.video.netflix (0)] Could not extract [u'models', u'truths', u'data', u'isLocoSupported']
2020-06-19 20:56:35.216 T:1561310080   ERROR: [plugin.video.netflix (0)] IPC callback raised exception: u'lolomo'
2020-06-19 20:56:35.225 T:1561310080   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 185, in make_return_call
                                                result = call(instance, func, data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 209, in call
                                                return func(instance)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_base.py", line 37, in ensure_login
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession.py", line 86, in fetch_initial_page
                                                api_data = self.website_extract_session_data(response, update_profiles=True)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession.py", line 275, in website_extract_session_data
                                                return website.extract_session_data(content, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/api/website.py", line 124, in extract_session_data
                                                lolomo_root = falcor_cache['lolomo']['value'][1]
                                            KeyError: u'lolomo'
2020-06-19 20:56:35.242 T:1206236032   ERROR: [plugin.video.netflix (1)] IPC call fetch_initial_page returned KeyError: u'lolomo'
2020-06-19 20:56:35.249 T:1206236032   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 207, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 38, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 72, in route
                                                _execute(nav_handler, pathitems[1:], g.REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 100, in _execute
                                                executor(pathitems=pathitems)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 59, in root
                                                common.make_call('fetch_initial_page')
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 89, in make_call
                                                return make_addonsignals_call(callname, data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 162, in make_addonsignals_call
                                                _raise_for_error(callname, result)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 175, in _raise_for_error
                                                raise Exception(result['error'])
                                            Exception: KeyError
```

**Comment by dagwieers** [comment]
Duplicate of #701

**Comment by dagwieers** [comment]
@CastagnaIT If the issue title would have been more specific, I would have identified it before opening the ticket. And probably just like other users ;-)
