### ISSUE TITLE
addon signals call time out

### ISSUE THREAD

**Issue by maxolon01** [CastagnaIT/plugin.video.netflix#711]
#### Your Environment
- Netflix add-on version:  1.5.0
- Operating system version/name:  win10
- Device model:   

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x ] Windows

### Describe the bug

 An error appears 'addon signals call time out'  on search or certain browsing of titles/ genres, problems in looking for a title. 
#### Expected behavior

show list of searched titles
#### Actual behavior

goes out of addon or keeps loading like searching and repeats error above
#### Steps to reproduce the behavior

1. each title search
2. click on list of all kinds
3. 

### Debug log

The debug log can be found from this link: https://pastebin.com/DP2rFmDK

#### Installation
* [ ] I'm using other Netflix Repo  
* [ ] I'm using a different source

**Comment by risogolo** [comment]
Same issue on rpi4 under librelec 9.2.1, I have been having this issue for some time already also with provious versions of this plugin

**Comment by baykant** [comment]
I had that issue on rpi 2 / libreelec 9.2.1 and having the same problem with rpi 4 / libreelec 9.2.3. When I get that error, most of the time the second attempt brings the list of titles.

**Comment by risogolo** [comment]
Yes but not everytime, there were situations that I was just simply not able to watch at all, FYI my internet connection is 120 Mb/s

**Comment by CastagnaIT** [comment]
without a full log as described in readme or Issue instructions can not help

**Comment by risogolo** [comment]
here you go:
2020-06-23 20:56:21.604 T:2523206512   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 207, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 38, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 72, in route
                                                _execute(nav_handler, pathitems[1:], g.REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 100, in _execute
                                                executor(pathitems=pathitems)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_utils.py", line 34, in set_custom_viewmode
                                                override_partial_setting_id = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 173, in video_list_sorted
                                                list_data, extra_data = common.make_call('get_video_list_sorted', call_args)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 89, in make_call
                                                return make_addonsignals_call(callname, data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 164, in make_addonsignals_call
                                                raise Exception('Addon Signals call timeout')
                                            Exception: Addon Signals call timeout

**Comment by CastagnaIT** [comment]
@risogolo follow rules

**Comment by risogolo** [comment]
**Platform**
RPI 4 / libreelec 9.2.1

**Steps:**
trying to browse titles or anything else

**Log:**
[https://pastebin.com/zmgwA4WT](url)

**Comment by CastagnaIT** [comment]
attach log it totally useless you have not follow the readme

**Comment by CastagnaIT** [comment]
Closed for inactivity
