### ISSUE TITLE
Show better error message on lapsed account

### ISSUE THREAD

**Issue by shtrom** [CastagnaIT/plugin.video.netflix#750]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [x] change an existing feature

### Describe your request

On an account that needs renewal (that I didn't know about), I get the standard “check the log file” error when trying to access any user.

Looking at the log file, this shows up in the stack trace
```2020-07-12 21:43:21.470 T:2227532656   ERROR: [plugin.video.netflix (0)] Can not login, the Membership status is FORMER_MEMBER
2020-07-12 21:43:21.470 T:2227532656   ERROR: [plugin.video.netflix (0)] IPC callback raised exception: FORMER_MEMBER
```

In those cases, it would be good to show a modal dialog, rather than a notification, explaining that the account needs reactivating.

#### Traceback
```
2020-07-12 21:43:21.471 T:2227532656   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 185, in make_return_call
                                                result = call(instance, func, data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 209, in call
                                                return func(instance)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_base.py", line 35, in ensure_login
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession.py", line 85, in fetch_initial_page
                                                api_data = self.website_extract_session_data(response, update_profiles=True)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession.py", line 273, in website_extract_session_data
                                                return website.extract_session_data(content, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/api/website.py", line 94, in extract_session_data
                                                raise InvalidMembershipStatusError(user_data.get('membershipStatus'))
                                            InvalidMembershipStatusError: FORMER_MEMBER
2020-07-12 21:43:21.477 T:2114220912   ERROR: [plugin.video.netflix (7)] IPC call fetch_initial_page returned InvalidMembershipStatusError: FORMER_MEMBER
2020-07-12 21:43:21.478 T:2114220912   ERROR: [plugin.video.netflix (7)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 207, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 38, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 72, in route
                                                _execute(nav_handler, pathitems[1:], g.REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 100, in _execute
                                                executor(pathitems=pathitems)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 59, in root
                                                common.make_call('fetch_initial_page')
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 88, in make_call
                                                return make_http_call(callname, data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 118, in make_http_call
                                                _raise_for_error(callname, result)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 173, in _raise_for_error
                                                raise apierrors.__dict__[result['error']](result['message'])
                                            InvalidMembershipStatusError: FORMER_MEMBER
```

**Comment by CastagnaIT** [comment]
thanks for the info
there are a lot of unknow error codes
i will add a message
