### ISSUE TITLE
Account login problem

### ISSUE THREAD

**Issue by swhr0903** [CastagnaIT/plugin.video.netflix#813]
#### Your Environment
- Netflix add-on version: 1.7.1
- Operating system version/name: coreELEC for N1 9.2.2 
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ √] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request
The account login always prompts that the password is wrong, but I log in to the App and web page normally

**Comment by CastagnaIT** [comment]
i need you write here an example
of your email and password used

i need to figure out what special chars there are or accented letters or other

**Comment by swhr0903** [comment]
But I logged in to this account before, but it didn’t work after reinstalling the system

**Comment by CastagnaIT** [comment]
so what else should i tell you?
read the FAQ https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Errors%29#email-or-password-is-incorrect

**Comment by swhr0903** [comment]
A new error message 
exception: SSLError

**Comment by CastagnaIT** [comment]
If you want other help sugget you to read the Readme:
https://github.com/CastagnaIT/plugin.video.netflix#something-doesnt-work

**Comment by swhr0903** [comment]
I don’t know what to say, I have tried different accounts, they are all the same, and the password is incorrect.

**Comment by CastagnaIT** [comment]
Look at the already opened Issue thread

**Comment by swhr0903** [comment]
Kodi logs：
2020-08-19 14:54:22.325 T:4088209424   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-08-19 14:55:05.789 T:3685942144   ERROR: [plugin.video.netflix (0)] Could not extract [u'models', u'playerModel', u'data', u'config', u'ui', u'initParams', u'apiUrl']
2020-08-19 14:55:05.790 T:3685942144   ERROR: [plugin.video.netflix (0)] Could not extract [u'models', u'playerModel', u'data', u'config', u'core', u'assets', u'core']
2020-08-19 14:55:05.791 T:3685942144   ERROR: [plugin.video.netflix (0)] Could not extract [u'models', u'playerModel', u'data', u'config', u'ui', u'initParams', u'uiVersion']
2020-08-19 14:55:06.503 T:3685942144   ERROR: [plugin.video.netflix (0)] Login not valid, error code incorrect_password
2020-08-19 14:55:22.615 T:3584471936   ERROR: [plugin.video.netflix (3)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 32, in wrapper
                                                func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 244, in run
                                                success = route(pathitems)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 87, in lazy_login_wrapper
                                                if _check_valid_credentials():
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 72, in _check_valid_credentials
                                                if not login():
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/api_requests.py", line 50, in login
                                                if not common.make_call('login'):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 164, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 86, in make_call
                                                return make_http_call(callname, data)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 105, in make_http_call
                                                urlopen(url=url, data=json.dumps(data).encode('utf-8'), timeout=IPC_TIMEOUT_SECS).read(),
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                              File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
                                              File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
                                              File "/usr/lib/python2.7/httplib.py", line 438, in begin
                                              File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
                                              File "/usr/lib/python2.7/socket.py", line 480, in readline
                                            timeout: timed out
2020-08-19 14:55:22.627 T:3617948544   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
2020-08-19 14:55:32.200 T:3685942144   ERROR: Traceback (most recent call last):
2020-08-19 14:55:32.201 T:3685942144   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
2020-08-19 14:55:32.201 T:3685942144   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
2020-08-19 14:55:32.201 T:3685942144   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2020-08-19 14:55:32.201 T:3685942144   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
2020-08-19 14:55:32.201 T:3685942144   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
2020-08-19 14:55:32.201 T:3685942144   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
2020-08-19 14:55:32.201 T:3685942144   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
2020-08-19 14:55:32.202 T:3685942144   ERROR: error: [Errno 32] Broken pipe
2020-08-19 14:55:32.210 T:4088209424   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed

**Comment by matthuo333** [comment]
> I don’t know what to say, I have tried different accounts, they are all the same, and the password is incorrect.

is it fixed ?
兄弟， 最后解决了么？

I also face same issue as you

**Comment by swhr0903** [comment]
我无意间先安装1.6再升级1.7后登陆成功，我也不知道跟这个升级有没有关系，是不是解决之道，你可以试试

**Comment by matthuo333** [comment]
> 我无意间先安装1.6再升级1.7后登陆成功，我也不知道跟这个升级有没有关系，是不是解决之道，你可以试试

我从1.5 升级 1.8 貌似不行。不过我是覆盖安装，不是先卸载后安装。

**Comment by matthuo333** [comment]
刚试了1.5.1 到1.7.1，不行啊~~·

**Comment by swhr0903** [comment]
多半跟这个没啥关系吧，我也是重装的时候无意间选了1.6安装，然后在插件里升级1.7，没想到登陆成功了，这东西自今我也搞明白啥原因，现在我已经放弃了用N1看Netflix，看个1080P也卡还音画不同步，我还是投屏了

**Comment by matthuo333** [comment]
不过和N1同价位的，没有啥更多选择

**Comment by matthuo333** [comment]
感觉是插件中记录了cookie，没有清空。导致NF那边还是认得之前账号。 可是怎么清空呢？

**Comment by swhr0903** [comment]
你可以在插件设置里logout试试，或者你向作者提帮助吧，其实我也不太清楚，我之前卸载过几次插件，甚至重刷过系统都没有用，后来也是无意间登陆上去的

**Comment by matthuo333** [comment]
看到 #502 issue, 他们在跟进，但目前看似没有结论。。。
