### ISSUE TITLE
search doesn't work (sqlite error)

### ISSUE THREAD

**Issue by Heiko-san** [CastagnaIT/plugin.video.netflix#854]
#### Your Environment
- Netflix add-on version: First tried 1.6.0 as this one was linked in the install howto, then upgraded to 1.9.0, still broken
- Operating system version/name: Ubuntu 20.04
- Device model:  Acer Laptop
- Kodi Version: 18.8 from kodi ppa

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux (Ubuntu 20.04)
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Installation worked fine, can ply video, but search feature doesn't work.  
It throws the following error:

```
2020-09-08 19:56:46.128 T:140167525395136   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-09-08 19:56:46.821 T:140166569228032   ERROR: GetDirectory - Error getting /home/hfi/.kodi/userdata/addon_data/plugin.video.netflix/movies
2020-09-08 19:56:46.821 T:140166569228032   ERROR: GetDirectory - Error getting special://profile/addon_data/plugin.video.netflix/movies
2020-09-08 19:56:46.821 T:140166569228032   ERROR: GetDirectory - Error getting /home/hfi/.kodi/userdata/addon_data/plugin.video.netflix/shows
2020-09-08 19:56:46.821 T:140166569228032   ERROR: GetDirectory - Error getting special://profile/addon_data/plugin.video.netflix/shows
2020-09-08 19:56:53.248 T:140166569228032   ERROR: [plugin.video.netflix (2)] SQLite error no such table: search:
2020-09-08 19:56:53.251 T:140166569228032   ERROR: [plugin.video.netflix (2)] Traceback (most recent call last):
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 33, in wrapper
                                                func(*args, **kwargs)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 249, in run
                                                success = route(pathitems)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 90, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 126, in route
                                                _execute(nav_handler, pathitems[1:], G.REQUEST_PARAMS)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 153, in _execute
                                                executor(pathitems=pathitems)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 277, in search
                                                route_search_nav(pathitems, self.perpetual_range_start, self.dir_update_listing, self.params)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_search.py", line 42, in route_search_nav
                                                search_list()
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_search.py", line 59, in search_list
                                                list_data = [_create_dictitem_from_row(row) for row in G.LOCAL_DB.get_search_list()]
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_base_sqlite.py", line 58, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_local.py", line 144, in get_search_list
                                                cur = self._execute_query(query, (guid,), cur)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_base_sqlite.py", line 150, in _execute_query
                                                raise_from(DBSQLiteError, exc)
                                              File "/home/hfi/.kodi/addons/script.module.future/libs/future/utils/__init__.py", line 456, in raise_from
                                                raise e
                                            DBSQLiteError
2020-09-08 19:56:56.525 T:140167370135296   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/directory/search/search/
2020-09-08 19:56:56.542 T:140167525395136   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/directory/search/search/) failed
```

#### Expected behavior

Menu entry "search" should allow to search for movies.

#### Actual behavio

see error above

#### Steps to reproduce the behavior

1. start kodi/addon
2. select profile
3. hit "search" entry

### Debug log

```
2020-09-08 20:23:08.063 T:140167525395136   DEBUG: ------ Window Init (Pointer.xml) ------
2020-09-08 20:23:09.709 T:140167525395136   DEBUG: Keyboard: scancode: 0x6f, sym: 0x273, unicode: 0x0000, modifier: 0x0
2020-09-08 20:23:09.709 T:140167525395136   DEBUG: HandleKey: up (0xf080) pressed, action is Up
2020-09-08 20:23:09.711 T:140167525395136   DEBUG: ------ Window Deinit (Pointer.xml) ------
2020-09-08 20:23:09.792 T:140167525395136   DEBUG: Keyboard: scancode: 0x6f, sym: 0x273, unicode: 0x0000, modifier: 0x0
2020-09-08 20:23:10.186 T:140167525395136   DEBUG: Previous line repeats 1 times.
2020-09-08 20:23:10.186 T:140167525395136   DEBUG: HandleKey: up (0xf080) pressed, action is Up
2020-09-08 20:23:10.261 T:140167525395136   DEBUG: Keyboard: scancode: 0x6f, sym: 0x273, unicode: 0x0000, modifier: 0x0
2020-09-08 20:23:10.363 T:140167525395136   DEBUG: Previous line repeats 1 times.
2020-09-08 20:23:10.363 T:140167525395136   DEBUG: HandleKey: up (0xf080) pressed, action is Up
2020-09-08 20:23:10.427 T:140167525395136   DEBUG: Keyboard: scancode: 0x6f, sym: 0x273, unicode: 0x0000, modifier: 0x0
2020-09-08 20:23:10.752 T:140167525395136   DEBUG: Keyboard: scancode: 0x74, sym: 0x274, unicode: 0x0000, modifier: 0x0
2020-09-08 20:23:10.752 T:140167525395136   DEBUG: HandleKey: down (0xf081) pressed, action is Down
2020-09-08 20:23:10.829 T:140167525395136   DEBUG: Keyboard: scancode: 0x74, sym: 0x274, unicode: 0x0000, modifier: 0x0
2020-09-08 20:23:10.962 T:140167525395136   DEBUG: Previous line repeats 1 times.
2020-09-08 20:23:10.962 T:140167525395136   DEBUG: HandleKey: down (0xf081) pressed, action is Down
2020-09-08 20:23:10.998 T:140167525395136   DEBUG: Keyboard: scancode: 0x74, sym: 0x274, unicode: 0x0000, modifier: 0x0
2020-09-08 20:23:11.379 T:140167525395136   DEBUG: Keyboard: scancode: 0x24, sym: 0x13, unicode: 0x000d, modifier: 0x0
2020-09-08 20:23:11.449 T:140167525395136   DEBUG: Keyboard: scancode: 0x24, sym: 0x13, unicode: 0x0000, modifier: 0x0
2020-09-08 20:23:11.449 T:140167525395136   DEBUG: HandleKey: return (0xf00d) pressed, action is Select
2020-09-08 20:23:11.450 T:140167525395136   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.netflix/directory/search/search/)
2020-09-08 20:23:11.450 T:140167525395136   DEBUG:   ParentPath = [plugin://plugin.video.netflix/directory/home/?switch_profile_guid=HREWA5FPNND5LL67GUZBSU3T24]
2020-09-08 20:23:11.451 T:140165734405888   DEBUG: Thread waiting start, auto delete: false
2020-09-08 20:23:11.546 T:140165792962304   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.netflix] took 95 ms
2020-09-08 20:23:11.547 T:140165734405888   DEBUG: StartScript - calling plugin Netflix('plugin://plugin.video.netflix/directory/search/search/','2','','resume:false')
2020-09-08 20:23:11.547 T:140165734405888   DEBUG: GetLanguageInvoker - Reusing LanguageInvokerThread 7 for script /home/hfi/.kodi/addons/plugin.video.netflix/addon.py
2020-09-08 20:23:11.547 T:140166569228032    INFO: initializing python engine.
2020-09-08 20:23:11.547 T:140166569228032   DEBUG: CPythonInvoker(7, /home/hfi/.kodi/addons/plugin.video.netflix/addon.py): start processing
2020-09-08 20:23:11.547 T:140166569228032   DEBUG: CPythonInvoker(7, /home/hfi/.kodi/addons/plugin.video.netflix/addon.py): entering source directory /home/hfi/.kodi/addons/plugin.video.netflix
2020-09-08 20:23:11.547 T:140166569228032   DEBUG: CPythonInvoker(7, /home/hfi/.kodi/addons/plugin.video.netflix/addon.py): instantiating addon using automatically obtained id of "plugin.video.netflix" dependent on version 2.26.0 of the xbmc.python api
2020-09-08 20:23:11.551 T:140167525395136   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-09-08 20:23:11.551 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
2020-09-08 20:23:11.552 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
2020-09-08 20:23:11.557 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CSettingsManager: requested setting (autoselect_profile_enabled) was not found.
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting autoselect_profile_enabled. Creating a setting on-the-fly...
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CSettingsManager: requested setting (autoselect_profile_name) was not found.
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting autoselect_profile_name. Creating a setting on-the-fly...
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CSettingsManager: requested setting (disable_modal_error_display) was not found.
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting disable_modal_error_display. Creating a setting on-the-fly...
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CSettingsManager: requested setting (info) was not found.
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting info. Creating a setting on-the-fly...
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CSettingsManager: requested setting (lib_sync_mylist_shw_profile) was not found.
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting lib_sync_mylist_shw_profile. Creating a setting on-the-fly...
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CSettingsManager: requested setting (library_playback_ask_profile) was not found.
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting library_playback_ask_profile. Creating a setting on-the-fly...
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CSettingsManager: requested setting (library_playback_profile) was not found.
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting library_playback_profile. Creating a setting on-the-fly...
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CSettingsManager: requested setting (migrate_library) was not found.
2020-09-08 20:23:11.558 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting migrate_library. Creating a setting on-the-fly...
2020-09-08 20:23:11.568 T:140166569228032   ERROR: [plugin.video.netflix (2)] SQLite error no such table: search:
2020-09-08 20:23:11.569 T:140166569228032   ERROR: [plugin.video.netflix (2)] Traceback (most recent call last):
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 33, in wrapper
                                                func(*args, **kwargs)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 249, in run
                                                success = route(pathitems)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 90, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 126, in route
                                                _execute(nav_handler, pathitems[1:], G.REQUEST_PARAMS)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 153, in _execute
                                                executor(pathitems=pathitems)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 277, in search
                                                route_search_nav(pathitems, self.perpetual_range_start, self.dir_update_listing, self.params)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_search.py", line 42, in route_search_nav
                                                search_list()
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_search.py", line 59, in search_list
                                                list_data = [_create_dictitem_from_row(row) for row in G.LOCAL_DB.get_search_list()]
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_base_sqlite.py", line 58, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_local.py", line 144, in get_search_list
                                                cur = self._execute_query(query, (guid,), cur)
                                              File "/home/hfi/.kodi/addons/plugin.video.netflix/resources/lib/database/db_base_sqlite.py", line 150, in _execute_query
                                                raise_from(DBSQLiteError, exc)
                                              File "/home/hfi/.kodi/addons/script.module.future/libs/future/utils/__init__.py", line 456, in raise_from
                                                raise e
                                            DBSQLiteError
2020-09-08 20:23:11.571 T:140167525395136   DEBUG: ------ Window Init (DialogConfirm.xml) ------
2020-09-08 20:23:12.532 T:140167525395136   DEBUG: Keyboard: scancode: 0x24, sym: 0x13, unicode: 0x000d, modifier: 0x0
2020-09-08 20:23:12.615 T:140167525395136   DEBUG: Keyboard: scancode: 0x24, sym: 0x13, unicode: 0x0000, modifier: 0x0
2020-09-08 20:23:12.615 T:140167525395136   DEBUG: HandleKey: return (0xf00d) pressed, action is Select
2020-09-08 20:23:12.867 T:140167525395136   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
2020-09-08 20:23:12.869 T:140165734405888   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/directory/search/search/
2020-09-08 20:23:12.869 T:140165734405888   DEBUG: Thread waiting 140165734405888 terminating
2020-09-08 20:23:12.871 T:140166569228032    INFO: CPythonInvoker(7, /home/hfi/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
2020-09-08 20:23:12.885 T:140167525395136   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-09-08 20:23:12.886 T:140167525395136   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/directory/search/search/) failed
2020-09-08 20:23:12.886 T:140167525395136   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.netflix/directory/home/?switch_profile_guid=HREWA5FPNND5LL67GUZBSU3T24)
2020-09-08 20:23:12.886 T:140167525395136   DEBUG:   ParentPath = []
2020-09-08 20:23:12.887 T:140165734405888   DEBUG: Thread waiting start, auto delete: false
2020-09-08 20:23:12.977 T:140165792962304   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.netflix] took 91 ms
2020-09-08 20:23:12.978 T:140165734405888   DEBUG: StartScript - calling plugin Netflix('plugin://plugin.video.netflix/directory/home/','2','?switch_profile_guid=HREWA5FPNND5LL67GUZBSU3T24','resume:false')
2020-09-08 20:23:12.978 T:140165734405888   DEBUG: GetLanguageInvoker - Reusing LanguageInvokerThread 7 for script /home/hfi/.kodi/addons/plugin.video.netflix/addon.py
2020-09-08 20:23:12.978 T:140166569228032    INFO: initializing python engine.
2020-09-08 20:23:12.978 T:140166569228032   DEBUG: CPythonInvoker(7, /home/hfi/.kodi/addons/plugin.video.netflix/addon.py): start processing
2020-09-08 20:23:12.979 T:140166569228032   DEBUG: CPythonInvoker(7, /home/hfi/.kodi/addons/plugin.video.netflix/addon.py): entering source directory /home/hfi/.kodi/addons/plugin.video.netflix
2020-09-08 20:23:12.979 T:140166569228032   DEBUG: CPythonInvoker(7, /home/hfi/.kodi/addons/plugin.video.netflix/addon.py): instantiating addon using automatically obtained id of "plugin.video.netflix" dependent on version 2.26.0 of the xbmc.python api
2020-09-08 20:23:12.982 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
2020-09-08 20:23:12.982 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
2020-09-08 20:23:12.987 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
2020-09-08 20:23:12.987 T:140167525395136   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CSettingsManager: requested setting (autoselect_profile_enabled) was not found.
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting autoselect_profile_enabled. Creating a setting on-the-fly...
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CSettingsManager: requested setting (autoselect_profile_name) was not found.
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting autoselect_profile_name. Creating a setting on-the-fly...
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CSettingsManager: requested setting (disable_modal_error_display) was not found.
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting disable_modal_error_display. Creating a setting on-the-fly...
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CSettingsManager: requested setting (info) was not found.
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting info. Creating a setting on-the-fly...
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CSettingsManager: requested setting (lib_sync_mylist_shw_profile) was not found.
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting lib_sync_mylist_shw_profile. Creating a setting on-the-fly...
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CSettingsManager: requested setting (library_playback_ask_profile) was not found.
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting library_playback_ask_profile. Creating a setting on-the-fly...
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CSettingsManager: requested setting (library_playback_profile) was not found.
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting library_playback_profile. Creating a setting on-the-fly...
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CSettingsManager: requested setting (migrate_library) was not found.
2020-09-08 20:23:12.989 T:140166569228032   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting migrate_library. Creating a setting on-the-fly...
2020-09-08 20:23:13.195 T:140166569228032    INFO: CPythonInvoker(7, /home/hfi/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
2020-09-08 20:23:13.196 T:140165734405888   DEBUG: Thread waiting 140165734405888 terminating
2020-09-08 20:23:13.200 T:140167525395136   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-09-08 20:23:13.204 T:140165734405888   DEBUG: Thread BackgroundLoader start, auto delete: false
2020-09-08 20:23:13.214 T:140165734405888   DEBUG: Thread BackgroundLoader 140165734405888 terminating
2020-09-08 20:23:13.486 T:140167525395136   DEBUG: Keyboard: scancode: 0x40, sym: 0x308, unicode: 0x0000, modifier: 0x256
2020-09-08 20:23:13.486 T:140167525395136   DEBUG: HandleKey: alt-leftalt (0x4f0d4) pressed, action is
2020-09-08 20:23:42.858 T:140165929101056   DEBUG: [plugin.googledrive][service-export-140165929101056]: export_map: {}
2020-09-08 20:23:42.978 T:140166584858368   DEBUG: Thread JobWorker 140166584858368 terminating (autodelete)
2020-09-08 20:23:42.978 T:140165792962304   DEBUG: Thread JobWorker 140165792962304 terminating (autodelete
```

#### Installation
* I'm using zip archive from this repo

**Comment by CastagnaIT** [comment]
reinstall from scratch last version
