### ISSUE TITLE
Authentication Key file not supported

### ISSUE THREAD

**Issue by Anan5a** [CastagnaIT/plugin.video.netflix#880]
#### Your Environment
- Netflix add-on version: 1.9.0 matrix.1 
- Operating system version/name: Debian 10 
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

Shows unsupported when trying to use Authentication.key file

```
NFAuthentication Key for linux (Version 1.0.1)

Disclaimer:
This script and source code available on GitHub are provided "as is" without warranty of any kind, either express or implied. Use at your own risk. The use of the software is done at your own discretion and risk with the agreement that you will be solely responsible for any damage resulting from such activities and you are solely responsible for adequate data protection.

Press "ENTER" key to accept the disclaimer and start, or "CTRL+C" to cancel
Browser startup... please wait
Establish connection with the browser... please wait
Opening login webpage... please wait
Please login in to website now ...waiting for you to finish...
Verification of data in progress... please wait
File creation in progress... please wait
Operations completed!
The "NFAuthentication.key" file has been saved in current folder.
Your PIN protection is: 6222
```
#### Expected behavior

Accept key file and login to Netflix
#### Actual behavior

Error: Unsupported
#### Steps to reproduce the behavior

1.Install plugin
2.Generate Key file
3.Try to use the key file

#### Possible fix

Donno :(
### Debug log

```
2020-10-01 12:18:43.492 T:6497    ERROR <general>: [plugin.video.netflix (1)] Traceback (most recent call last):
                                                     File "/home/ananta/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 33, in wrapper
                                                       func(*args, **kwargs)
                                                     File "/home/ananta/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 249, in run
                                                       success = route(pathitems)
                                                     File "/home/ananta/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 88, in lazy_login_wrapper
                                                       if _check_valid_credentials():
                                                     File "/home/ananta/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 73, in _check_valid_credentials
                                                       if not login():
                                                     File "/home/ananta/.kodi/addons/plugin.video.netflix/resources/lib/utils/api_requests.py", line 65, in login
                                                       data = common.run_nf_authentication_key()
                                                     File "/home/ananta/.kodi/addons/plugin.video.netflix/resources/lib/common/credentials.py", line 135, in run_nf_authentication_key
                                                       return _prepare_authentication_key_data(data)
                                                     File "/home/ananta/.kodi/addons/plugin.video.netflix/resources/lib/common/credentials.py", line 189, in _prepare_authentication_key_data
                                                       raise Exception('Authentication key file not supported')
                                                   Exception: Authentication key file not supported
                                                   
2020-10-01 12:18:43.505 T:6459     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2020-10-01 12:18:55.443 T:6497     INFO <general>: CPythonInvoker(2, /home/ananta/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
2020-10-01 12:18:55.443 T:6496    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.netflix/
2020-10-01 12:18:55.460 T:6459    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
2020-10-01 12:19:03.109 T:6459     INFO <general>: Loading skin file: DialogButtonMenu.xml, load type: KEEP_IN_MEMORY

```
#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by notoco** [comment]
Update to the last version: https://github.com/CastagnaIT/plugin.video.netflix/releases/tag/v1.9.1

> Add support to NFAuthenticationKey for linux

**Comment by Anan5a** [comment]
@CastagnaIT Install failed, xbmc.python 2.26... could not be satisfied

Kodi 19

**Comment by notoco** [comment]
You are trying to install the Kodi Leia version and not the Kodi Matrix version. Install version for k19 from matrix repository:
https://github.com/CastagnaIT/plugin.video.netflix/tree/matrix#installation--updates

**Comment by Anan5a** [comment]
Thanks @notoco 
I just modified the addon xml and installed just fine

**Comment by notoco** [comment]
You did wrong. On k19 you install the repository for kodi matrix and you don't have to do anything. Now you have the k18 version installed on the k19
