### ISSUE TITLE
Video doesn´t start

### ISSUE THREAD

**Issue by leubedane** [CastagnaIT/plugin.video.netflix#897]
#### Your Environment
- Netflix add-on version: 1.10.0
- Operating system version/name: Android 9.0.0 API Level 28 Linux 4.9.113
- Device model:  Minix NEO U22-XJ

Used Operating system:
* [ X] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
If I want to start a video, I get the following message:
Netflix returned the following error:
MSLError: This title is not available to watch instantly. Please try another title. - 1044

#### Expected behavior
The video should start

#### Actual behavior
The error message occurs

#### Steps to reproduce the behavior
1. Start any video in the list
2.
3.

### Debug log
2020-10-18 15:57:53.078 T:8842  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.netflix/play/show/80992775/season/81018796/episode/81021083/?profile_guid=FD4JV6BNZFC5TN5TBOQJ5VYNVQ
2020-10-18 15:57:53.088 T:8941  NOTICE: Creating InputStream
2020-10-18 15:57:53.128 T:8941   ERROR: AddOnLog: InputStream Adaptive: Key system request: com.widevine.alpha
2020-10-18 15:57:55.613 T:8911   ERROR: [plugin.video.netflix (0)] Full MSL error information:
2020-10-18 15:57:55.614 T:8911   ERROR: [plugin.video.netflix (0)] {"from": "nq_cadmium_pbo_licenses@2.47.0/pbo-client@2.47.0", "version": 2, "serverTime": 1603036677052, "id": 16030366754800, "result": [{"errorParams": {"drmSessionId": "sid5"}, "error": {"errorExternalCode": 0, "code": "FAIL", "bladeRunnerMessage": "license/pbl-1044: IssueLicensePolicyError (E2-BQFRAAELEH7MWIMiLDHkL7MpeXLYRhuAyVQB25bhKOdl7JdwbpHmheXUEPdIIrT_th-92rff43n9UefHT1XkKuOKh6gaglpRc1zfYvqIY_r9QKJyayNk8L7oixL9Yx9nFc6_ylMXwUIJYpntwieCHaP-ZqatjbJdYTHF4KhT2X2yEooeObQCSIIqcpRqoNp8GY82zJ-NKA-kWreIpGULlxAgOT9ZzR9G4bGjEs3Dd4txCOd0MHPSs1WMSF8fzCvCmcs4CR7Ma8PSRfFdpBejPal0L7z2l6l1Z16GMaQtmWZn0A..) (nq_cadmium_pbo_licenses@2.47.0/pbo-client@2.47.0)", "errorNccpCode": 0, "pboc": true, "alertTag": "", "detail": "license/pbl-1044: IssueLicensePolicyError (E2-BQFRAAELEH7MWIMiLDHkL7MpeXLYRhuAyVQB25bhKOdl7JdwbpHmheXUEPdIIrT_th-92rff43n9UefHT1XkKuOKh6gaglpRc1zfYvqIY_r9QKJyayNk8L7oixL9Yx9nFc6_ylMXwUIJYpntwieCHaP-ZqatjbJdYTHF4KhT2X2yEooeObQCSIIqcpRqoNp8GY82zJ-NKA-kWreIpGULlxAgOT9ZzR9G4bGjEs3Dd4txCOd0MHPSs1WMSF8fzCvCmcs4CR7Ma8PSRfFdpBejPal0L7z2l6l1Z16GMaQtmWZn0A..) (nq_cadmium_pbo_licenses@2.47.0/pbo-client@2.47.0)", "errorDisplayMessage": "This title is not available to watch instantly. Please try another title. - 1044", "nccpError": {}, "bladeRunnerCode": "1044", "errorActionId": 3, "errorSubCode": 0, "errorReasonCode": 0, "display": "This title is not available to watch instantly. Please try another title. - 1044"}}]}
2020-10-18 15:57:57.302 T:8842 WARNING: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2020-10-18 15:57:57.407 T:8911 WARNING: Previous line repeats 4 times.
2020-10-18 15:57:57.407 T:8911   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/http_server.py", line 55, in do_POST
                                                challenge=data[0], sid=base64.standard_b64decode(data[1]).decode('utf-8'))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_utils.py", line 59, in error_catching_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 168, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 265, in get_license
                                                get_esn())
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 168, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_requests.py", line 169, in chunked_request
                                                save_uid_token_to_owner=auth_data['user_id_token'] is None)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 168, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_requests.py", line 212, in _process_chunked_response
                                                return _raise_if_error(decrypted_response)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_requests.py", line 237, in _raise_if_error
                                                raise MSLError(_get_error_details(decoded_response))
                                            MSLError: This title is not available to watch instantly. Please try another title. - 1044
2020-10-18 15:57:57.409 T:8941   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 500
2020-10-18 15:57:57.409 T:8941   ERROR: CCurlFile::Open failed with code 500 for http://127.0.0.1:51557/license?id=81021083:
2020-10-18 15:57:57.410 T:8941   ERROR: AddOnLog: InputStream Adaptive: License server returned failure
2020-10-18 15:57:57.413 T:8941   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
2020-10-18 15:57:57.416 T:8911   ERROR: Traceback (most recent call last):
2020-10-18 15:57:57.416 T:8911   ERROR:   File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
2020-10-18 15:57:57.416 T:8911   ERROR:   File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/SocketServer.py", line 318, in process_request
2020-10-18 15:57:57.417 T:8911   ERROR:   File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/SocketServer.py", line 331, in finish_request
2020-10-18 15:57:57.417 T:8911   ERROR:   File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/SocketServer.py", line 654, in __init__
2020-10-18 15:57:57.417 T:8911   ERROR:   File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/SocketServer.py", line 713, in finish
2020-10-18 15:57:57.417 T:8911   ERROR:   File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/socket.py", line 283, in close
2020-10-18 15:57:57.417 T:8911   ERROR:   File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/socket.py", line 307, in flush
2020-10-18 15:57:57.417 T:8911   ERROR: error: [Errno 32] Broken pipe
2020-10-18 15:57:57.419 T:8941   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/play/show/80992775/season/81018796/episode/81021083/?profile_guid=FD4JV6BNZFC5TN5TBOQJ5VYNVQ]
2020-10-18 15:57:57.419 T:8941  NOTICE: CVideoPlayer::OnExit()
2020-10-18 15:57:57.436 T:8842  NOTICE: CVideoPlayer::CloseFile()
2020-10-18 15:57:57.437 T:8842  NOTICE: VideoPlayer: waiting for threads to exit
2020-10-18 15:57:57.437 T:8842  NOTICE: VideoPlayer: finished waiting
2020-10-18 15:57:57.513 T:8881 WARNING: [plugin.video.netflix (0)] ActionController: Possible problem with video playback, action managers disabled.
2020-10-18 15:58:02.973 T:8842  NOTICE: CWinSystemAndroid::DestroyWindow
2020-10-18 15:58:02.994 T:8823 WARNING: CPeripheralBusAndroid: failed to update input device with ID 3 because it couldn't be found
2020-10-18 15:58:14.006 T:8842  NOTICE: CAndroidUtils: SetNativeResolution: 1: 1920x1080 1920x1080@60.000004
2020-10-18 15:58:14.007 T:8842  NOTICE: GL_VENDOR = ARM
2020-10-18 15:58:14.007 T:8842  NOTICE: GL_RENDERER = Mali-G52
2020-10-18 15:58:14.007 T:8842  NOTICE: GL_VERSION = OpenGL ES 3.2 v1.r16p0-01rel0.45b161e1b2cff94b03faf73ffeb6b9a5
2020-10-18 15:58:14.007 T:8842  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.20
2020-10-18 15:58:14.008 T:8842  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_astc_decode_mode GL_EXT_texture_compression_astc_decode_mode_rgb9e5 GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_EGL_image_array GL_EXT_texture_filter_anisotropic

#### Installation
* [X ] I'm using other Netflix Repo CastagnaIT Repo for Kodi 18.x
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
wiki explains

**Comment by leubedane** [comment]
Hi @CastagnaIT ,
at which section it is explained? I didn't find it, so I opened this ticket. Sorry for interrupting.
