### ISSUE TITLE
No videos will play | object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by dm2912** [CastagnaIT/plugin.video.netflix#929]
#### Your Environment
- Netflix add-on version: latest release 1.10.1
- Operating system version/name: CoreElec Nightly / Kodi 18.9.8
- Device model:  TX3 S905X3

Used Operating system:

* [x ] Linux

### Describe the bug

object of type 'NoneType' has no len() when trying to play any videos. This came after initial setup and post widevine install. 

Rebooting as suggested in another issue did not solve it. 

#### Expected behavior

Expect to play video

#### Actual behavior

As above

#### Steps to reproduce the behavior

1. Clean install of Corelec, latest version of netflix app. 

### Debug log

```
2020-11-06 04:00:34.782 T:3867984768  NOTICE: Previous line repeats 2 times.
2020-11-06 04:00:34.782 T:3867984768   ERROR: EXCEPTION: Invalid setting type
2020-11-06 04:00:34.783 T:3867984768  NOTICE: [script.module.inputstreamhelper] Widevine update check was made on 2020-11-06 03:47
2020-11-06 04:00:35.544 T:4062453776  NOTICE: VideoPlayer::OpenFile: /storage/.kodi/userdata/addon_data/plugin.video.netflix/shows/Community/S05E03.strm
2020-11-06 04:00:35.546 T:3156251520  NOTICE: Creating InputStream
2020-11-06 04:00:35.666 T:3156251520   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2020-11-06 04:00:41.622 T:3231548288   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/http_server.py", line 75, in do_GET
                                                data = self.server.msl_handler.load_manifest(int(params['id'][0]))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_utils.py", line 61, in error_catching_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 164, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 130, in load_manifest
                                                manifest = self._load_manifest(viewable_id, get_esn())
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 164, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 230, in _load_manifest
                                                disable_msl_switch=False)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 164, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_requests.py", line 168, in chunked_request
                                                self._post(endpoint, self.msl_request(request_data, esn, auth_data)),
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 164, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_request_builder.py", line 52, in msl_request
                                                return (json.dumps(self._signed_header(esn, auth_data)) +
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_request_builder.py", line 71, in _signed_header
                                                encryption_envelope = self.crypto.encrypt(self._headerdata(auth_data=auth_data, esn=esn), esn)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/default_crypto.py", line 80, in encrypt
                                                cipher = AES.new(self.encryption_key, AES.MODE_CBC, init_vector)
                                              File "/usr/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 232, in new
                                              File "/usr/lib/python2.7/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
                                              File "/usr/lib/python2.7/site-packages/Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
                                              File "/usr/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 92, in _create_base_cipher
                                            TypeError: object of type 'NoneType' has no len()
2020-11-06 04:00:41.623 T:3156251520   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
2020-11-06 04:00:41.623 T:3156251520   ERROR: CCurlFile::Open failed with code 400 for http://127.0.0.1:53953/manifest?id=80033505:
2020-11-06 04:00:41.623 T:3156251520   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://127.0.0.1:53953/manifest?id=80033505
2020-11-06 04:00:41.624 T:3156251520   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://127.0.0.1:53953/manifest?id=80033505)
2020-11-06 04:00:41.624 T:3231548288   ERROR: Traceback (most recent call last):
2020-11-06 04:00:41.624 T:3231548288   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
2020-11-06 04:00:41.624 T:3231548288   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
2020-11-06 04:00:41.624 T:3231548288   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2020-11-06 04:00:41.625 T:3231548288   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
2020-11-06 04:00:41.625 T:3231548288   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
2020-11-06 04:00:41.625 T:3231548288   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
2020-11-06 04:00:41.625 T:3231548288   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
2020-11-06 04:00:41.625 T:3231548288   ERROR: error: [Errno 32] Broken pipe
2020-11-06 04:00:41.626 T:3156251520   ERROR: CVideoPlayer::OpenInputStream - error opening [/storage/.kodi/userdata/addon_data/plugin.video.netflix/shows/Community/S05E03.strm]
2020-11-06 04:00:41.626 T:3156251520  NOTICE: CVideoPlayer::OnExit()
2020-11-06 04:00:41.657 T:4062453776  NOTICE: CVideoPlayer::CloseFile()
2020-11-06 04:00:41.684 T:4062453776  NOTICE: VideoPlayer: waiting for threads to exit
2020-11-06 04:00:41.684 T:4062453776  NOTICE: VideoPlayer: finished waiting
2020-11-06 04:00:41.686 T:3640640384 WARNING: [plugin.video.netflix (0)] ActionController: Possible problem with video playback, action managers disabled.
2020-11-06 04:00:43.735 T:3649033088  NOTICE: [plugin.video.themoviedb.helper]
                                            HTTP Error Code: 404 
                                            Request: https://api.themoviedb.org/3/search/season?&language=en-GB&include_image_language=en,null&query=Community&region=GB
2020-11-06 04:00:45.048 T:3828872064   ERROR: GetDirectory - Error getting include
2020-11-06 04:00:47.310 T:3933184896   ERROR: Previous line repeats 37 times.
2020-11-06 04:00:47.310 T:3933184896   ERROR: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/6/6d61f70f.jpg
2020-11-06 04:00:47.318 T:3828872064   ERROR: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/5/5b322a7a.jpg
2020-11-06 04:00:47.319 T:3876377472   ERROR: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/0/01b9d5bf.jpg
2020-11-06 04:00:47.321 T:3206370176   ERROR: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/1/1397a10e.jpg
2020-11-06 04:00:47.666 T:3933184896   ERROR: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/7/74ea69fc.jpg
2020-11-06 04:00:47.686 T:3876377472   ERROR: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/e/e362d8f6.jpg
2020-11-06 04:00:48.436 T:3828872064   ERROR: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/b/b635284a.jpg
2020-11-06 04:00:48.693 T:3649033088  NOTICE: [plugin.video.themoviedb.helper]
                                            HTTP Error Code: 404 
                                            Request: https://api.themoviedb.org/3/search/episode?&language=en-GB&include_image_language=en,null&query=La Révolution&region=GB
2020-11-06 04:00:52.353 T:3126932352  NOTICE: Previous line repeats 1 times.
2020-11-06 04:00:52.353 T:3126932352   ERROR: EXCEPTION: Invalid setting type
2020-11-06 04:00:52.354 T:3126932352  NOTICE: [script.module.inputstreamhelper] Widevine update check was made on 2020-11-06 03:47
2020-11-06 04:00:52.974 T:4062453776  NOTICE: VideoPlayer::OpenFile: /storage/.kodi/userdata/addon_data/plugin.video.netflix/shows/La Révolution/S01E03.strm
2020-11-06 04:00:52.980 T:3099579264  NOTICE: Creating InputStream
2020-11-06 04:00:53.009 T:3099579264   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2020-11-06 04:00:54.658 T:3231548288   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/http_server.py", line 75, in do_GET
                                                data = self.server.msl_handler.load_manifest(int(params['id'][0]))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_utils.py", line 61, in error_catching_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 164, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 130, in load_manifest
                                                manifest = self._load_manifest(viewable_id, get_esn())
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 164, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_handler.py", line 230, in _load_manifest
                                                disable_msl_switch=False)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 164, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_requests.py", line 168, in chunked_request
                                                self._post(endpoint, self.msl_request(request_data, esn, auth_data)),
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 164, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_request_builder.py", line 52, in msl_request
                                                return (json.dumps(self._signed_header(esn, auth_data)) +
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/msl_request_builder.py", line 71, in _signed_header
                                                encryption_envelope = self.crypto.encrypt(self._headerdata(auth_data=auth_data, esn=esn), esn)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/msl/default_crypto.py", line 80, in encrypt
                                                cipher = AES.new(self.encryption_key, AES.MODE_CBC, init_vector)
                                              File "/usr/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 232, in new
                                              File "/usr/lib/python2.7/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
                                              File "/usr/lib/python2.7/site-packages/Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
                                              File "/usr/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 92, in _create_base_cipher
                                            TypeError: object of type 'NoneType' has no len()
2020-11-06 04:00:54.659 T:3099579264   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
2020-11-06 04:00:54.659 T:3099579264   ERROR: CCurlFile::Open failed with code 400 for http://127.0.0.1:53953/manifest?id=81021085:
2020-11-06 04:00:54.659 T:3099579264   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://127.0.0.1:53953/manifest?id=81021085
2020-11-06 04:00:54.659 T:3099579264   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://127.0.0.1:53953/manifest?id=81021085)
2020-11-06 04:00:54.660 T:3231548288   ERROR: Traceback (most recent call last):
2020-11-06 04:00:54.660 T:3231548288   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
2020-11-06 04:00:54.660 T:3231548288   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
2020-11-06 04:00:54.660 T:3231548288   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2020-11-06 04:00:54.660 T:3231548288   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
2020-11-06 04:00:54.661 T:3231548288   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
2020-11-06 04:00:54.661 T:3231548288   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
2020-11-06 04:00:54.661 T:3231548288   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
2020-11-06 04:00:54.661 T:3231548288   ERROR: error: [Errno 32] Broken pipe
2020-11-06 04:00:54.662 T:3099579264   ERROR: CVideoPlayer::OpenInputStream - error opening [/storage/.kodi/userdata/addon_data/plugin.video.netflix/shows/La Révolution/S01E03.strm]
2020-11-06 04:00:54.662 T:3099579264  NOTICE: CVideoPlayer::OnExit()
2020-11-06 04:00:54.691 T:4062453776  NOTICE: CVideoPlayer::CloseFile()
2020-11-06 04:00:54.718 T:3640640384 WARNING: [plugin.video.netflix (0)] ActionController: Possible problem with video playback, action managers disabled.
2020-11-06 04:00:54.718 T:4062453776  NOTICE: VideoPlayer: waiting for threads to exit
2020-11-06 04:00:54.718 T:4062453776  NOTICE: VideoPlayer: finished waiting
2020-11-06 04:00:55.647 T:3876377472   ERROR: GetDirectory - Error getting include
```

http://paste.kodi.tv/kirulonabu

Had checked this https://github.com/CastagnaIT/plugin.video.netflix/issues/171 thread but that just said to reboot. 

Have also tried uninstall, reboot, reinstall, reboot route..

**Comment by dm2912** [comment]
And on fresh install with no other addons, clean netflix install, same issue

http://paste.kodi.tv/ibegekadob

**Comment by CastagnaIT** [comment]
Hi
to try understand something i need a more detailed log then follow these steps in this order:
1. remove the NF addon and his user data when prompt
2. enable Kodi debug
3. reboot device
4. after the reboot, check if kodi debug is still enabled
5. install this addon version: [plugin.video.netflix_1.10.1_20201106_DebugOn.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5499875/plugin.video.netflix_1.10.1_20201106_DebugOn.zip)
6. try reproduce the error
7. get the big log

**Comment by dm2912** [comment]
hmmm. did that, used that version, first episode i tested played off the bat... :)
