### ISSUE TITLE
The Spanish tracks (es-ES) are not selected automatically

### ISSUE THREAD

**Issue by Paco8** [CastagnaIT/plugin.video.netflix#962]
#### Your Environment
- Netflix add-on version: 1.11.0
- Operating system version/name: Ubuntu 16.04
- I'm using Kodi 18.9.

Used Operating system:
* [ ] Android
* [ ] iOS
* [x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

I selected Spanish as preferred language for subtitles in the kodi settings.
When I play a video in the netflix addon the subtitles are turned off. I have to manually select "Spanish - Spain".
If I select Spanish as preferred audio language, instead of Spanish it plays by default with the English track, I have to manually select "Spanish - Spain".

#### Expected behavior

The Spanish track should be automatically selected by kodi.

#### Actual behavior

The subtitles are turned off.
Kodi seems to select the "default" audio track, which may be English.

#### Steps to reproduce the behavior

1. Select Spanish as preferred language for audio and subtitles in the Kodi settings.
2. Play a video in the netflix addon which has an "es-ES" audio or subtitle track.

#### Possible fix

Aparently the language code (es-ES) has to be changed to "es" so that kodi could select it automatically. I was using version 0.16.3 and it worked as expected, but now I updated to 1.11.0 and this problem is happening.
I think the problem is that the addon is changing the code to "es-Spain" instead of "es".
Probably the bug was introduced in this commit: https://github.com/CastagnaIT/plugin.video.netflix/commit/8af12f54d985ec4b7848a1a074d536e4fe2de337

**Comment by CastagnaIT** [comment]
enable "Prefer the audio/subtitle language with coutry code" in addon Playback settings

a important note:
when you manually change the audio/subtitle setting for an episode/movie
this setting is permanently stored in the kodi/addon database
you have to try to see if works with a never watched TvShow (without change manually the sudio/subtitle settings so than kodi/addon not save permanently the changes)

**Comment by Paco8** [comment]
I'm afraid I can't find that option in the addon settings:
https://imgur.com/a/bb8ZogB

**Comment by CastagnaIT** [comment]
yes now remember on kodi 18 this has been disabled due to some kodi 18 limits
i will try to see if can be enabled without side effect

**Comment by CastagnaIT** [comment]
I have enabled the new setting "Prefer the audio/subtitle language with coutry code" 
but on kodi 18 has side effects with subtitles, that will be disabled due to kodi problem
[plugin.video.netflix_1.11.0_20201205_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5646814/plugin.video.netflix_1.11.0_20201205_t1.zip)

I will not make any other changes on this
switch to Kodi 19 or keep it that way

**Comment by CastagnaIT** [comment]
> Aparently the language code (es-ES) has to be changed to "es" so that kodi could select it automatically

yes, it used to work like this,
previoulsy it was exchanged in this way, was depend on how many language are listed on a video:
when only a single "es-es" was present (so without "es" track), was replaced to "es"
a user may get confused because sometimes the "es" track can be "es-spain" or "es" likewise

this way was wrong, replacing the language code causes incorrect descriptions and mixture
we have to work on the default track to be set to kodi, so that the kodi player plays the lang track we want to play.

so now the behaviour is:
when only single "es-es" is present, is replaced to "es-Spain"
a user always knows that the track is es-Spain and cannot get confused

**Comment by Paco8** [comment]
Yes, "es-Spain" is clearer for the user but the problem is that if the code is "es-Spain" instead of "es" then kodi doesn't select it automatically and the user has to do it manually. Unless they finally fixed it in kodi 19.

**Comment by CastagnaIT** [comment]
sorry i was in error
the test version works

i tried tvshow "Vis vis" ep 1x10
have audio es-Spain and the subtitle es-Spain forced
the subtitles es-Spain forced are selected and enabled in right way

I got confused before because some tvshows have only "es-Spain" subtitles [captions] for impaired and not normal subtitle
then are select only if Kodi is set to prefer subtitles for impaired

i think that you can confirm

**Comment by CastagnaIT** [comment]
Use this test: [plugin.video.netflix_1.11.0_20201206_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5648624/plugin.video.netflix_1.11.0_20201206_t2.zip)
the previous i forgot to enable the new setting menu for you

**Comment by Paco8** [comment]
I'm afraid it doesn't work for me even after enabling the option "Prefer the audio/subtitle language with coutry code". The Spanish track is not selected automatically.

I suggest the following: when the code "es-es" is found, check if there's another track with the code "es", in that case rename "es-es" to "es-Spain". If there isn't a "es" track then rename "es-es" as "es". That way there couldn't be any confusion and there will always be at least a track with the code "es" so kodi will use it automatically.

**Comment by CastagnaIT** [comment]
> I'm afraid it doesn't work for me

if it does not work it means that Kodi and/or the addon has stored the old audio/subtitle setting for a tvshow/movie
to full exclude this "problem" you have to install from scratch both Kodi and the NF Addon
keep enabled "Prefer the audio/subtitle language with coutry code"

**Comment by CastagnaIT** [comment]
i will recheck next days

**Comment by Paco8** [comment]
I tested again. That option works with the audio but not with the subtitles.

**Comment by CastagnaIT** [comment]
I did a lot of tests today, and i found the cause
when i made the mentioned commit i didn't notice this difference so:

if you set Kodi player with "preferred audio language" to "Media default"
all work good without problem with audio/subtitles tracks

but

if you set Kodi player with "preferred audio language" to a language name,
"Prefer the audio/subtitle language with coutry code" option, not works anymore and unfurnately this happen also on Kodi 19

For Kodi 19 i have done a fix, but can not be ported to Kodi 18,
then for Kodi 18 the only solutions is:
when the "preferred audio language" is not "Media default" but a language name
then use the previous old behaviour (that mix/replace the language code)

Kodi 18 is a crap...i will soon split the entire addon code and i will limit Kodi 18 to extraordinary maintenance only

**Comment by CastagnaIT** [comment]
Restored previous behaviour for kodi 18, please try on a clean kodi:
[plugin.video.netflix_1.11.0_20201208_t3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5659287/plugin.video.netflix_1.11.0_20201208_t3.zip)

**Comment by Paco8** [comment]
Yes, it works perfectly now.

**Comment by Paco8** [comment]
I installed version 1.13.0 on Kodi 19 and I'm afraid the problem has returned.
This is my configuration: in the player settings, language, I set the preferred audio language to English and the preferred subtitle language to Spanish. In the addon the option to prefer audio/subtitle language with country code is enabled.

Now I play a video that I never played. The audio is in English but the subtitles in Spanish are not displayed. In the subtitle menu the subtitles are disabled, and the selected subtitle track is Arabic.

Now I go to the Kodi settings and change the preferred audio language to Spanish. I play the same video (or another one, the result is the same). Now the audio track is correctly selected to Spanish AND the subtitle track in Spanish is also selected and displayed.

So it seems the Spanish subtitle track is only selected if the audio is also in Spanish. But this is not the behaviour I would expect.

**Comment by CastagnaIT** [comment]
I will check the code, unfortunately there are many things to take into account and it is not easy to solve everything in easy way without exhausting tests

>  I set the preferred audio language to English and the preferred subtitle language to Spanish.
> ... The audio is in English but the subtitles in Spanish are not displayed

please pay attention to every labels on subtitles tracks that could deceive you,
if on available subtitles the Spanish one, exist only the `[captions]` track then Kodi not display it and disable the subtitles, because is needed to enable the Kodi subtitles for impaired setting

**Comment by jakermx** [comment]
Steffano..I think that the set as Default option should grab and save ID and Languague Description....and select Description for next playback, instead of Id...since sometimes...not always, the id changes....and the player sleects by default another than selected before....but it always grab the correct one if Regional Settings are set as desired....but once set itin subtittles pages...cannot beoverrided by Regional settings

**Comment by CastagnaIT** [comment]
@Paco8 i revisited the code please try:
[plugin.video.netflix_1.13.0+matrix.1_20210116.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5824406/plugin.video.netflix_1.13.0%2Bmatrix.1_20210116.zip)

**please ensure that in Playback settings these are set as:**
Force the display of forced subtitles only... OFF
Always show the subtitles when the preferred audio... OFF

because i have not finished fix the source code
let me know if now can be good

**Comment by CastagnaIT** [comment]
use this: (i forgot to delete a thing)
[plugin.video.netflix_1.13.0+matrix.1_20210116_t2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5824411/plugin.video.netflix_1.13.0%2Bmatrix.1_20210116_t2.zip)

**Comment by Paco8** [comment]
I can't check if this is fixed, I'm getting this error when I try to enter in any of the folders:

```
2021-01-17 08:17:46.142 T:11580    INFO <general>: [plugin.video.netflix (1)] The debug logging level is set as "Verbose"
2021-01-17 08:17:46.309 T:11580    INFO <general>: [plugin.video.netflix (1)] Started (Version 1.13.0+matrix.1)
2021-01-17 08:17:46.309 T:11580    INFO <general>: [plugin.video.netflix (1)] URL is ParseResult(scheme='plugin', netloc='plugin.video.netflix', path='/', params='', query='', fragment='')
2021-01-17 08:17:46.549 T:11040   ERROR <general>: [plugin.video.netflix (0)] IPC callback raised exception: 'DefaultCookiePolicy' object has no attribute 'secure_protocols'
2021-01-17 08:17:46.553 T:11040   ERROR <general>: [plugin.video.netflix (0)] Traceback (most recent call last):
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\ipc.py", line 193, in _perform_ipc_return_call
                                                       result = _call(func, data)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\ipc.py", line 234, in _call
                                                       return func()
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\logging.py", line 148, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\nfsession_ops.py", line 81, in fetch_initial_page
                                                       self.refresh_session_data(True)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\nfsession_ops.py", line 90, in refresh_session_data
                                                       response = self.get_safe('browse')
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\session\access.py", line 67, in get_safe
                                                       return self.get(endpoint, **kwargs)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\session\http_requests.py", line 35, in get
                                                       return self._request_call(
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\logging.py", line 148, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\session\http_requests.py", line 49, in _request_call
                                                       return self._request(method, endpoint, None, **kwargs)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\session\http_requests.py", line 73, in _request
                                                       req_prep = req.prepare()
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 257, in prepare
                                                       p.prepare(
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 315, in prepare
                                                       self.prepare_cookies(cookies)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 572, in prepare_cookies
                                                       cookie_header = get_cookie_header(self._cookies, self)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\cookies.py", line 142, in get_cookie_header
                                                       jar.add_cookie_header(r)
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\cookiejar.py", line 1365, in add_cookie_header
                                                       cookies = self._cookies_for_request(request)
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\cookiejar.py", line 1291, in _cookies_for_request
                                                       cookies.extend(self._cookies_for_domain(domain, request))
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\cookiejar.py", line 1280, in _cookies_for_domain
                                                       if not self._policy.return_ok(cookie, request):
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\cookiejar.py", line 1102, in return_ok
                                                       if not fn(cookie, request):
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\cookiejar.py", line 1128, in return_ok_secure
                                                       if cookie.secure and request.type not in self.secure_protocols:
                                                   AttributeError: 'DefaultCookiePolicy' object has no attribute 'secure_protocols'
                                                   
2021-01-17 08:17:46.593 T:11580   ERROR <general>: [plugin.video.netflix (1)] Traceback (most recent call last):
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 29, in wrapper
                                                       func(*args, **kwargs)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 253, in run
                                                       success = route(pathitems)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 87, in lazy_login_wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 126, in route
                                                       _execute(nav_handler, pathitems[1:], G.REQUEST_PARAMS, root_handler)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 156, in _execute
                                                       executor(pathitems=pathitems)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\navigation\directory.py", line 61, in root
                                                       common.make_call('fetch_initial_page')
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\logging.py", line 148, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\ipc.py", line 80, in make_call
                                                       return make_addonsignals_call(callname, data)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\ipc.py", line 142, in make_addonsignals_call
                                                       _raise_for_error(result)
                                                     File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\ipc.py", line 154, in _raise_for_error
                                                       raise Exception(result['class'] + '\r\nError details:\r\n' + result.get('message', '--'))
                                                   Exception: AttributeError
                                                   Error details:
                                                   'DefaultCookiePolicy' object has no attribute 'secure_protocols'
                                                   
```

**Comment by CastagnaIT** [comment]
weird.. take this:
[plugin.video.netflix_1.13.0+matrix.1_20210117.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5825751/plugin.video.netflix_1.13.0%2Bmatrix.1_20210117.zip)

**Comment by Paco8** [comment]
Yes, it seems the problem is fixed now.
